<?php
/**
 * Shared tool list data.
 *
 * Future language support:
 * 1. Add a new locale entry under "locales" with its directory, labels, and translated tools.
 * 2. Create localized tool pages in languages/<directory>/ using the shared localized route slugs.
 * 3. Add a thin wrapper file that passes the locale code to tool-list-renderer.php.
 *
 * Non-English locales only render tools that have both:
 * - a translated entry in the locale pack
 * - a localized page file that exists on disk
 */

if (!function_exists('getSharedToolListData')) {
    function getSharedToolListData()
    {
        return [
            'categories' => [
                'keyboard' => [
                    'order' => 1,
                    'accent' => '#2563eb',
                    'soft' => 'rgba(37, 99, 235, 0.14)',
                    'strong' => 'rgba(37, 99, 235, 0.26)',
                ],
                'mouse' => [
                    'order' => 2,
                    'accent' => '#059669',
                    'soft' => 'rgba(5, 150, 105, 0.14)',
                    'strong' => 'rgba(5, 150, 105, 0.26)',
                ],
                'display' => [
                    'order' => 3,
                    'accent' => '#d97706',
                    'soft' => 'rgba(217, 119, 6, 0.14)',
                    'strong' => 'rgba(217, 119, 6, 0.26)',
                ],
                'camera' => [
                    'order' => 4,
                    'accent' => '#0891b2',
                    'soft' => 'rgba(8, 145, 178, 0.14)',
                    'strong' => 'rgba(8, 145, 178, 0.26)',
                ],
                'audio' => [
                    'order' => 5,
                    'accent' => '#db2777',
                    'soft' => 'rgba(219, 39, 119, 0.14)',
                    'strong' => 'rgba(219, 39, 119, 0.26)',
                ],
                'utility' => [
                    'order' => 6,
                    'accent' => '#7c3aed',
                    'soft' => 'rgba(124, 58, 237, 0.14)',
                    'strong' => 'rgba(124, 58, 237, 0.26)',
                ],
                'gaming' => [
                    'order' => 7,
                    'accent' => '#ea580c',
                    'soft' => 'rgba(234, 88, 12, 0.14)',
                    'strong' => 'rgba(234, 88, 12, 0.26)',
                ],
            ],
            'tools' => [
                [
                    'id' => 'keyboard-home',
                    'category' => 'keyboard',
                    'icon' => 'keyboard',
                    'name' => 'Keyboard Tester',
                    'description' => 'Test keyboard functionality, detect ghosting, measure latency, check for stuck keys',
                    'cta' => 'Test your keyboard',
                    'routes' => ['en' => 'tools/keyboard-tester/', 'localized' => ''],
                ],
                [
                    'id' => 'arabic-keyboard',
                    'category' => 'keyboard',
                    'icon' => 'keyboard',
                    'name' => 'Arabic Keyboard Tester',
                    'description' => 'Test Arabic keyboard layout and key response in an Arabic-first interface',
                    'cta' => 'Test Arabic layout',
                    'routes' => ['en' => 'languages/arabic/'],
                    'visible_locales' => ['en'],
                ],
                [
                    'id' => 'typing-test',
                    'category' => 'keyboard',
                    'icon' => 'typing',
                    'name' => 'Typing Speed Test',
                    'description' => 'Measure WPM, accuracy, and typing consistency',
                    'cta' => 'Check typing speed',
                    'routes' => ['en' => 'keyboard_typing_test.php', 'localized' => 'typing-test.php'],
                ],
                [
                    'id' => 'latency-checker',
                    'category' => 'keyboard',
                    'icon' => 'clock',
                    'name' => 'Latency Checker',
                    'description' => 'Test device and input latency in your browser',
                    'cta' => 'Measure latency',
                    'routes' => ['en' => 'latency-checker.php', 'localized' => 'latency-checker.php'],
                ],
                [
                    'id' => 'spacebar-test',
                    'category' => 'keyboard',
                    'icon' => 'spacebar',
                    'name' => 'Spacebar Speed Test',
                    'description' => 'Count how many spacebar presses you can make in 5, 10, or 30 seconds',
                    'cta' => 'Test your spacebar',
                    'routes' => ['en' => 'spacebar-test.php', 'localized' => 'spacebar-test.php'],
                ],
                [
                    'id' => 'mouse-test',
                    'category' => 'mouse',
                    'icon' => 'mouse',
                    'name' => 'Mouse Tester',
                    'description' => 'Check mouse buttons, scroll wheel, cursor movement, and responsiveness',
                    'cta' => 'Test your mouse',
                    'routes' => ['en' => 'mouse-test.php', 'localized' => 'mouse-test.php'],
                ],
                [
                    'id' => 'click-speed',
                    'category' => 'mouse',
                    'icon' => 'lightning',
                    'name' => 'Mouse Speed Tester',
                    'description' => 'Measure your click speed (CPM or CPS) with timed tests',
                    'cta' => 'Check click speed',
                    'routes' => ['en' => 'mouse_speed_tester.php', 'localized' => 'click-speed.php'],
                ],
                [
                    'id' => 'dpi-tester',
                    'category' => 'mouse',
                    'icon' => 'target',
                    'name' => 'Mouse Sensitivity / DPI',
                    'description' => 'Test DPI, sensitivity, and tracking accuracy',
                    'cta' => 'Test DPI settings',
                    'routes' => ['en' => 'mouse_sensitivity_DPI_tester.php', 'localized' => 'dpi-tester.php'],
                ],
                [
                    'id' => 'mouse-trail',
                    'category' => 'mouse',
                    'icon' => 'trail',
                    'name' => 'Mouse Trail',
                    'description' => 'Visualize mouse movement trails and precision',
                    'cta' => 'View mouse trails',
                    'routes' => ['en' => 'mouse-trail.php', 'localized' => 'mouse-trail.php'],
                ],
                [
                    'id' => 'ghost-click',
                    'category' => 'mouse',
                    'icon' => 'ghost',
                    'name' => 'Ghost Click Detector',
                    'description' => 'Detect unintended or phantom clicks',
                    'cta' => 'Detect ghost clicks',
                    'routes' => ['en' => 'ghost-click-detector.php', 'localized' => 'ghost-click.php'],
                ],
                [
                    'id' => 'polling-rate-test',
                    'category' => 'mouse',
                    'icon' => 'polling',
                    'name' => 'Mouse Polling Rate Test',
                    'description' => 'Check if your gaming mouse runs at 125Hz, 500Hz, 1000Hz or higher',
                    'cta' => 'Test polling rate',
                    'routes' => ['en' => 'polling-rate-test.php', 'localized' => 'polling-rate-test.php'],
                ],
                [
                    'id' => 'screen-test',
                    'category' => 'display',
                    'icon' => 'screen',
                    'name' => 'Screen Tester',
                    'description' => 'Detect dead, stuck, or hot pixels on screens',
                    'cta' => 'Test your screen',
                    'routes' => ['en' => 'screentestindex.php', 'localized' => 'screen-test.php'],
                ],
                [
                    'id' => 'refresh-rate-test',
                    'category' => 'display',
                    'icon' => 'refresh',
                    'name' => 'Monitor Refresh Rate Test',
                    'description' => 'Detect if your display runs at 60Hz, 144Hz, 240Hz or higher',
                    'cta' => 'Test refresh rate',
                    'routes' => ['en' => 'refresh-rate-test.php', 'localized' => 'refresh-rate-test.php'],
                ],
                [
                    'id' => 'color-test',
                    'category' => 'display',
                    'icon' => 'palette',
                    'name' => 'Monitor Color Test',
                    'description' => 'Check color accuracy, gradient banding and backlight uniformity',
                    'cta' => 'Test colors',
                    'routes' => ['en' => 'color-test.php', 'localized' => 'color-test.php'],
                ],
                [
                    'id' => 'backlight-bleed-test',
                    'category' => 'display',
                    'icon' => 'bleed',
                    'name' => 'Backlight Bleed Test',
                    'description' => 'Check your LCD monitor for backlight bleed, IPS glow, and clouding',
                    'cta' => 'Test for bleed',
                    'routes' => ['en' => 'backlight-bleed-test.php'],
                    'visible_locales' => ['en'],
                ],
                [
                    'id' => 'touch-screen-test',
                    'category' => 'display',
                    'icon' => 'touch',
                    'name' => 'Touch Screen Test',
                    'description' => 'Test for dead zones, ghost touches and multi-touch on phone or tablet',
                    'cta' => 'Test touch screen',
                    'routes' => ['en' => 'touch-screen-test.php', 'localized' => 'touch-screen-test.php'],
                ],
                [
                    'id' => 'webcam-test',
                    'category' => 'camera',
                    'icon' => 'camera',
                    'name' => 'Webcam Tester',
                    'description' => 'Check webcam quality, resolution, and snapshots',
                    'cta' => 'Test your webcam',
                    'routes' => ['en' => 'webcamtesterindex.php', 'localized' => 'webcam-test.php'],
                ],
                [
                    'id' => 'mic-test',
                    'category' => 'audio',
                    'icon' => 'mic',
                    'name' => 'Mic Tester',
                    'description' => 'Verify microphone input and audio levels',
                    'cta' => 'Test your microphone',
                    'routes' => ['en' => 'mic-tester.php', 'localized' => 'mic-test.php'],
                ],
                [
                    'id' => 'headphone-test',
                    'category' => 'audio',
                    'icon' => 'headphones',
                    'name' => 'Headphone / Speaker Tester',
                    'description' => 'Test stereo channels and sound output',
                    'cta' => 'Test audio output',
                    'routes' => ['en' => 'headphone_speaker_tester_index.php', 'localized' => 'headphone-test.php'],
                ],
                [
                    'id' => 'ocr-tool',
                    'category' => 'utility',
                    'icon' => 'ocr',
                    'name' => 'OCR Tool',
                    'description' => 'Extract text from images quickly',
                    'cta' => 'Extract text now',
                    'routes' => ['en' => 'ocr-tool.php', 'localized' => 'ocr-tool.php'],
                ],
                [
                    'id' => 'qr-reader',
                    'category' => 'utility',
                    'icon' => 'qr-reader',
                    'name' => 'QR Code Reader',
                    'description' => 'Scan QR codes with camera or image upload',
                    'cta' => 'Scan QR codes',
                    'routes' => ['en' => 'qr-code-reader.php', 'localized' => 'qr-reader.php'],
                ],
                [
                    'id' => 'qr-generator',
                    'category' => 'utility',
                    'icon' => 'qr-generator',
                    'name' => 'QR Code Generator',
                    'description' => 'Create custom QR codes instantly',
                    'cta' => 'Create QR code',
                    'routes' => ['en' => 'QR_code_generator_scanner.php', 'localized' => 'qr-generator.php'],
                ],
                [
                    'id' => 'password-generator',
                    'category' => 'utility',
                    'icon' => 'lock',
                    'name' => 'Password Generator',
                    'description' => 'Create strong, secure passwords instantly',
                    'cta' => 'Generate password',
                    'routes' => ['en' => 'auto-password-generator.php', 'localized' => 'password-generator.php'],
                ],
                [
                    'id' => 'whatsapp-link',
                    'category' => 'utility',
                    'icon' => 'whatsapp-link',
                    'name' => 'WhatsApp Link Generator',
                    'description' => 'Create clickable WhatsApp chat links',
                    'cta' => 'Generate chat link',
                    'routes' => ['en' => 'whatsapp-link-generator.php'],
                    'visible_locales' => ['en'],
                ],
                [
                    'id' => 'whatsapp-brand-links',
                    'category' => 'utility',
                    'icon' => 'tag',
                    'name' => 'WhatsApp Brand Links',
                    'description' => 'Create branded WhatsApp links and QR codes',
                    'cta' => 'Create brand link',
                    'routes' => ['en' => 'whatsapp-Brand-link-generator.php'],
                    'visible_locales' => ['en'],
                ],
                [
                    'id' => 'whatsapp-sentiment',
                    'category' => 'utility',
                    'icon' => 'sentiment',
                    'name' => 'WhatsApp Sentiment Analyzer',
                    'description' => 'Analyze chat sentiment and tone',
                    'cta' => 'Analyze sentiment',
                    'routes' => ['en' => 'whatsapp-sentiment-analyzer.php'],
                    'visible_locales' => ['en'],
                ],
                [
                    'id' => 'gamepad-test',
                    'category' => 'gaming',
                    'icon' => 'gamepad',
                    'name' => 'Gamepad Tester',
                    'description' => 'Test PS5, Xbox, Switch and PC controller buttons, stick drift and triggers',
                    'cta' => 'Test controller',
                    'routes' => ['en' => 'gamepad-test.php', 'localized' => 'gamepad-test.php'],
                ],
                [
                    'id' => 'reaction-time-test',
                    'category' => 'gaming',
                    'icon' => 'reaction',
                    'name' => 'Reaction Time Test',
                    'description' => 'Measure how fast you react with a browser-based millisecond reflex test',
                    'cta' => 'Test reaction time',
                    'routes' => ['en' => 'reaction-time-test.php', 'localized' => 'reaction-time-test.php'],
                ],
            ],
            'locales' => [
                'en' => [
                    'directory' => '',
                    'dir' => 'ltr',
                    'title' => 'More testing tools',
                    'subtitle' => 'Explore the full suite for keyboard, mouse, audio, and utilities.',
                    'note' => 'Language support: All major tools are available in 8 languages - Arabic, Russian, Spanish, French, Portuguese, Japanese, German, and Korean. Select your language from the header menu to switch.',
                    'all_label' => 'All',
                    'default_cta' => 'Open tool',
                    'empty_message' => 'No tools match that category yet.',
                    'category_labels' => [
                        'keyboard' => 'Keyboard',
                        'mouse' => 'Mouse',
                        'display' => 'Display',
                        'camera' => 'Camera',
                        'audio' => 'Audio',
                        'utility' => 'Utility',
                        'gaming' => 'Gaming',
                    ],
                    'tools' => [],
                ],
                'ar' => [
                    'directory' => 'arabic',
                    'dir' => 'rtl',
                    'title' => 'المزيد من أدوات الاختبار',
                    'subtitle' => 'استكشف مجموعة كاملة لاختبار لوحة المفاتيح والماوس والصوت والأدوات المساعدة.',
                    'note' => 'جميع الأدوات المعروضة هنا متاحة بواجهة عربية كاملة.',
                    'all_label' => 'الكل',
                    'default_cta' => 'افتح الأداة',
                    'empty_message' => 'لا توجد أدوات في هذا التصنيف حاليًا.',
                    'category_labels' => [
                        'keyboard' => 'لوحة المفاتيح',
                        'mouse' => 'الماوس',
                        'display' => 'الشاشة',
                        'camera' => 'الكاميرا',
                        'audio' => 'الصوت',
                        'utility' => 'الأدوات',
                        'gaming' => 'الألعاب',
                    ],
                    'tools' => [
                        'keyboard-home' => ['name' => 'اختبار لوحة المفاتيح', 'description' => 'اختبر وظائف لوحة المفاتيح، اكتشف الأشباح، قس زمن الاستجابة'],
                        'mouse-test' => ['name' => 'اختبار الماوس', 'description' => 'تحقق من أزرار الماوس وعجلة التمرير وحركة المؤشر والاستجابة'],
                        'click-speed' => ['name' => 'اختبار سرعة النقر', 'description' => 'قِس سرعة النقر (نقرات في الدقيقة أو الثانية) عبر اختبارات مؤقتة'],
                        'dpi-tester' => ['name' => 'حساسية الماوس / DPI', 'description' => 'اختبر DPI والحساسية ودقة التتبع'],
                        'mouse-trail' => ['name' => 'مسار الماوس', 'description' => 'تصور مسارات حركة الماوس والدقة'],
                        'ghost-click' => ['name' => 'كاشف النقرات الوهمية', 'description' => 'اكتشف النقرات غير المقصودة أو الوهمية'],
                        'typing-test' => ['name' => 'اختبار سرعة الكتابة', 'description' => 'قِس عدد الكلمات في الدقيقة والدقة واتساق الكتابة'],
                        'latency-checker' => ['name' => 'فاحص زمن الاستجابة', 'description' => 'اختبر زمن استجابة الجهاز والإدخال في متصفحك'],
                        'screen-test' => ['name' => 'اختبار الشاشة', 'description' => 'اكتشف البكسلات الميتة أو العالقة أو الساخنة على الشاشات'],
                        'webcam-test' => ['name' => 'اختبار كاميرا الويب', 'description' => 'تحقق من جودة كاميرا الويب والدقة واللقطات'],
                        'mic-test' => ['name' => 'اختبار الميكروفون', 'description' => 'تحقق من إدخال الميكروفون ومستويات الصوت'],
                        'headphone-test' => ['name' => 'اختبار السماعات / مكبر الصوت', 'description' => 'اختبر قنوات الاستيريو وإخراج الصوت'],
                        'ocr-tool' => ['name' => 'أداة OCR', 'description' => 'استخرج النص من الصور بسرعة'],
                        'qr-reader' => ['name' => 'قارئ رمز QR', 'description' => 'امسح رموز QR بالكاميرا أو برفع صورة'],
                        'qr-generator' => ['name' => 'مولد رمز QR', 'description' => 'أنشئ رموز QR مخصصة فورًا'],
                        'password-generator' => ['name' => 'مولد كلمات المرور', 'description' => 'أنشئ كلمات مرور قوية وآمنة فورًا'],
                        'spacebar-test' => ['name' => 'اختبار مسطرة المسافة', 'description' => 'احسب الضغطات في 5 أو 10 أو 30 ثانية'],
                        'reaction-time-test' => ['name' => 'اختبار وقت الاستجابة', 'description' => 'قِس ردود أفعالك بالميلي ثانية'],
                        'polling-rate-test' => ['name' => 'اختبار معدل استطلاع الماوس', 'description' => 'قِس معدل Hz للماوس في الوقت الفعلي'],
                        'refresh-rate-test' => ['name' => 'اختبار معدل تحديث الشاشة', 'description' => 'اكتشف تردد تحديث شاشتك'],
                        'touch-screen-test' => ['name' => 'اختبار الشاشة اللمسية', 'description' => 'تحقق من المناطق الميتة واللمس الوهمي'],
                        'gamepad-test' => ['name' => 'اختبار وحدة التحكم', 'description' => 'اختبر الأزرار والعصا والاهتزاز'],
                        'color-test' => ['name' => 'اختبار ألوان الشاشة', 'description' => 'تحقق من الألوان والتدرجات والبكسل الميت'],
                    ],
                ],
                'fr' => [
                    'directory' => 'french',
                    'dir' => 'ltr',
                    'title' => 'Plus d\'outils de test',
                    'subtitle' => 'Explorez la suite complète pour clavier, souris, audio et utilitaires.',
                    'note' => 'Tous les outils affichés ici sont disponibles avec une interface en français.',
                    'all_label' => 'Tous',
                    'default_cta' => 'Ouvrir l\'outil',
                    'empty_message' => 'Aucun outil ne correspond à cette catégorie pour le moment.',
                    'category_labels' => [
                        'keyboard' => 'Clavier',
                        'mouse' => 'Souris',
                        'display' => 'Écran',
                        'camera' => 'Caméra',
                        'audio' => 'Audio',
                        'utility' => 'Utilitaires',
                        'gaming' => 'Jeux',
                    ],
                    'tools' => [
                        'keyboard-home' => ['name' => 'Testeur de clavier', 'description' => 'Testez le clavier, détectez le ghosting, mesurez la latence, vérifiez les touches bloquées'],
                        'mouse-test' => ['name' => 'Testeur de souris', 'description' => 'Vérifiez les boutons, la molette, le mouvement du curseur et la réactivité'],
                        'click-speed' => ['name' => 'Test de vitesse de clic', 'description' => 'Mesurez votre vitesse de clic (CPM ou CPS) avec des tests chronométrés'],
                        'dpi-tester' => ['name' => 'Sensibilité souris / DPI', 'description' => 'Testez le DPI, la sensibilité et la précision du suivi'],
                        'mouse-trail' => ['name' => 'Trace de souris', 'description' => 'Visualisez les trajectoires de la souris et la précision'],
                        'ghost-click' => ['name' => 'Détecteur de clics fantômes', 'description' => 'Détectez les clics involontaires ou fantômes'],
                        'typing-test' => ['name' => 'Test de vitesse de frappe', 'description' => 'Mesurez les mots par minute, la précision et la régularité de la frappe'],
                        'latency-checker' => ['name' => 'Test de latence', 'description' => 'Testez la latence de l\'appareil et des entrées dans votre navigateur'],
                        'screen-test' => ['name' => 'Testeur d\'écran', 'description' => 'Détectez les pixels morts, bloqués ou chauds'],
                        'webcam-test' => ['name' => 'Testeur de webcam', 'description' => 'Vérifiez la qualité, la résolution et les instantanés de la webcam'],
                        'mic-test' => ['name' => 'Testeur de micro', 'description' => 'Vérifiez l\'entrée du micro et les niveaux audio'],
                        'headphone-test' => ['name' => 'Testeur de casque / haut-parleur', 'description' => 'Testez les canaux stéréo et la sortie audio'],
                        'ocr-tool' => ['name' => 'Outil OCR', 'description' => 'Extrayez du texte d\'images rapidement'],
                        'qr-reader' => ['name' => 'Lecteur de QR Code', 'description' => 'Scannez des QR codes avec la caméra ou un fichier image'],
                        'qr-generator' => ['name' => 'Générateur de QR Code', 'description' => 'Créez des QR codes personnalisés instantanément'],
                        'password-generator' => ['name' => 'Générateur de mots de passe', 'description' => 'Créez des mots de passe forts et sécurisés instantanément'],
                        'spacebar-test' => ['name' => 'Test de Barre d\'Espace', 'description' => 'Comptez vos appuis en 5, 10 ou 30 secondes'],
                        'reaction-time-test' => ['name' => 'Test de Temps de Reaction', 'description' => 'Mesurez vos reflexes en millisecondes'],
                        'polling-rate-test' => ['name' => 'Test de Taux d\'Interrogation Souris', 'description' => 'Mesurez le taux Hz de votre souris'],
                        'refresh-rate-test' => ['name' => 'Test de Frequence de Rafraichissement', 'description' => 'Detectez la frequence de votre moniteur'],
                        'touch-screen-test' => ['name' => 'Test d\'Ecran Tactile', 'description' => 'Verifiez les zones mortes et faux contacts'],
                        'gamepad-test' => ['name' => 'Test de Manette de Jeu', 'description' => 'Testez les boutons, sticks et vibrations'],
                        'color-test' => ['name' => 'Test de Couleur du Moniteur', 'description' => 'Verifiez les couleurs et pixels defectueux'],
                    ],
                ],
                'de' => [
                    'directory' => 'german',
                    'dir' => 'ltr',
                    'title' => 'Weitere Test-Tools',
                    'subtitle' => 'Entdecken Sie die komplette Suite für Tastatur, Maus, Audio und Tools.',
                    'note' => 'Alle hier angezeigten Tools sind mit deutscher Oberfläche verfügbar.',
                    'all_label' => 'Alle',
                    'default_cta' => 'Tool oeffnen',
                    'empty_message' => 'Keine Tools passen aktuell zu dieser Kategorie.',
                    'category_labels' => [
                        'keyboard' => 'Tastatur',
                        'mouse' => 'Maus',
                        'display' => 'Bildschirm',
                        'camera' => 'Kamera',
                        'audio' => 'Audio',
                        'utility' => 'Tools',
                        'gaming' => 'Gaming',
                    ],
                    'tools' => [
                        'keyboard-home' => ['name' => 'Tastatur-Tester', 'description' => 'Teste die Tastatur, erkenne Ghosting, miss Latenz und pruefe klemmende Tasten'],
                        'mouse-test' => ['name' => 'Maus-Tester', 'description' => 'Pruefe Maustasten, Scrollrad, Mausbewegung und Reaktionszeit'],
                        'click-speed' => ['name' => 'Klickgeschwindigkeitstest', 'description' => 'Miss deine Klickgeschwindigkeit (KPM oder KPS) mit Zeittests'],
                        'dpi-tester' => ['name' => 'Mausempfindlichkeit / DPI', 'description' => 'Teste DPI, Empfindlichkeit und Tracking-Genauigkeit'],
                        'mouse-trail' => ['name' => 'Mausspur', 'description' => 'Visualisiere Mausbewegungen und Praezision'],
                        'ghost-click' => ['name' => 'Geisterklick-Detektor', 'description' => 'Erkenne unbeabsichtigte oder phantomhafte Klicks'],
                        'typing-test' => ['name' => 'Tippgeschwindigkeitstest', 'description' => 'Miss WPM, Genauigkeit und Tipp-Konsistenz'],
                        'latency-checker' => ['name' => 'Latenz-Checker', 'description' => 'Teste Geraete- und Eingabelatenz im Browser'],
                        'screen-test' => ['name' => 'Bildschirm-Tester', 'description' => 'Erkenne tote, festhaengende oder heisse Pixel'],
                        'webcam-test' => ['name' => 'Webcam-Tester', 'description' => 'Pruefe Webcam-Qualitaet, Aufloesung und Schnappschuesse'],
                        'mic-test' => ['name' => 'Mikrofon-Tester', 'description' => 'Ueberpruefe Mikrofoneingang und Audiopegel'],
                        'headphone-test' => ['name' => 'Kopfhoerer-/Lautsprecher-Tester', 'description' => 'Teste Stereo-Kanaele und Audioausgabe'],
                        'ocr-tool' => ['name' => 'OCR-Tool', 'description' => 'Extrahiere Text aus Bildern schnell'],
                        'qr-reader' => ['name' => 'QR-Code-Scanner', 'description' => 'Scanne QR-Codes per Kamera oder Bildupload'],
                        'qr-generator' => ['name' => 'QR-Code-Generator', 'description' => 'Erstelle benutzerdefinierte QR-Codes sofort'],
                        'password-generator' => ['name' => 'Passwortgenerator', 'description' => 'Erstelle starke, sichere Passwoerter sofort'],
                        'spacebar-test' => ['name' => 'Leertasten-Test', 'description' => 'Zaehle Anschlaege in 5, 10 oder 30 Sekunden'],
                        'reaction-time-test' => ['name' => 'Reaktionszeit-Test', 'description' => 'Miss deine Reflexe in Millisekunden'],
                        'polling-rate-test' => ['name' => 'Maus-Abfragerate-Test', 'description' => 'Miss die Hz-Rate deiner Maus in Echtzeit'],
                        'refresh-rate-test' => ['name' => 'Monitor-Bildwiederholrate-Test', 'description' => 'Erkenne die Bildwiederholrate deines Monitors'],
                        'touch-screen-test' => ['name' => 'Touchscreen-Test', 'description' => 'Pruefe tote Zonen und Geisterberuehrungen'],
                        'gamepad-test' => ['name' => 'Gamepad-Test', 'description' => 'Teste Tasten, Sticks und Vibration'],
                        'color-test' => ['name' => 'Monitor-Farbtest', 'description' => 'Pruefe Farben, Verlaeufe und tote Pixel'],
                    ],
                ],
            'es' => [
                'directory' => 'spanish',
                'dir' => 'ltr',
                'title' => 'Más herramientas de prueba',
                'subtitle' => 'Explora la suite completa para teclado, ratón, audio y utilidades.',
                'note' => 'Todas las herramientas disponibles con interfaz en español.',
                'all_label' => 'Todos',
                'default_cta' => 'Abrir herramienta',
                'empty_message' => 'No hay herramientas en esta categoría por ahora.',
                'category_labels' => [
                    'keyboard' => 'Teclado',
                    'mouse' => 'Ratón',
                    'display' => 'Pantalla',
                    'camera' => 'Cámara',
                    'audio' => 'Audio',
                    'utility' => 'Utilidades',
                    'gaming' => 'Juegos',
                ],
                'tools' => [
                    'keyboard-home' => ['name' => 'Probador de Teclado', 'description' => 'Prueba el teclado, detecta ghosting, mide la latencia'],
                    'mouse-test' => ['name' => 'Probador de Ratón', 'description' => 'Comprueba botones, rueda de desplazamiento y movimiento'],
                    'click-speed' => ['name' => 'Velocidad de Clic', 'description' => 'Mide la velocidad de clic (CPS) con pruebas cronometradas'],
                    'dpi-tester' => ['name' => 'Sensibilidad / DPI', 'description' => 'Prueba DPI, sensibilidad y precisión de seguimiento'],
                    'mouse-trail' => ['name' => 'Rastro del Ratón', 'description' => 'Visualiza trayectorias del ratón y precisión'],
                    'ghost-click' => ['name' => 'Detector de Clics Fantasma', 'description' => 'Detecta clics no intencionados o fantasma'],
                    'polling-rate-test' => ['name' => 'Test de Tasa de Sondeo del Ratón', 'description' => 'Mide la tasa Hz de tu ratón en tiempo real'],
                    'typing-test' => ['name' => 'Velocidad de Escritura', 'description' => 'Mide WPM, precisión y consistencia al escribir'],
                    'latency-checker' => ['name' => 'Verificador de Latencia', 'description' => 'Prueba la latencia y tiempo de reacción'],
                    'spacebar-test' => ['name' => 'Prueba de Barra Espaciadora', 'description' => 'Cuenta tus pulsaciones en 5, 10 o 30 segundos'],
                    'screen-test' => ['name' => 'Prueba de Pantalla', 'description' => 'Detecta píxeles muertos, atascados o calientes'],
                    'refresh-rate-test' => ['name' => 'Test de Tasa de Refresco', 'description' => 'Detecta la frecuencia de actualización del monitor'],
                    'color-test' => ['name' => 'Test de Color del Monitor', 'description' => 'Verifica colores, gradientes y píxeles muertos'],
                    'touch-screen-test' => ['name' => 'Test de Pantalla Táctil', 'description' => 'Verifica zonas muertas y toque fantasma'],
                    'webcam-test' => ['name' => 'Prueba de Webcam', 'description' => 'Comprueba calidad, resolución y capturas'],
                    'mic-test' => ['name' => 'Prueba de Micrófono', 'description' => 'Comprueba la entrada del micrófono y niveles de audio'],
                    'headphone-test' => ['name' => 'Prueba de Auriculares', 'description' => 'Prueba canales estéreo y salida de audio'],
                    'ocr-tool' => ['name' => 'Herramienta OCR', 'description' => 'Extrae texto de imágenes rápidamente'],
                    'qr-reader' => ['name' => 'Lector de Códigos QR', 'description' => 'Escanea códigos QR con la cámara o imagen'],
                    'qr-generator' => ['name' => 'Generador de QR', 'description' => 'Crea códigos QR personalizados al instante'],
                    'password-generator' => ['name' => 'Generador de Contraseñas', 'description' => 'Crea contraseñas fuertes y seguras al instante'],
                    'gamepad-test' => ['name' => 'Test de Mando de Juego', 'description' => 'Prueba botones, sticks y vibración del mando'],
                    'reaction-time-test' => ['name' => 'Test de Tiempo de Reacción', 'description' => 'Mide tus reflejos en milisegundos'],
                ],
            ],
            'pt' => [
                'directory' => 'portuguese',
                'dir' => 'ltr',
                'title' => 'Mais ferramentas de teste',
                'subtitle' => 'Explore o conjunto completo para teclado, mouse, áudio e utilitários.',
                'note' => 'Todas as ferramentas disponíveis com interface em português.',
                'all_label' => 'Todos',
                'default_cta' => 'Abrir ferramenta',
                'empty_message' => 'Nenhuma ferramenta nesta categoria por enquanto.',
                'category_labels' => [
                    'keyboard' => 'Teclado',
                    'mouse' => 'Mouse',
                    'display' => 'Tela',
                    'camera' => 'Câmera',
                    'audio' => 'Áudio',
                    'utility' => 'Utilitários',
                    'gaming' => 'Jogos',
                ],
                'tools' => [
                    'keyboard-home' => ['name' => 'Testador de teclado', 'description' => 'Teste o teclado, detecte ghosting, meça a latência e verifique teclas presas'],
                    'mouse-test' => ['name' => 'Testador de mouse', 'description' => 'Verifique botões, roda de rolagem, movimento do cursor e responsividade'],
                    'click-speed' => ['name' => 'Teste de velocidade de clique', 'description' => 'Meça sua velocidade de clique (CPM ou CPS) com testes cronometrados'],
                    'dpi-tester' => ['name' => 'Sensibilidade do mouse / DPI', 'description' => 'Teste DPI, sensibilidade e precisão do rastreamento'],
                    'mouse-trail' => ['name' => 'Rastro do mouse', 'description' => 'Visualize trajetórias do mouse e precisão'],
                    'ghost-click' => ['name' => 'Detector de cliques fantasma', 'description' => 'Detecte cliques não intencionais ou fantasma'],
                    'polling-rate-test' => ['name' => 'Teste de Taxa de Polling do Mouse', 'description' => 'Meça a taxa Hz do seu mouse em tempo real'],
                    'typing-test' => ['name' => 'Teste de velocidade de digitação', 'description' => 'Meça WPM, precisão e consistência da digitação'],
                    'latency-checker' => ['name' => 'Verificador de latência', 'description' => 'Teste a latência do dispositivo e da entrada no navegador'],
                    'spacebar-test' => ['name' => 'Teste da Barra de Espaço', 'description' => 'Conte os toques em 5, 10 ou 30 segundos'],
                    'screen-test' => ['name' => 'Teste de tela', 'description' => 'Detecte pixels mortos, travados ou quentes'],
                    'refresh-rate-test' => ['name' => 'Teste de Taxa de Atualização', 'description' => 'Detecte a frequência de atualização do monitor'],
                    'color-test' => ['name' => 'Teste de Cor do Monitor', 'description' => 'Verifique cores, gradientes e pixels mortos'],
                    'touch-screen-test' => ['name' => 'Teste de Tela Sensível ao Toque', 'description' => 'Verifique zonas mortas e toques fantasma'],
                    'webcam-test' => ['name' => 'Teste de webcam', 'description' => 'Verifique qualidade, resolução e capturas da webcam'],
                    'mic-test' => ['name' => 'Teste de microfone', 'description' => 'Verifique a entrada do microfone e níveis de áudio'],
                    'headphone-test' => ['name' => 'Teste de fones / alto-falante', 'description' => 'Teste canais estéreo e saída de áudio'],
                    'ocr-tool' => ['name' => 'Ferramenta OCR', 'description' => 'Extraia texto de imagens rapidamente'],
                    'qr-reader' => ['name' => 'Leitor de QR Code', 'description' => 'Leia QR codes com câmera ou upload de imagem'],
                    'qr-generator' => ['name' => 'Gerador de QR Code', 'description' => 'Crie QR codes personalizados instantaneamente'],
                    'password-generator' => ['name' => 'Gerador de senhas', 'description' => 'Crie senhas fortes e seguras instantaneamente'],
                    'gamepad-test' => ['name' => 'Teste de Gamepad', 'description' => 'Teste botões, analógicos e vibração'],
                    'reaction-time-test' => ['name' => 'Teste de Tempo de Reação', 'description' => 'Meça seus reflexos em milissegundos'],
                ],
            ],
            'ru' => [
                'directory' => 'russian',
                'dir' => 'ltr',
                'title' => 'Больше инструментов тестирования',
                'subtitle' => 'Полный набор инструментов для клавиатуры, мыши, аудио и утилит.',
                'note' => 'Все инструменты доступны с интерфейсом на русском языке.',
                'all_label' => 'Все',
                'default_cta' => 'Открыть инструмент',
                'empty_message' => 'В этой категории пока нет инструментов.',
                'category_labels' => [
                    'keyboard' => 'Клавиатура',
                    'mouse' => 'Мышь',
                    'display' => 'Экран',
                    'camera' => 'Камера',
                    'audio' => 'Аудио',
                    'utility' => 'Утилиты',
                    'gaming' => 'Игры',
                ],
                'tools' => [
                    'keyboard-home' => ['name' => 'Тестер Клавиатуры', 'description' => 'Проверьте клавиатуру, обнаружьте ghosting, измерьте задержку'],
                    'mouse-test' => ['name' => 'Тестер Мыши', 'description' => 'Проверьте кнопки, колесо прокрутки и движение'],
                    'click-speed' => ['name' => 'Скорость Клика', 'description' => 'Измерьте скорость клика (CPS) с таймером'],
                    'dpi-tester' => ['name' => 'Чувствительность / DPI', 'description' => 'Проверьте DPI, чувствительность и точность'],
                    'mouse-trail' => ['name' => 'След Мыши', 'description' => 'Визуализируйте траектории мыши и точность'],
                    'ghost-click' => ['name' => 'Детектор Призрачных Кликов', 'description' => 'Обнаружьте непреднамеренные или призрачные клики'],
                    'polling-rate-test' => ['name' => 'Тест частоты опроса мыши', 'description' => 'Измерьте частоту опроса мыши в Гц'],
                    'typing-test' => ['name' => 'Скорость Печати', 'description' => 'Измерьте WPM, точность и стабильность'],
                    'latency-checker' => ['name' => 'Проверка Задержки', 'description' => 'Проверьте задержку и время реакции'],
                    'spacebar-test' => ['name' => 'Тест пробела', 'description' => 'Считайте нажатия за 5, 10 или 30 секунд'],
                    'screen-test' => ['name' => 'Тест Экрана', 'description' => 'Обнаружьте битые, застрявшие или горячие пиксели'],
                    'refresh-rate-test' => ['name' => 'Тест частоты обновления монитора', 'description' => 'Определите частоту обновления монитора'],
                    'color-test' => ['name' => 'Тест цветов монитора', 'description' => 'Проверьте цвета, градиенты и мёртвые пиксели'],
                    'touch-screen-test' => ['name' => 'Тест сенсорного экрана', 'description' => 'Проверьте мёртвые зоны и ложные касания'],
                    'webcam-test' => ['name' => 'Тест Веб-камеры', 'description' => 'Проверьте качество, разрешение и снимки'],
                    'mic-test' => ['name' => 'Тест Микрофона', 'description' => 'Проверьте вход микрофона и уровни звука'],
                    'headphone-test' => ['name' => 'Тест Наушников', 'description' => 'Проверьте стереоканалы и вывод звука'],
                    'ocr-tool' => ['name' => 'OCR Инструмент', 'description' => 'Быстро извлеките текст из изображений'],
                    'qr-reader' => ['name' => 'Сканер QR-кода', 'description' => 'Сканируйте QR-коды камерой или изображением'],
                    'qr-generator' => ['name' => 'Генератор QR-кода', 'description' => 'Создайте пользовательские QR-коды мгновенно'],
                    'password-generator' => ['name' => 'Генератор Паролей', 'description' => 'Создайте надёжные и безопасные пароли мгновенно'],
                    'gamepad-test' => ['name' => 'Тест геймпада', 'description' => 'Протестируйте кнопки, стики и вибрацию'],
                    'reaction-time-test' => ['name' => 'Тест времени реакции', 'description' => 'Измерьте рефлексы в миллисекундах'],
                ],
            ],
            'ja' => [
                'directory' => 'japanese',
                'dir' => 'ltr',
                'title' => 'その他のテストツール',
                'subtitle' => 'キーボード、マウス、オーディオ、ユーティリティの完全なツールスイートをご覧ください。',
                'note' => 'すべてのツールは日本語インターフェースで利用可能です。',
                'all_label' => 'すべて',
                'default_cta' => 'ツールを開く',
                'empty_message' => 'このカテゴリにはまだツールがありません。',
                'category_labels' => [
                    'keyboard' => 'キーボード',
                    'mouse' => 'マウス',
                    'display' => 'ディスプレイ',
                    'camera' => 'カメラ',
                    'audio' => 'オーディオ',
                    'utility' => 'ユーティリティ',
                    'gaming' => 'ゲーミング',
                ],
                'tools' => [
                    'keyboard-home' => ['name' => 'キーボードテスター', 'description' => 'キーボードテスト、ゴースト検出、レイテンシー測定'],
                    'mouse-test' => ['name' => 'マウステスター', 'description' => 'ボタン、スクロールホイール、動作をチェック'],
                    'click-speed' => ['name' => 'クリック速度テスト', 'description' => 'タイマー付きテストでクリック速度（CPS）を測定'],
                    'dpi-tester' => ['name' => '感度 / DPIテスト', 'description' => 'DPI、感度、トラッキング精度をテスト'],
                    'mouse-trail' => ['name' => 'マウストレイル', 'description' => 'マウスの軌跡と精度を可視化'],
                    'ghost-click' => ['name' => 'ゴーストクリック検出器', 'description' => '意図しないクリックやゴーストクリックを検出'],
                    'polling-rate-test' => ['name' => 'マウスポーリングレートテスト', 'description' => 'マウスのHz率をリアルタイム計測'],
                    'typing-test' => ['name' => 'タイピング速度テスト', 'description' => 'WPM、精度、タイピングの一貫性を測定'],
                    'latency-checker' => ['name' => 'レイテンシーチェッカー', 'description' => 'レイテンシーと反応時間をテスト'],
                    'spacebar-test' => ['name' => 'スペースバーテスト', 'description' => '5・10・30秒で押した回数を計測'],
                    'screen-test' => ['name' => 'スクリーンテスト', 'description' => 'デッドピクセル、スタックピクセル、ホットピクセルを検出'],
                    'refresh-rate-test' => ['name' => 'モニターリフレッシュレートテスト', 'description' => 'モニターの周波数をrAFで検出'],
                    'color-test' => ['name' => 'モニターカラーテスト', 'description' => '色、グラデーション、不良ピクセルを確認'],
                    'touch-screen-test' => ['name' => 'タッチスクリーンテスト', 'description' => 'デッドゾーンとゴーストタッチを確認'],
                    'webcam-test' => ['name' => 'ウェブカメラテスト', 'description' => '画質、解像度、キャプチャをチェック'],
                    'mic-test' => ['name' => 'マイクテスト', 'description' => 'マイク入力とオーディオレベルをチェック'],
                    'headphone-test' => ['name' => 'ヘッドホンテスト', 'description' => 'ステレオチャンネルとオーディオ出力をテスト'],
                    'ocr-tool' => ['name' => 'OCRツール', 'description' => '画像からテキストを素早く抽出'],
                    'qr-reader' => ['name' => 'QRコードリーダー', 'description' => 'カメラまたは画像からQRコードをスキャン'],
                    'qr-generator' => ['name' => 'QRコード生成器', 'description' => 'カスタムQRコードを即座に作成'],
                    'password-generator' => ['name' => 'パスワード生成器', 'description' => '強力で安全なパスワードを即座に作成'],
                    'gamepad-test' => ['name' => 'ゲームパッドテスト', 'description' => 'ボタン・スティック・振動をテスト'],
                    'reaction-time-test' => ['name' => '反応時間テスト', 'description' => 'ミリ秒単位で反射神経を測定'],
                ],
            ],
            'ko' => [
                'directory' => 'korean',
                'dir' => 'ltr',
                'title' => '더 많은 테스트 도구',
                'subtitle' => '키보드, 마우스, 오디오, 유틸리티 전체 도구를 확인하세요.',
                'note' => '모든 도구가 한국어 인터페이스로 제공됩니다.',
                'all_label' => '전체',
                'default_cta' => '도구 열기',
                'empty_message' => '이 카테고리에는 아직 도구가 없습니다.',
                'category_labels' => [
                    'keyboard' => '키보드',
                    'mouse' => '마우스',
                    'display' => '디스플레이',
                    'camera' => '카메라',
                    'audio' => '오디오',
                    'utility' => '유틸리티',
                    'gaming' => '게이밍',
                ],
                'tools' => [
                    'keyboard-home' => ['name' => '키보드 테스터', 'description' => '키보드 기능을 테스트하고 고스팅을 감지하며 지연 시간과 눌림 문제를 확인'],
                    'mouse-test' => ['name' => '마우스 테스터', 'description' => '버튼, 스크롤 휠, 커서 이동, 반응성을 확인'],
                    'click-speed' => ['name' => '클릭 속도 테스트', 'description' => '클릭 속도(CPM/CPS)를 시간 제한 테스트로 측정'],
                    'dpi-tester' => ['name' => '마우스 감도 / DPI', 'description' => 'DPI, 감도, 트래킹 정확도 테스트'],
                    'mouse-trail' => ['name' => '마우스 궤적', 'description' => '마우스 이동 경로와 정밀도 시각화'],
                    'ghost-click' => ['name' => '고스트 클릭 감지', 'description' => '의도치 않은 클릭을 감지'],
                    'polling-rate-test' => ['name' => '마우스 폴링 레이트 테스트', 'description' => '마우스의 Hz 속도를 실시간 측정'],
                    'typing-test' => ['name' => '타이핑 속도 테스트', 'description' => 'WPM, 정확도, 타이핑 일관성 측정'],
                    'latency-checker' => ['name' => '지연 시간 검사기', 'description' => '브라우저에서 장치/입력 지연을 테스트'],
                    'spacebar-test' => ['name' => '스페이스바 테스트', 'description' => '5·10·30초 동안 누른 횟수 카운트'],
                    'screen-test' => ['name' => '스크린 테스터', 'description' => '죽은/고정/핫 픽셀 감지'],
                    'refresh-rate-test' => ['name' => '모니터 주사율 테스트', 'description' => '모니터의 주사율을 rAF로 감지'],
                    'color-test' => ['name' => '모니터 색상 테스트', 'description' => '색상, 그라데이션, 불량 화소 확인'],
                    'touch-screen-test' => ['name' => '터치스크린 테스트', 'description' => '데드존 및 고스트 터치 확인'],
                    'webcam-test' => ['name' => '웹캠 테스터', 'description' => '웹캠 품질, 해상도, 스냅샷 확인'],
                    'mic-test' => ['name' => '마이크 테스터', 'description' => '마이크 입력과 오디오 레벨 확인'],
                    'headphone-test' => ['name' => '헤드폰 / 스피커 테스터', 'description' => '스테레오 채널과 음향 출력 테스트'],
                    'ocr-tool' => ['name' => 'OCR 도구', 'description' => '이미지에서 텍스트를 빠르게 추출'],
                    'qr-reader' => ['name' => 'QR 코드 리더', 'description' => '카메라 또는 이미지로 QR 코드 스캔'],
                    'qr-generator' => ['name' => 'QR 코드 생성기', 'description' => '맞춤 QR 코드를 즉시 생성'],
                    'password-generator' => ['name' => '비밀번호 생성기', 'description' => '강력하고 안전한 비밀번호를 즉시 생성'],
                    'gamepad-test' => ['name' => '게임패드 테스트', 'description' => '버튼, 스틱, 진동 테스트'],
                    'reaction-time-test' => ['name' => '반응 시간 테스트', 'description' => '밀리초 단위로 반사 신경 측정'],
                ],
            ],
            ],
        ];
    }
}
