<?php
// Localized labels for aspect-ratio-calculator — auto-generated by generate-locale-wrappers.py
$ar_labels = [
    'aria' => 'アスペクト比計算機 - 幅・高さ・比率を解決',
    'instruction' => '3つのうち2つを編集（幅・高さ・比率）。ツールが3つ目を解決します。比率は \'16:9\' または \'1.7778\' が有効。',
    'preset' => 'プリセット比率',
    'width' => '幅 (px)',
    'height' => '高さ (px)',
    'ratio' => 'アスペクト比',
    'simplified' => '簡約',
    'decimal' => '小数',
    'orientation' => '向き',
    'landscape' => '横向き',
    'portrait' => '縦向き',
    'square' => '正方形',
    'reference' => 'ヒント：幅と高さを入力すると比率が出ます。プリセットを選んで1辺を入力してもOK。',
];
include __DIR__ . '/../../../tools/aspect_calc_tool.php';
