<?php
// Localized labels for burn-in-test — auto-generated by generate-locale-wrappers.py
$bi_labels = [
    'aria' => 'OLED焼き付き・画像保持テスト',
    'instruction' => 'フルスクリーンをクリック。矢印またはボタンで色を送ります。白単色を30-60秒表示すると保持が見えます。Escで終了。',
    'mode' => 'モード',
    'mode_cycle' => '色サイクル (W, K, R, G, B, C, M, Y)',
    'mode_checker' => '細かい市松',
    'mode_scroll' => 'スクロールリフレッシャー',
    'auto' => '自動送り',
    'auto_off' => 'オフ',
    'auto_5' => '5秒ごと',
    'auto_15' => '15秒ごと',
    'auto_60' => '60秒ごと',
    'fullscreen' => 'フルスクリーン',
    'exit_fs' => '終了',
    'next' => '次へ',
    'prev' => '前へ',
    'current_color' => '現在の色',
    'reference' => 'ヒント：リフレッシャーを一晩動かすと軽度の保持は回復します。8時間の白で消えない永久焼き付きは直りません。',
];
include __DIR__ . '/../../../tools/burn_in_tool.php';
