<?php
// Localized labels for edpi-calculator — auto-generated by generate-locale-wrappers.py
$ec_labels = [
    'aria' => 'eDPI計算機 - ゲーム用の有効DPI',
    'instruction' => 'マウスDPIとゲーム内感度を入力。eDPI = DPI × 感度で、ゲーム間のエイムを比較できます。',
    'dpi' => 'マウスDPI',
    'sens' => 'ゲーム内感度',
    'edpi' => '有効DPI (eDPI)',
    'cm_360' => 'cm/360 (推定, yaw 0.022既定)',
    'reference' => 'プロ参考: 800 DPI × 0.5感度 = 400 eDPI',
];
include __DIR__ . '/../../../tools/edpi_calculator_tool.php';
