<?php
// Localized labels for fps-test — auto-generated by generate-locale-wrappers.py
$fps_labels = [
    'aria' => 'FPSテスト - ブラウザのフレームレート計測',
    'instruction' => 'スタートを押してください。このタブが前面である必要があります。バックグラウンドタブは30 FPS以下にスロットルされます。',
    'start' => 'スタート',
    'stop' => '停止',
    'reset' => 'リセット',
    'current' => '現在のFPS',
    'avg' => '平均FPS',
    'min' => '最小FPS',
    'max' => '最大FPS',
    'low1' => '1% low',
    'total_frames' => 'フレーム数',
    'uptime' => '稼働時間',
    'detected_hz' => '推定ディスプレイHz',
    'reference' => 'ヒント：ブラウザFPSはモニターHzを超えません。60 = 60Hz。1% lowはカクつきの底値です。',
];
include __DIR__ . '/../../../tools/fps_test_tool.php';
