<?php
// Localized labels for mouse-spin-test — auto-generated by generate-locale-wrappers.py
$ms_labels = [
    'aria' => 'マウス回転テスト - 360°回転をカウント',
    'instruction' => 'スタートを押し、カーソルをパッドに置き、左ボタンを押したまま中心点の周りを回してください。360°ごとに1回転。',
    'duration' => '時間',
    'dur_15' => '15秒',
    'dur_30' => '30秒',
    'dur_60' => '60秒',
    'start' => 'スタート',
    'stop' => '停止',
    'reset' => 'リセット',
    'pad_hint' => '左ボタンを押したまま中心を回します。',
    'time_left' => '残り時間',
    'spins' => '回転数',
    'peak_sps' => 'ピーク回転/秒',
    'degrees' => '累計回転',
    'direction' => '方向',
    'dir_cw' => '時計回り',
    'dir_ccw' => '反時計回り',
    'dir_idle' => '-',
    'reference' => 'ヒント：高DPIなら少ない動きで多く回せます。時計回り・反時計回り、ゆっくり・素早い振りも試しましょう。',
];
include __DIR__ . '/../../../tools/mouse_spin_tool.php';
