<?php
// Localized labels for resolution-test — auto-generated by generate-locale-wrappers.py
$rt_labels = [
    'aria' => '画面解像度テスト',
    'instruction' => 'すべての値はライブで更新されます。ウィンドウをリサイズしたりズームすると viewport と DPR が変化します。',
    'screen_size' => '画面解像度',
    'native_res' => 'ネイティブ物理解像度',
    'viewport' => 'ビューポート（このタブ）',
    'dpr' => 'デバイスピクセル比（DPR）',
    'color_depth' => '色深度',
    'color_gamut' => '色域',
    'pixel_depth' => 'ピクセル深度',
    'orientation' => '向き',
    'aspect' => 'アスペクト比',
    'avail' => '利用可能な画面',
    'reference' => 'ヒント：DPRはCSSピクセルを物理ピクセルに倍率換算します。Retina・スマホは2-3。ネイティブ = CSS × DPR。',
];
include __DIR__ . '/../../../tools/resolution_test_tool.php';
