<?php
// Localized labels for screen-uniformity-test — auto-generated by generate-locale-wrappers.py
$su_labels = [
    'aria' => '画面ユニフォーミティテスト',
    'instruction' => '色と輝度を選び、フルスクリーンへ。良いパネルは端から端まで均一です。輝度ムラ、色づきのある角、雲状の斑はユニフォーミティ問題を示します。',
    'color' => '色',
    'c_gray' => 'ミッドグレー（クラウディングを検出）',
    'c_black' => 'ブラック近傍（IPSグロー＋バックライト漏れ）',
    'c_white' => '白（輝度低下を検出）',
    'c_red' => '赤',
    'c_green' => '緑',
    'c_blue' => '青',
    'brightness' => '輝度',
    'fullscreen' => 'フルスクリーン',
    'exit_fs' => '終了',
    'reference' => 'ヒント：20・50・80%の輝度でそれぞれテスト - 問題は特定の輝度帯でだけ出ることが多いです。2-3フィート下がり、部屋を暗くしてクラウディングを観察。',
];
include __DIR__ . '/../../../tools/screen_uniformity_tool.php';
