<?php
// Localized labels for viewing-distance-calculator — auto-generated by generate-locale-wrappers.py
$vd_labels = [
    'aria' => '視聴距離計算機',
    'instruction' => '画面対角と解像度を入力。THX最適（36° FoV）、SMPTE映画館（30° FoV）、4Kが1080pと見分けられなくなる最大距離が出ます。',
    'diagonal' => '画面対角',
    'resolution' => 'ネイティブ解像度',
    'unit' => '単位',
    'thx' => 'THX最適（36° FoV）',
    'smpte' => 'SMPTE映画館（30° FoV）',
    'uhd4k' => '4K UHDの最大距離',
    'min_4k' => 'これより遠いと4K = 1080pに見える',
    'angle' => 'THX時の角度',
    'reference' => 'ヒント：THX = 36°（没入）、SMPTE = 30°（映画館コンフォート）。4K最大距離より離れて座るならそのサイズに4Kは無駄です。',
];
include __DIR__ . '/../../../tools/viewing_distance_calc_tool.php';
