"""Rewrites the 96 localized tool-wrappers (languages/{lang}/tools/*.php) so each
one now sets a full translated label-array before including the English tool partial.

This ONLY touches wrappers, not the landing pages. The 12 tools handled:
  edpi-calculator, aspect-ratio-calculator, screen-size-calculator,
  viewing-distance-calculator, fps-test, resolution-test, apm-test, mouse-spin-test,
  burn-in-test, color-range-test, screen-uniformity-test, sound-test.

Run:  python generate-locale-wrappers.py
"""
from __future__ import annotations
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent

LOCALES = {'es':'spanish','fr':'french','de':'german','pt':'portuguese','ar':'arabic','ru':'russian','ja':'japanese','ko':'korean'}

# ---------- Per-tool metadata + per-language label translations ----------
# labels_var must match the $var name the English tool-partial expects.
# wrapper is the filename inside languages/{lang}/tools/.
# partial is the file in /tools/ the wrapper includes.
# trans[lang] is a dict of key -> string, matching the English keys in the partial.

TOOLS = {
    # ----- edpi-calculator ($ec_labels) -----
    'edpi-calculator': {
        'labels_var': 'ec_labels',
        'wrapper': 'edpi-calculator-tool.php',
        'partial': 'edpi_calculator_tool.php',
        'trans': {
            'es': {'aria':'Calculadora de eDPI - DPI efectivo para gaming','instruction':'Introduce el DPI del raton y la sensibilidad del juego. eDPI = DPI x sensibilidad, util para comparar punteria entre juegos.','dpi':'DPI del raton','sens':'Sensibilidad en el juego','edpi':'DPI efectivo (eDPI)','cm_360':'cm/360 (estimado, yaw 0.022 por defecto)','reference':'Referencia pro: 800 DPI x 0.5 sens = 400 eDPI'},
            'fr': {'aria':"Calculateur eDPI - DPI effectif pour le gaming",'instruction':"Entrez le DPI de la souris et la sensibilite en jeu. eDPI = DPI x sensibilite, utile pour comparer la visee entre jeux.",'dpi':"DPI souris",'sens':"Sensibilite en jeu",'edpi':"DPI effectif (eDPI)",'cm_360':"cm/360 (estime, yaw 0.022 par defaut)",'reference':"Reference pro : 800 DPI x 0.5 sens = 400 eDPI"},
            'de': {'aria':"eDPI-Rechner - Effektive DPI fuers Gaming",'instruction':"Gib Maus-DPI und Spiel-Empfindlichkeit ein. eDPI = DPI x Empfindlichkeit zum Vergleich der Zielgenauigkeit zwischen Spielen.",'dpi':"Maus-DPI",'sens':"Empfindlichkeit im Spiel",'edpi':"Effektive DPI (eDPI)",'cm_360':"cm/360 (geschaetzt, Yaw 0.022)",'reference':"Pro-Referenz: 800 DPI x 0.5 Sens = 400 eDPI"},
            'pt': {'aria':"Calculadora de eDPI - DPI efetivo para gaming",'instruction':"Digite DPI do mouse e sensibilidade do jogo. eDPI = DPI x sensibilidade, para comparar mira entre jogos.",'dpi':"DPI do mouse",'sens':"Sensibilidade no jogo",'edpi':"DPI efetivo (eDPI)",'cm_360':"cm/360 (estimado, yaw 0.022 padrao)",'reference':"Referencia pro: 800 DPI x 0.5 sens = 400 eDPI"},
            'ar': {'aria':"حاسبة eDPI - DPI الفعال في الألعاب",'instruction':"أدخل DPI الماوس وحساسية اللعبة. eDPI = DPI × الحساسية، لمقارنة التصويب بين الألعاب.",'dpi':"DPI الماوس",'sens':"حساسية اللعبة",'edpi':"DPI الفعال (eDPI)",'cm_360':"سم/360 (تقديري، yaw 0.022 افتراضي)",'reference':"مرجع احترافي: 800 DPI × 0.5 حساسية = 400 eDPI"},
            'ru': {'aria':"Калькулятор eDPI - эффективный DPI для гейминга",'instruction':"Введите DPI мыши и чувствительность в игре. eDPI = DPI × чувствительность, для сравнения прицеливания между играми.",'dpi':"DPI мыши",'sens':"Чувствительность в игре",'edpi':"Эффективный DPI (eDPI)",'cm_360':"см/360 (оценка, yaw 0.022)",'reference':"Про-референс: 800 DPI × 0.5 = 400 eDPI"},
            'ja': {'aria':"eDPI計算機 - ゲーム用の有効DPI",'instruction':"マウスDPIとゲーム内感度を入力。eDPI = DPI × 感度で、ゲーム間のエイムを比較できます。",'dpi':"マウスDPI",'sens':"ゲーム内感度",'edpi':"有効DPI (eDPI)",'cm_360':"cm/360 (推定, yaw 0.022既定)",'reference':"プロ参考: 800 DPI × 0.5感度 = 400 eDPI"},
            'ko': {'aria':"eDPI 계산기 - 게임용 유효 DPI",'instruction':"마우스 DPI와 게임 내 감도를 입력하세요. eDPI = DPI × 감도로 게임 간 에임을 비교합니다.",'dpi':"마우스 DPI",'sens':"게임 내 감도",'edpi':"유효 DPI (eDPI)",'cm_360':"cm/360 (추정, yaw 0.022 기본)",'reference':"프로 기준: 800 DPI × 0.5 감도 = 400 eDPI"},
        },
    },
    # ----- aspect-ratio-calculator ($ar_labels) -----
    'aspect-ratio-calculator': {
        'labels_var': 'ar_labels',
        'wrapper': 'aspect-ratio-calculator-tool.php',
        'partial': 'aspect_calc_tool.php',
        'trans': {
            'es': {'aria':"Calculadora de relacion de aspecto - resuelve ancho, alto o ratio",'instruction':"Edita dos de tres (ancho, alto o ratio). La herramienta resuelve el tercero. El ratio acepta '16:9' o '1.7778'.",'preset':"Ratio preajustado",'width':"Ancho (px)",'height':"Alto (px)",'ratio':"Relacion de aspecto",'simplified':"Simplificado",'decimal':"Decimal",'orientation':"Orientacion",'landscape':"Horizontal",'portrait':"Vertical",'square':"Cuadrado",'reference':"Consejo: introduce ancho y alto para ver el ratio, o elige un preset y escribe una dimension."},
            'fr': {'aria':"Calculateur de ratio - resout largeur, hauteur ou ratio",'instruction':"Modifiez deux des trois champs (largeur, hauteur ou ratio). L'outil resout le troisieme. Accepte '16:9' ou '1.7778'.",'preset':"Ratio preregle",'width':"Largeur (px)",'height':"Hauteur (px)",'ratio':"Ratio d'aspect",'simplified':"Simplifie",'decimal':"Decimal",'orientation':"Orientation",'landscape':"Paysage",'portrait':"Portrait",'square':"Carre",'reference':"Astuce : entrez largeur + hauteur pour le ratio, ou choisissez un preset et une dimension."},
            'de': {'aria':"Seitenverhaeltnis-Rechner - Breite, Hoehe oder Ratio",'instruction':"Aendere zwei von drei (Breite, Hoehe, Ratio). Das Tool loest das dritte. Ratio akzeptiert '16:9' oder '1.7778'.",'preset':"Voreinstellung",'width':"Breite (px)",'height':"Hoehe (px)",'ratio':"Seitenverhaeltnis",'simplified':"Vereinfacht",'decimal':"Dezimal",'orientation':"Ausrichtung",'landscape':"Querformat",'portrait':"Hochformat",'square':"Quadratisch",'reference':"Tipp: Breite + Hoehe fuer das Ratio, oder Preset + eine Dimension."},
            'pt': {'aria':"Calculadora de proporcao - resolve largura, altura ou razao",'instruction':"Edite dois de tres (largura, altura ou razao). A ferramenta resolve o terceiro. Razao aceita '16:9' ou '1.7778'.",'preset':"Razao predefinida",'width':"Largura (px)",'height':"Altura (px)",'ratio':"Razao de aspecto",'simplified':"Simplificado",'decimal':"Decimal",'orientation':"Orientacao",'landscape':"Paisagem",'portrait':"Retrato",'square':"Quadrado",'reference':"Dica: largura + altura para a razao, ou preset + uma dimensao."},
            'ar': {'aria':"حاسبة نسبة العرض - تحل العرض أو الارتفاع أو النسبة",'instruction':"عدّل اثنين من ثلاثة (عرض، ارتفاع، نسبة). تحل الأداة الثالث. تقبل النسبة '16:9' أو '1.7778'.",'preset':"نسبة مسبقة",'width':"العرض (بكسل)",'height':"الارتفاع (بكسل)",'ratio':"نسبة العرض",'simplified':"مبسّط",'decimal':"عشري",'orientation':"الاتجاه",'landscape':"أفقي",'portrait':"عمودي",'square':"مربع",'reference':"نصيحة: أدخل العرض والارتفاع لرؤية النسبة أو اختر إعداداً مسبقاً."},
            'ru': {'aria':"Калькулятор соотношения - решает ширину, высоту или ratio",'instruction':"Отредактируйте два из трёх (ширина, высота, ratio). Инструмент решит третье. Ratio принимает '16:9' или '1.7778'.",'preset':"Пресет ratio",'width':"Ширина (px)",'height':"Высота (px)",'ratio':"Соотношение сторон",'simplified':"Упрощённо",'decimal':"Десятичное",'orientation':"Ориентация",'landscape':"Альбомная",'portrait':"Портретная",'square':"Квадрат",'reference':"Совет: ширина + высота для ratio, или пресет + одно измерение."},
            'ja': {'aria':"アスペクト比計算機 - 幅・高さ・比率を解決",'instruction':"3つのうち2つを編集（幅・高さ・比率）。ツールが3つ目を解決します。比率は '16:9' または '1.7778' が有効。",'preset':"プリセット比率",'width':"幅 (px)",'height':"高さ (px)",'ratio':"アスペクト比",'simplified':"簡約",'decimal':"小数",'orientation':"向き",'landscape':"横向き",'portrait':"縦向き",'square':"正方形",'reference':"ヒント：幅と高さを入力すると比率が出ます。プリセットを選んで1辺を入力してもOK。"},
            'ko': {'aria':"화면 비율 계산기 - 가로·세로·비율 계산",'instruction':"셋 중 둘을 편집하세요(가로·세로·비율). 도구가 세 번째를 계산합니다. 비율은 '16:9' 또는 '1.7778' 형식.",'preset':"사전 설정 비율",'width':"가로 (px)",'height':"세로 (px)",'ratio':"화면 비율",'simplified':"간소화",'decimal':"십진수",'orientation':"방향",'landscape':"가로",'portrait':"세로",'square':"정사각형",'reference':"팁: 가로·세로를 입력해 비율을 확인하거나 프리셋 선택 후 한 값만 입력."},
        },
    },
    # ----- screen-size-calculator ($ss_labels) -----
    'screen-size-calculator': {
        'labels_var': 'ss_labels',
        'wrapper': 'screen-size-calculator-tool.php',
        'partial': 'screen_size_calc_tool.php',
        'trans': {
            'es': {'aria':"Calculadora de tamano de pantalla",'instruction':"Elige la relacion de aspecto y escribe diagonal, ancho o alto. Las otras dos se rellenan en pulgadas y cm. Tambien se muestra el area visible.",'aspect':"Relacion de aspecto",'measured':"Conozco la",'measure_diagonal':"diagonal",'measure_width':"ancho",'measure_height':"alto",'value':"Valor",'unit':"Unidad",'diagonal':"Diagonal",'width':"Ancho",'height':"Alto",'area':"Area visible",'reference':"Consejo: los TV se anuncian por diagonal, pero lo que ocupa en el mueble es el ancho. 55 16:9 y 55 21:9 son muy diferentes."},
            'fr': {'aria':"Calculateur de taille d'ecran",'instruction':"Choisissez le ratio puis entrez diagonale, largeur ou hauteur. Les deux autres se remplissent en pouces et cm. La surface visible s'affiche aussi.",'aspect':"Ratio d'aspect",'measured':"Je connais la",'measure_diagonal':"diagonale",'measure_width':"largeur",'measure_height':"hauteur",'value':"Valeur",'unit':"Unite",'diagonal':"Diagonale",'width':"Largeur",'height':"Hauteur",'area':"Surface visible",'reference':"Astuce : les TV sont vendues a la diagonale mais c'est la largeur qui compte sur le meuble. 55 16:9 != 55 21:9."},
            'de': {'aria':"Bildschirmgroessen-Rechner",'instruction':"Seitenverhaeltnis waehlen, dann Diagonale, Breite oder Hoehe eingeben. Die anderen beiden fuellen sich in Zoll und cm. Sichtflaeche wird auch angezeigt.",'aspect':"Seitenverhaeltnis",'measured':"Ich kenne die",'measure_diagonal':"Diagonale",'measure_width':"Breite",'measure_height':"Hoehe",'value':"Wert",'unit':"Einheit",'diagonal':"Diagonale",'width':"Breite",'height':"Hoehe",'area':"Sichtflaeche",'reference':"Tipp: TVs werden nach Diagonale verkauft, aber was aufs Moebel passt ist die Breite. 55 16:9 != 55 21:9."},
            'pt': {'aria':"Calculadora de tamanho de tela",'instruction':"Escolha a proporcao e informe diagonal, largura ou altura. As outras duas preenchem em polegadas e cm. Area visivel tambem calculada.",'aspect':"Razao de aspecto",'measured':"Eu sei a",'measure_diagonal':"diagonal",'measure_width':"largura",'measure_height':"altura",'value':"Valor",'unit':"Unidade",'diagonal':"Diagonal",'width':"Largura",'height':"Altura",'area':"Area visivel",'reference':"Dica: TVs sao anunciadas pela diagonal, mas o que importa na estante e a largura. 55 16:9 != 55 21:9."},
            'ar': {'aria':"حاسبة حجم الشاشة",'instruction':"اختر نسبة العرض ثم أدخل القطر أو العرض أو الارتفاع. يملأ الحقلان الآخران بالبوصة والسنتيمتر، مع المساحة المرئية.",'aspect':"نسبة العرض",'measured':"أعرف",'measure_diagonal':"القطر",'measure_width':"العرض",'measure_height':"الارتفاع",'value':"القيمة",'unit':"الوحدة",'diagonal':"القطر",'width':"العرض",'height':"الارتفاع",'area':"المساحة المرئية",'reference':"نصيحة: التلفازات تُسوّق بالقطر، لكن ما يهم على الطاولة هو العرض. 55 بنسبة 16:9 تختلف عن 55 بنسبة 21:9."},
            'ru': {'aria':"Калькулятор размера экрана",'instruction':"Выберите соотношение сторон и введите диагональ, ширину или высоту. Другие две заполняются в дюймах и см. Видимая площадь тоже считается.",'aspect':"Соотношение сторон",'measured':"Я знаю",'measure_diagonal':"диагональ",'measure_width':"ширина",'measure_height':"высота",'value':"Значение",'unit':"Единица",'diagonal':"Диагональ",'width':"Ширина",'height':"Высота",'area':"Видимая площадь",'reference':"Совет: ТВ продают по диагонали, но на тумбу встаёт ширина. 55 16:9 и 55 21:9 очень разные."},
            'ja': {'aria':"画面サイズ計算機",'instruction':"アスペクト比を選び、対角・幅・高さのどれか1つを入力。残り2つをインチとcmで自動計算。可視面積も表示。",'aspect':"アスペクト比",'measured':"知っているのは",'measure_diagonal':"対角",'measure_width':"幅",'measure_height':"高さ",'value':"値",'unit':"単位",'diagonal':"対角",'width':"幅",'height':"高さ",'area':"可視面積",'reference':"ヒント：TVは対角で売られますが、棚に置くときに重要なのは幅。55インチ16:9と55インチ21:9は別物です。"},
            'ko': {'aria':"화면 크기 계산기",'instruction':"화면 비율을 고른 뒤 대각선·가로·세로 중 하나를 입력하세요. 나머지 두 개가 인치와 cm로 자동 계산되며 가시 면적도 표시됩니다.",'aspect':"화면 비율",'measured':"아는 값은",'measure_diagonal':"대각선",'measure_width':"가로",'measure_height':"세로",'value':"값",'unit':"단위",'diagonal':"대각선",'width':"가로",'height':"세로",'area':"가시 면적",'reference':"팁: TV는 대각선으로 광고되지만 가구에 올리는 건 가로 길이입니다. 55 16:9와 55 21:9는 매우 다릅니다."},
        },
    },
    # ----- viewing-distance-calculator ($vd_labels) -----
    'viewing-distance-calculator': {
        'labels_var': 'vd_labels',
        'wrapper': 'viewing-distance-calculator-tool.php',
        'partial': 'viewing_distance_calc_tool.php',
        'trans': {
            'es': {'aria':"Calculadora de distancia de vision",'instruction':"Introduce la diagonal de tu pantalla y la resolucion. El tool devuelve THX optimo (36 FoV), SMPTE cine (30 FoV) y la distancia donde el 4K deja de distinguirse del 1080p.",'diagonal':"Diagonal de la pantalla",'resolution':"Resolucion nativa",'unit':"Unidad",'thx':"THX optimo (36 FoV)",'smpte':"SMPTE cine (30 FoV)",'uhd4k':"Distancia max 4K UHD",'min_4k':"Mas alla, el 4K = 1080p a la vista",'angle':"Angulo en THX",'reference':"Consejo: THX apunta a 36 (inmersivo), SMPTE a 30 (cine comodo). Si te sientas mas lejos que el maximo 4K, comprar un panel 4K no aporta nada a ese tamano."},
            'fr': {'aria':"Calculateur de distance de vision",'instruction':"Saisissez la diagonale et la resolution. L'outil donne THX optimal (36 FoV), SMPTE cinema (30 FoV) et la distance limite ou 4K ne se distingue plus de 1080p.",'diagonal':"Diagonale de l'ecran",'resolution':"Resolution native",'unit':"Unite",'thx':"THX optimal (36 FoV)",'smpte':"SMPTE cinema (30 FoV)",'uhd4k':"Distance max 4K UHD",'min_4k':"Au-dela, 4K = 1080p a l'oeil",'angle':"Angle en THX",'reference':"Astuce : THX = 36 (immersif), SMPTE = 30 (cinema confort). Plus loin que la limite 4K, acheter 4K ne sert a rien a cette taille."},
            'de': {'aria':"Sehabstand-Rechner",'instruction':"Diagonale und Aufloesung eingeben. Das Tool gibt THX-Optimum (36 FoV), SMPTE-Kino (30 FoV) und die maximale Distanz, auf der 4K noch von 1080p unterscheidbar ist.",'diagonal':"Bildschirmdiagonale",'resolution':"Native Aufloesung",'unit':"Einheit",'thx':"THX optimal (36 FoV)",'smpte':"SMPTE Kino (30 FoV)",'uhd4k':"Max 4K UHD Distanz",'min_4k':"Dahinter: 4K = 1080p fuer das Auge",'angle':"Winkel bei THX",'reference':"Tipp: THX = 36 (immersiv), SMPTE = 30 (Kino-Komfort). Weiter als die 4K-Grenze lohnt sich 4K bei dieser Groesse nicht."},
            'pt': {'aria':"Calculadora de distancia de visao",'instruction':"Informe a diagonal da tela e a resolucao. A ferramenta retorna THX otimo (36 FoV), SMPTE cinema (30 FoV) e a distancia limite onde 4K ja nao se distingue de 1080p.",'diagonal':"Diagonal da tela",'resolution':"Resolucao nativa",'unit':"Unidade",'thx':"THX otimo (36 FoV)",'smpte':"SMPTE cinema (30 FoV)",'uhd4k':"Distancia max 4K UHD",'min_4k':"Alem disso, 4K = 1080p ao olho",'angle':"Angulo no THX",'reference':"Dica: THX = 36 (imersivo), SMPTE = 30 (cinema confortavel). Alem da distancia 4K max, comprar 4K nao ajuda nesse tamanho."},
            'ar': {'aria':"حاسبة مسافة المشاهدة",'instruction':"أدخل قطر الشاشة والدقة. تُرجع الأداة THX الأمثل (36°)، SMPTE سينما (30°)، والمسافة القصوى التي يظل عندها 4K مميَّزاً عن 1080p.",'diagonal':"قطر الشاشة",'resolution':"الدقة الأصلية",'unit':"الوحدة",'thx':"THX الأمثل (36°)",'smpte':"SMPTE سينما (30°)",'uhd4k':"الحد الأقصى لـ4K UHD",'min_4k':"بعدها 4K = 1080p للعين",'angle':"الزاوية عند THX",'reference':"نصيحة: THX = 36° (غامر)، SMPTE = 30° (سينما مريحة). إذا جلست أبعد من الحد الأقصى لـ4K فلن تستفيد من دقة 4K بهذا الحجم."},
            'ru': {'aria':"Калькулятор дистанции просмотра",'instruction':"Введите диагональ экрана и разрешение. Инструмент даёт THX оптимум (36° FoV), SMPTE кино (30° FoV) и максимальную дистанцию, на которой 4K ещё отличается от 1080p.",'diagonal':"Диагональ экрана",'resolution':"Нативное разрешение",'unit':"Единица",'thx':"THX оптимум (36° FoV)",'smpte':"SMPTE кино (30° FoV)",'uhd4k':"Макс дистанция 4K UHD",'min_4k':"Дальше 4K = 1080p на глаз",'angle':"Угол при THX",'reference':"Совет: THX = 36° (погружение), SMPTE = 30° (кино-комфорт). Дальше максимума 4K покупать 4K на этом размере бесполезно."},
            'ja': {'aria':"視聴距離計算機",'instruction':"画面対角と解像度を入力。THX最適（36° FoV）、SMPTE映画館（30° FoV）、4Kが1080pと見分けられなくなる最大距離が出ます。",'diagonal':"画面対角",'resolution':"ネイティブ解像度",'unit':"単位",'thx':"THX最適（36° FoV）",'smpte':"SMPTE映画館（30° FoV）",'uhd4k':"4K UHDの最大距離",'min_4k':"これより遠いと4K = 1080pに見える",'angle':"THX時の角度",'reference':"ヒント：THX = 36°（没入）、SMPTE = 30°（映画館コンフォート）。4K最大距離より離れて座るならそのサイズに4Kは無駄です。"},
            'ko': {'aria':"시청 거리 계산기",'instruction':"화면 대각선과 해상도를 입력하세요. THX 최적(36° FoV), SMPTE 영화관(30° FoV), 4K와 1080p의 구분이 사라지는 최대 거리를 보여줍니다.",'diagonal':"화면 대각선",'resolution':"네이티브 해상도",'unit':"단위",'thx':"THX 최적 (36° FoV)",'smpte':"SMPTE 영화관 (30° FoV)",'uhd4k':"4K UHD 최대 거리",'min_4k':"이보다 멀면 4K = 1080p로 보임",'angle':"THX에서의 각도",'reference':"팁: THX = 36° (몰입), SMPTE = 30° (영화관 편안). 4K 최대 거리보다 멀리 앉으면 그 크기에서 4K는 쓸모 없습니다."},
        },
    },
    # ----- fps-test ($fps_labels) -----
    'fps-test': {
        'labels_var': 'fps_labels',
        'wrapper': 'fps-test-tool.php',
        'partial': 'fps_test_tool.php',
        'trans': {
            'es': {'aria':"Prueba de FPS - mide la tasa de fotogramas del navegador",'instruction':"Pulsa Iniciar. La pestana debe estar activa; los navegadores limitan las pestanas en segundo plano a 30 FPS o menos.",'start':"Iniciar",'stop':"Detener",'reset':"Reiniciar",'current':"FPS actual",'avg':"FPS promedio",'min':"FPS min",'max':"FPS max",'low1':"1% low",'total_frames':"Fotogramas",'uptime':"Tiempo",'detected_hz':"Hz de pantalla probable",'reference':"Consejo: el FPS del navegador no supera el Hz del monitor. 60 = 60Hz, 144 = 144Hz, etc. El 1% low es el suelo de tartamudeo."},
            'fr': {'aria':"Test FPS - mesure la frequence d'images du navigateur",'instruction':"Cliquez sur Demarrer. L'onglet doit etre au premier plan ; les onglets en arriere-plan sont limites a 30 FPS ou moins.",'start':"Demarrer",'stop':"Arreter",'reset':"Reinitialiser",'current':"FPS actuel",'avg':"FPS moyen",'min':"FPS min",'max':"FPS max",'low1':"1% low",'total_frames':"Images",'uptime':"Duree",'detected_hz':"Hz d'ecran probable",'reference':"Astuce : le FPS du navigateur ne depasse pas le Hz de l'ecran. 60 = 60Hz. 1% low = plancher de saccades."},
            'de': {'aria':"FPS-Test - misst die Browser-Bildrate",'instruction':"Druecke Start. Der Tab muss im Vordergrund sein; Browser drosseln Hintergrundtabs auf 30 FPS oder weniger.",'start':"Start",'stop':"Stopp",'reset':"Zuruecksetzen",'current':"Aktuelle FPS",'avg':"Durchschnittl. FPS",'min':"Min FPS",'max':"Max FPS",'low1':"1% low",'total_frames':"Frames",'uptime':"Laufzeit",'detected_hz':"Wahrscheinliche Hz",'reference':"Tipp: Browser-FPS kann die Hz des Monitors nicht ueberschreiten. 60 = 60Hz. 1% low = Stotter-Schwelle."},
            'pt': {'aria':"Teste de FPS - mede a taxa de quadros do navegador",'instruction':"Clique em Iniciar. A aba deve estar em primeiro plano; navegadores limitam abas em segundo plano a 30 FPS ou menos.",'start':"Iniciar",'stop':"Parar",'reset':"Reiniciar",'current':"FPS atual",'avg':"FPS medio",'min':"Min FPS",'max':"Max FPS",'low1':"1% low",'total_frames':"Quadros",'uptime':"Tempo",'detected_hz':"Hz provavel",'reference':"Dica: FPS do navegador nao ultrapassa o Hz do monitor. 60 = 60Hz. 1% low = piso de stutter."},
            'ar': {'aria':"اختبار FPS - يقيس معدل إطارات المتصفح",'instruction':"اضغط ابدأ. يجب أن تكون التبويبة في المقدمة؛ المتصفحات تقلل التبويبات الخلفية إلى 30 FPS أو أقل.",'start':"ابدأ",'stop':"إيقاف",'reset':"إعادة تعيين",'current':"FPS الحالي",'avg':"متوسط FPS",'min':"أقل FPS",'max':"أعلى FPS",'low1':"1% low",'total_frames':"الإطارات",'uptime':"الوقت",'detected_hz':"Hz الشاشة المتوقعة",'reference':"نصيحة: FPS المتصفح لا يتجاوز Hz الشاشة. 60 = 60Hz. 1% low = أرضية التقطّع."},
            'ru': {'aria':"Тест FPS - измеряет частоту кадров браузера",'instruction':"Нажмите Старт. Вкладка должна быть активной; браузеры ограничивают фоновые вкладки до 30 FPS и ниже.",'start':"Старт",'stop':"Стоп",'reset':"Сброс",'current':"Текущий FPS",'avg':"Средний FPS",'min':"Мин FPS",'max':"Макс FPS",'low1':"1% low",'total_frames':"Кадров",'uptime':"Время",'detected_hz':"Предполагаемые Гц",'reference':"Совет: FPS браузера не превышает Гц монитора. 60 = 60Гц. 1% low = пол заиканий."},
            'ja': {'aria':"FPSテスト - ブラウザのフレームレート計測",'instruction':"スタートを押してください。このタブが前面である必要があります。バックグラウンドタブは30 FPS以下にスロットルされます。",'start':"スタート",'stop':"停止",'reset':"リセット",'current':"現在のFPS",'avg':"平均FPS",'min':"最小FPS",'max':"最大FPS",'low1':"1% low",'total_frames':"フレーム数",'uptime':"稼働時間",'detected_hz':"推定ディスプレイHz",'reference':"ヒント：ブラウザFPSはモニターHzを超えません。60 = 60Hz。1% lowはカクつきの底値です。"},
            'ko': {'aria':"FPS 테스트 - 브라우저 프레임 레이트 측정",'instruction':"시작을 누르세요. 탭이 포그라운드여야 합니다. 브라우저는 백그라운드 탭을 30 FPS 이하로 제한합니다.",'start':"시작",'stop':"중지",'reset':"초기화",'current':"현재 FPS",'avg':"평균 FPS",'min':"최소 FPS",'max':"최대 FPS",'low1':"1% low",'total_frames':"프레임 수",'uptime':"가동 시간",'detected_hz':"추정 디스플레이 Hz",'reference':"팁: 브라우저 FPS는 모니터 Hz를 넘지 않습니다. 60 = 60Hz. 1% low는 스터터 바닥값."},
        },
    },
    # ----- resolution-test ($rt_labels) -----
    'resolution-test': {
        'labels_var': 'rt_labels',
        'wrapper': 'resolution-test-tool.php',
        'partial': 'resolution_test_tool.php',
        'trans': {
            'es': {'aria':"Prueba de resolucion de pantalla",'instruction':"Todo se actualiza en vivo. Redimensiona la ventana o haz zoom para ver cambiar viewport y DPR.",'screen_size':"Resolucion de pantalla",'native_res':"Resolucion fisica nativa",'viewport':"Viewport (esta pestana)",'dpr':"Device pixel ratio",'color_depth':"Profundidad de color",'color_gamut':"Gama de color",'pixel_depth':"Pixel depth",'orientation':"Orientacion",'aspect':"Relacion de aspecto",'avail':"Pantalla disponible",'reference':"Consejo: DPR multiplica pixeles CSS a fisicos. Retina / moviles 2-3. Nativa = CSS x DPR."},
            'fr': {'aria':"Test de resolution d'ecran",'instruction':"Tout se met a jour en direct. Redimensionnez la fenetre ou zoomez pour voir viewport et DPR changer.",'screen_size':"Resolution d'ecran",'native_res':"Resolution physique native",'viewport':"Viewport (cet onglet)",'dpr':"Device pixel ratio",'color_depth':"Profondeur de couleur",'color_gamut':"Gamut couleur",'pixel_depth':"Pixel depth",'orientation':"Orientation",'aspect':"Ratio d'aspect",'avail':"Ecran disponible",'reference':"Astuce : le DPR multiplie les pixels CSS en pixels physiques. Retina / mobiles 2-3. Native = CSS x DPR."},
            'de': {'aria':"Bildschirmaufloesungs-Test",'instruction':"Alles aktualisiert live. Fenster groessenaendern oder zoomen, um Viewport und DPR zu beobachten.",'screen_size':"Bildschirmaufloesung",'native_res':"Native Pixelaufloesung",'viewport':"Viewport (dieser Tab)",'dpr':"Device Pixel Ratio",'color_depth':"Farbtiefe",'color_gamut':"Farbgamut",'pixel_depth':"Pixeltiefe",'orientation':"Ausrichtung",'aspect':"Seitenverhaeltnis",'avail':"Verfuegbarer Bildschirm",'reference':"Tipp: DPR multipliziert CSS-Pixel zu physischen. Retina / Handy 2-3. Nativ = CSS x DPR."},
            'pt': {'aria':"Teste de resolucao de tela",'instruction':"Tudo atualiza ao vivo. Redimensione ou de zoom para ver viewport e DPR mudarem.",'screen_size':"Resolucao de tela",'native_res':"Resolucao fisica nativa",'viewport':"Viewport (esta aba)",'dpr':"Device pixel ratio",'color_depth':"Profundidade de cor",'color_gamut':"Gamut de cor",'pixel_depth':"Pixel depth",'orientation':"Orientacao",'aspect':"Razao de aspecto",'avail':"Tela disponivel",'reference':"Dica: DPR multiplica pixels CSS para fisicos. Retina / celular 2-3. Nativo = CSS x DPR."},
            'ar': {'aria':"اختبار دقة الشاشة",'instruction':"كل القيم تتحدث لحظياً. غيّر حجم النافذة أو قم بالتكبير لرؤية تغير viewport وDPR.",'screen_size':"دقة الشاشة",'native_res':"الدقة الفيزيائية الأصلية",'viewport':"Viewport (هذه التبويبة)",'dpr':"نسبة البكسل للجهاز",'color_depth':"عمق الألوان",'color_gamut':"نطاق الألوان",'pixel_depth':"عمق البكسل",'orientation':"الاتجاه",'aspect':"نسبة العرض",'avail':"المساحة المتاحة",'reference':"نصيحة: DPR يضرب بكسلات CSS للوصول إلى الفيزيائية. Retina / الهواتف 2-3. الأصلية = CSS × DPR."},
            'ru': {'aria':"Тест разрешения экрана",'instruction':"Всё обновляется в реальном времени. Измените размер окна или увеличьте масштаб, чтобы увидеть изменения viewport и DPR.",'screen_size':"Разрешение экрана",'native_res':"Нативное физическое разрешение",'viewport':"Viewport (эта вкладка)",'dpr':"Device pixel ratio",'color_depth':"Глубина цвета",'color_gamut':"Цветовой охват",'pixel_depth':"Глубина пикселя",'orientation':"Ориентация",'aspect':"Соотношение сторон",'avail':"Доступный экран",'reference':"Совет: DPR умножает CSS-пиксели в физические. Retina / мобильные 2-3. Нативный = CSS × DPR."},
            'ja': {'aria':"画面解像度テスト",'instruction':"すべての値はライブで更新されます。ウィンドウをリサイズしたりズームすると viewport と DPR が変化します。",'screen_size':"画面解像度",'native_res':"ネイティブ物理解像度",'viewport':"ビューポート（このタブ）",'dpr':"デバイスピクセル比（DPR）",'color_depth':"色深度",'color_gamut':"色域",'pixel_depth':"ピクセル深度",'orientation':"向き",'aspect':"アスペクト比",'avail':"利用可能な画面",'reference':"ヒント：DPRはCSSピクセルを物理ピクセルに倍率換算します。Retina・スマホは2-3。ネイティブ = CSS × DPR。"},
            'ko': {'aria':"화면 해상도 테스트",'instruction':"모든 값이 실시간 업데이트됩니다. 창 크기를 조절하거나 확대하면 뷰포트와 DPR이 변합니다.",'screen_size':"화면 해상도",'native_res':"네이티브 물리 해상도",'viewport':"뷰포트 (이 탭)",'dpr':"장치 픽셀 비(DPR)",'color_depth':"색 심도",'color_gamut':"색 영역",'pixel_depth':"픽셀 깊이",'orientation':"방향",'aspect':"화면 비율",'avail':"사용 가능 화면",'reference':"팁: DPR은 CSS 픽셀을 물리 픽셀로 곱합니다. Retina·모바일은 2-3. 네이티브 = CSS × DPR."},
        },
    },
    # ----- apm-test ($apm_labels) -----
    'apm-test': {
        'labels_var': 'apm_labels',
        'wrapper': 'apm-test-tool.php',
        'partial': 'apm_test_tool.php',
        'trans': {
            'es': {'aria':"Prueba de APM - contador de acciones por minuto",'instruction':"Pulsa Iniciar, haz foco en el pad y realiza tus acciones normales (clics, hotkeys, arrastres). Cada clic o pulsacion cuenta como una accion.",'start':"Iniciar",'stop':"Detener",'reset':"Reiniciar",'current_apm':"APM actual",'peak_apm':"Pico de APM",'avg_apm':"Promedio de sesion",'total_actions':"Acciones totales",'elapsed':"Tiempo",'clicks':"Clics",'keys':"Teclas",'pad_hint':"Haz clic aqui para enfocar el pad y actuar.",'reference':"Consejo: RTS casual 40-80 APM, plata 100, platino 200, master 300+, pro 300-450 sostenido con picos de 800."},
            'fr': {'aria':"Test APM - compteur d'actions par minute",'instruction':"Cliquez sur Demarrer, donnez le focus au pad et effectuez vos actions normales (clics, raccourcis, drags). Chaque clic ou touche compte.",'start':"Demarrer",'stop':"Arreter",'reset':"Reinitialiser",'current_apm':"APM actuel",'peak_apm':"APM pic",'avg_apm':"Moyenne de session",'total_actions':"Actions totales",'elapsed':"Temps",'clicks':"Clics",'keys':"Touches",'pad_hint':"Cliquez ici pour donner le focus au pad et agir.",'reference':"Astuce : RTS casual 40-80, Silver 100, Platinum 200, Master 300+, pro 300-450 soutenu avec pics de 800."},
            'de': {'aria':"APM-Test - Aktionen-pro-Minute-Zaehler",'instruction':"Starten druecken, Fokus auf das Pad und normale Aktionen ausfuehren (Klicks, Hotkeys, Drags). Jeder Klick oder Tastendruck zaehlt.",'start':"Start",'stop':"Stopp",'reset':"Zuruecksetzen",'current_apm':"Aktuelle APM",'peak_apm':"APM-Peak",'avg_apm':"Session-Durchschnitt",'total_actions':"Gesamte Aktionen",'elapsed':"Zeit",'clicks':"Klicks",'keys':"Tasten",'pad_hint':"Hier klicken fuer Pad-Fokus und Aktionen.",'reference':"Tipp: RTS casual 40-80, Silver 100, Platin 200, Master 300+, Pro 300-450 mit Peaks bis 800."},
            'pt': {'aria':"Teste de APM - contador de acoes por minuto",'instruction':"Clique em Iniciar, de foco ao pad e execute acoes normais (cliques, hotkeys, drags). Cada clique ou tecla conta.",'start':"Iniciar",'stop':"Parar",'reset':"Reiniciar",'current_apm':"APM atual",'peak_apm':"APM pico",'avg_apm':"Media da sessao",'total_actions':"Acoes totais",'elapsed':"Tempo",'clicks':"Cliques",'keys':"Teclas",'pad_hint':"Clique aqui para dar foco ao pad e agir.",'reference':"Dica: RTS casual 40-80, Silver 100, Platinum 200, Master 300+, pro 300-450 sustentado com picos ate 800."},
            'ar': {'aria':"اختبار APM - عداد الإجراءات في الدقيقة",'instruction':"اضغط ابدأ، ركّز اللوحة ونفّذ إجراءاتك الطبيعية (نقرات، اختصارات، سحب). كل نقرة أو ضغطة مفتاح تُحسب.",'start':"ابدأ",'stop':"إيقاف",'reset':"إعادة تعيين",'current_apm':"APM الحالي",'peak_apm':"ذروة APM",'avg_apm':"متوسط الجلسة",'total_actions':"إجمالي الإجراءات",'elapsed':"الوقت",'clicks':"النقرات",'keys':"المفاتيح",'pad_hint':"انقر هنا لتركيز اللوحة والبدء.",'reference':"نصيحة: RTS عادي 40-80، فضي 100، بلاتيني 200، ماستر 300+، محترفون 300-450 مستدام مع ذرى حتى 800."},
            'ru': {'aria':"Тест APM - счётчик действий в минуту",'instruction':"Нажмите Старт, наведите фокус на пад и выполняйте обычные действия (клики, горячие клавиши, перетаскивания). Каждый клик или клавиша считается.",'start':"Старт",'stop':"Стоп",'reset':"Сброс",'current_apm':"Текущий APM",'peak_apm':"Пиковый APM",'avg_apm':"Среднее за сессию",'total_actions':"Всего действий",'elapsed':"Время",'clicks':"Клики",'keys':"Клавиши",'pad_hint':"Нажмите здесь, чтобы сфокусировать пад.",'reference':"Совет: RTS casual 40-80, Silver 100, Platinum 200, Master 300+, pro 300-450 устойчиво с пиками до 800."},
            'ja': {'aria':"APMテスト - 分あたりアクションカウンター",'instruction':"スタートを押し、パッドにフォーカスを合わせて、普段通りにクリック・ホットキー・ドラッグを実行。各クリックまたは非修飾キーが1アクション。",'start':"スタート",'stop':"停止",'reset':"リセット",'current_apm':"現在のAPM",'peak_apm':"最大APM",'avg_apm':"セッション平均",'total_actions':"総アクション",'elapsed':"経過時間",'clicks':"クリック",'keys':"キー押下",'pad_hint':"ここをクリックしてパッドにフォーカス。",'reference':"ヒント：RTSカジュアル40-80、シルバー100、プラチナ200、マスター300+、プロは持続300-450でピーク800超。"},
            'ko': {'aria':"APM 테스트 - 분당 액션 카운터",'instruction':"시작을 누르고 패드에 포커스를 준 뒤 평소처럼 클릭·단축키·드래그를 실행하세요. 각 클릭이나 비수정키는 1액션.",'start':"시작",'stop':"중지",'reset':"초기화",'current_apm':"현재 APM",'peak_apm':"최고 APM",'avg_apm':"세션 평균",'total_actions':"총 액션",'elapsed':"경과 시간",'clicks':"클릭",'keys':"키 입력",'pad_hint':"여기를 클릭해 패드에 포커스.",'reference':"팁: RTS 캐주얼 40-80, 실버 100, 플래티넘 200, 마스터 300+, 프로 300-450 지속에 피크 800+."},
        },
    },
    # ----- mouse-spin-test ($ms_labels) -----
    'mouse-spin-test': {
        'labels_var': 'ms_labels',
        'wrapper': 'mouse-spin-tool.php',
        'partial': 'mouse_spin_tool.php',
        'trans': {
            'es': {'aria':"Prueba de giro del raton - cuenta rotaciones de 360",'instruction':"Pulsa Iniciar, coloca el cursor en el pad, manten el boton izquierdo y gira alrededor del punto central. Cada 360 cuenta como un giro.",'duration':"Duracion",'dur_15':"15 segundos",'dur_30':"30 segundos",'dur_60':"60 segundos",'start':"Iniciar",'stop':"Detener",'reset':"Reiniciar",'pad_hint':"Manten el boton izquierdo y gira alrededor del centro.",'time_left':"Tiempo restante",'spins':"Giros",'peak_sps':"Giros/seg pico",'degrees':"Rotacion total",'direction':"Direccion",'dir_cw':"Horario",'dir_ccw':"Antihorario",'dir_idle':"-",'reference':"Consejo: DPI alto permite girar mas con menos movimiento. Prueba en ambos sentidos y rondas lentas vs flicks rapidos."},
            'fr': {'aria':"Test de rotation souris - compte les tours 360",'instruction':"Demarrez, placez le curseur sur le pad, maintenez le clic gauche et tournez autour du centre. Chaque tour 360 compte.",'duration':"Duree",'dur_15':"15 secondes",'dur_30':"30 secondes",'dur_60':"60 secondes",'start':"Demarrer",'stop':"Arreter",'reset':"Reinitialiser",'pad_hint':"Maintenez le clic gauche et tournez autour du centre.",'time_left':"Temps restant",'spins':"Tours",'peak_sps':"Tours/s pic",'degrees':"Rotation totale",'direction':"Direction",'dir_cw':"Horaire",'dir_ccw':"Anti-horaire",'dir_idle':"-",'reference':"Astuce : DPI eleve permet plus de tours avec moins de mouvement. Essayez les deux sens, lent vs rapide."},
            'de': {'aria':"Maus-Dreh-Test - zaehlt 360-Rotationen",'instruction':"Start druecken, Cursor aufs Pad, linke Taste halten und um den Mittelpunkt drehen. Jede volle 360-Drehung ist ein Spin.",'duration':"Dauer",'dur_15':"15 Sekunden",'dur_30':"30 Sekunden",'dur_60':"60 Sekunden",'start':"Start",'stop':"Stopp",'reset':"Zuruecksetzen",'pad_hint':"Linke Taste halten und um den Mittelpunkt drehen.",'time_left':"Zeit",'spins':"Spins",'peak_sps':"Spins/s Peak",'degrees':"Gesamtrotation",'direction':"Richtung",'dir_cw':"Im Uhrzeigersinn",'dir_ccw':"Gegen den UZS",'dir_idle':"-",'reference':"Tipp: hohe DPI erlaubt mehr Spins mit weniger Handbewegung. Beide Richtungen und langsam vs Flick probieren."},
            'pt': {'aria':"Teste de giro do mouse - conta rotacoes 360",'instruction':"Clique em Iniciar, posicione o cursor no pad, segure o botao esquerdo e gire ao redor do ponto central. Cada 360 conta.",'duration':"Duracao",'dur_15':"15 segundos",'dur_30':"30 segundos",'dur_60':"60 segundos",'start':"Iniciar",'stop':"Parar",'reset':"Reiniciar",'pad_hint':"Segure o botao esquerdo e gire ao redor do centro.",'time_left':"Tempo restante",'spins':"Giros",'peak_sps':"Giros/s pico",'degrees':"Rotacao total",'direction':"Direcao",'dir_cw':"Horario",'dir_ccw':"Anti-horario",'dir_idle':"-",'reference':"Dica: DPI alto permite mais giros com menos movimento. Teste nos dois sentidos, lento vs rapido."},
            'ar': {'aria':"اختبار دوران الماوس - يعد الدورات 360",'instruction':"اضغط ابدأ، ضع المؤشر على اللوحة، اضغط باستمرار على الزر الأيسر ودر حول النقطة المركزية. كل 360° تعادل دورة واحدة.",'duration':"المدة",'dur_15':"15 ثانية",'dur_30':"30 ثانية",'dur_60':"60 ثانية",'start':"ابدأ",'stop':"إيقاف",'reset':"إعادة تعيين",'pad_hint':"اضغط الزر الأيسر ودر حول المركز.",'time_left':"الوقت المتبقي",'spins':"الدورات",'peak_sps':"ذروة الدورات/ث",'degrees':"الدوران الكلي",'direction':"الاتجاه",'dir_cw':"باتجاه الساعة",'dir_ccw':"عكس الساعة",'dir_idle':"-",'reference':"نصيحة: DPI مرتفع يسمح بعدد أكبر من الدورات بأقل حركة. جرّب الاتجاهين والسرعات المختلفة."},
            'ru': {'aria':"Тест вращения мыши - считает обороты на 360°",'instruction':"Нажмите Старт, наведите курсор на пад, зажмите левую кнопку и вращайте вокруг центра. Каждые 360° = один оборот.",'duration':"Длительность",'dur_15':"15 секунд",'dur_30':"30 секунд",'dur_60':"60 секунд",'start':"Старт",'stop':"Стоп",'reset':"Сброс",'pad_hint':"Зажмите левую кнопку и вращайте вокруг центра.",'time_left':"Осталось",'spins':"Обороты",'peak_sps':"Пик об/с",'degrees':"Общее вращение",'direction':"Направление",'dir_cw':"По часовой",'dir_ccw':"Против часовой",'dir_idle':"-",'reference':"Совет: высокий DPI даёт больше оборотов меньшими движениями. Пробуйте оба направления и разные темпы."},
            'ja': {'aria':"マウス回転テスト - 360°回転をカウント",'instruction':"スタートを押し、カーソルをパッドに置き、左ボタンを押したまま中心点の周りを回してください。360°ごとに1回転。",'duration':"時間",'dur_15':"15秒",'dur_30':"30秒",'dur_60':"60秒",'start':"スタート",'stop':"停止",'reset':"リセット",'pad_hint':"左ボタンを押したまま中心を回します。",'time_left':"残り時間",'spins':"回転数",'peak_sps':"ピーク回転/秒",'degrees':"累計回転",'direction':"方向",'dir_cw':"時計回り",'dir_ccw':"反時計回り",'dir_idle':"-",'reference':"ヒント：高DPIなら少ない動きで多く回せます。時計回り・反時計回り、ゆっくり・素早い振りも試しましょう。"},
            'ko': {'aria':"마우스 스핀 테스트 - 360° 회전 카운트",'instruction':"시작을 누르고 커서를 패드에 올린 뒤 왼쪽 버튼을 누른 채 중심점을 빙글빙글 돌리세요. 360°마다 1회전.",'duration':"시간",'dur_15':"15초",'dur_30':"30초",'dur_60':"60초",'start':"시작",'stop':"중지",'reset':"초기화",'pad_hint':"왼쪽 버튼을 누른 채 중심을 돌리세요.",'time_left':"남은 시간",'spins':"회전 수",'peak_sps':"피크 회전/초",'degrees':"누적 회전",'direction':"방향",'dir_cw':"시계방향",'dir_ccw':"반시계방향",'dir_idle':"-",'reference':"팁: 높은 DPI는 적은 움직임으로 더 많은 회전을 허용합니다. 양방향과 느림·빠름을 모두 시도하세요."},
        },
    },
    # ----- burn-in-test ($bi_labels) -----
    'burn-in-test': {
        'labels_var': 'bi_labels',
        'wrapper': 'burn-in-tool.php',
        'partial': 'burn_in_tool.php',
        'trans': {
            'es': {'aria':"Prueba de burn-in OLED y retencion de imagen",'instruction':"Pulsa Pantalla completa. Usa las flechas o los botones para pasar colores. Un blanco solido durante 30-60 s revela retencion. Pulsa Esc para salir.",'mode':"Modo",'mode_cycle':"Ciclo de colores (W, K, R, G, B, C, M, Y)",'mode_checker':"Tablero fino",'mode_scroll':"Refrescador deslizante",'auto':"Auto-avance",'auto_off':"Desactivado",'auto_5':"Cada 5 s",'auto_15':"Cada 15 s",'auto_60':"Cada 60 s",'fullscreen':"Pantalla completa",'exit_fs':"Salir",'next':"Siguiente",'prev':"Anterior",'current_color':"Color actual",'reference':"Consejo: deja el refrescador toda la noche para ayudar al OLED con retencion leve. El burn-in permanente (tras 8 h de blanco) no se puede arreglar."},
            'fr': {'aria':"Test de burn-in OLED et retention d'image",'instruction':"Cliquez Plein ecran. Utilisez les fleches ou les boutons pour parcourir les couleurs. Un blanc plein 30-60 s revele la retention. Esc pour quitter.",'mode':"Mode",'mode_cycle':"Cycle de couleurs (W, K, R, G, B, C, M, Y)",'mode_checker':"Damier fin",'mode_scroll':"Rafraichisseur defilant",'auto':"Auto-avance",'auto_off':"Desactive",'auto_5':"Toutes les 5 s",'auto_15':"Toutes les 15 s",'auto_60':"Toutes les 60 s",'fullscreen':"Plein ecran",'exit_fs':"Quitter",'next':"Suivant",'prev':"Precedent",'current_color':"Couleur actuelle",'reference':"Astuce : laissez le rafraichisseur la nuit pour aider un OLED avec retention legere. Burn-in permanent (apres 8 h de blanc) = irreparable."},
            'de': {'aria':"OLED-Burn-In- und Image-Retention-Test",'instruction':"Klicke Vollbild. Pfeiltasten oder Buttons fuer Farbwechsel. Vollbildweiss fuer 30-60 s enthuellt Retention. Esc zum Verlassen.",'mode':"Modus",'mode_cycle':"Farbzyklus (W, K, R, G, B, C, M, Y)",'mode_checker':"Feines Schachbrett",'mode_scroll':"Rollender Refresher",'auto':"Auto-Weiterschalten",'auto_off':"Aus",'auto_5':"Alle 5 s",'auto_15':"Alle 15 s",'auto_60':"Alle 60 s",'fullscreen':"Vollbild",'exit_fs':"Verlassen",'next':"Weiter",'prev':"Zurueck",'current_color':"Aktuelle Farbe",'reference':"Tipp: Refresher ueber Nacht laufen lassen, um OLED mit leichter Retention zu helfen. Permanenter Burn-In (nach 8 h Weiss) ist nicht reparabel."},
            'pt': {'aria':"Teste de burn-in OLED e retencao de imagem",'instruction':"Clique Tela cheia. Use setas ou botoes para trocar cores. Branco solido por 30-60 s revela retencao. Esc para sair.",'mode':"Modo",'mode_cycle':"Ciclo de cores (W, K, R, G, B, C, M, Y)",'mode_checker':"Xadrez fino",'mode_scroll':"Refrescador deslizante",'auto':"Auto-avanco",'auto_off':"Desligado",'auto_5':"A cada 5 s",'auto_15':"A cada 15 s",'auto_60':"A cada 60 s",'fullscreen':"Tela cheia",'exit_fs':"Sair",'next':"Proximo",'prev':"Anterior",'current_color':"Cor atual",'reference':"Dica: deixe o refrescador rodando a noite para ajudar o OLED com retencao leve. Burn-in permanente (apos 8 h de branco) nao tem conserto."},
            'ar': {'aria':"اختبار حرق OLED واحتجاز الصورة",'instruction':"اضغط ملء الشاشة. استخدم الأسهم أو الأزرار للتنقل بين الألوان. الأبيض الصلب لمدة 30-60 ثانية يكشف الاحتجاز. Esc للخروج.",'mode':"الوضع",'mode_cycle':"دورة الألوان (W, K, R, G, B, C, M, Y)",'mode_checker':"شطرنج دقيق",'mode_scroll':"مجدد متحرك",'auto':"تقدم تلقائي",'auto_off':"إيقاف",'auto_5':"كل 5 ث",'auto_15':"كل 15 ث",'auto_60':"كل 60 ث",'fullscreen':"ملء الشاشة",'exit_fs':"خروج",'next':"التالي",'prev':"السابق",'current_color':"اللون الحالي",'reference':"نصيحة: اترك المجدد طوال الليل لمساعدة OLED على التعافي من الاحتجاز الخفيف. الحرق الدائم (بعد 8 ساعات من الأبيض) لا يمكن إصلاحه."},
            'ru': {'aria':"Тест выгорания OLED и остаточного изображения",'instruction':"Нажмите Полный экран. Используйте стрелки или кнопки для смены цветов. Сплошной белый 30-60 с выявит остаточное изображение. Esc — выход.",'mode':"Режим",'mode_cycle':"Цикл цветов (W, K, R, G, B, C, M, Y)",'mode_checker':"Мелкая шахматка",'mode_scroll':"Бегущий обновитель",'auto':"Авто-переход",'auto_off':"Выкл",'auto_5':"Каждые 5 с",'auto_15':"Каждые 15 с",'auto_60':"Каждые 60 с",'fullscreen':"Полный экран",'exit_fs':"Выход",'next':"Далее",'prev':"Назад",'current_color':"Текущий цвет",'reference':"Совет: оставьте обновитель на ночь для лёгкого выгорания OLED. Постоянное выгорание (после 8 ч белого) уже не починить."},
            'ja': {'aria':"OLED焼き付き・画像保持テスト",'instruction':"フルスクリーンをクリック。矢印またはボタンで色を送ります。白単色を30-60秒表示すると保持が見えます。Escで終了。",'mode':"モード",'mode_cycle':"色サイクル (W, K, R, G, B, C, M, Y)",'mode_checker':"細かい市松",'mode_scroll':"スクロールリフレッシャー",'auto':"自動送り",'auto_off':"オフ",'auto_5':"5秒ごと",'auto_15':"15秒ごと",'auto_60':"60秒ごと",'fullscreen':"フルスクリーン",'exit_fs':"終了",'next':"次へ",'prev':"前へ",'current_color':"現在の色",'reference':"ヒント：リフレッシャーを一晩動かすと軽度の保持は回復します。8時間の白で消えない永久焼き付きは直りません。"},
            'ko': {'aria':"OLED 번인·이미지 잔상 테스트",'instruction':"전체화면을 클릭하세요. 화살표 또는 버튼으로 색상을 전환하세요. 흰색 30-60초는 잔상을 드러냅니다. Esc로 종료.",'mode':"모드",'mode_cycle':"색상 사이클 (W, K, R, G, B, C, M, Y)",'mode_checker':"미세 체커보드",'mode_scroll':"스크롤 리프레셔",'auto':"자동 전환",'auto_off':"꺼짐",'auto_5':"5초마다",'auto_15':"15초마다",'auto_60':"60초마다",'fullscreen':"전체화면",'exit_fs':"종료",'next':"다음",'prev':"이전",'current_color':"현재 색상",'reference':"팁: 리프레셔를 밤새 돌리면 경미한 OLED 잔상 회복에 도움. 8시간 흰색 후 남는 영구 번인은 복구되지 않습니다."},
        },
    },
    # ----- color-range-test ($cr_labels) -----
    'color-range-test': {
        'labels_var': 'cr_labels',
        'wrapper': 'color-range-tool.php',
        'partial': 'color_range_tool.php',
        'trans': {
            'es': {'aria':"Prueba de rango de color - detecta RGB limitado vs completo",'instruction':"Mira cada fila. Una pantalla COMPLETA muestra todas las fichas distintas. Una pantalla LIMITADA funde las primeras (a negro puro) y las ultimas (a blanco puro).",'near_black':"Cerca de negro (RGB 0-31)",'near_white':"Cerca de blanco (RGB 224-255)",'ramp':"Degradado continuo (0 a 255)",'fullscreen':"Pantalla completa",'exit_fs':"Salir",'reference':"Consejo: Windows suele enviar HDMI en rango limitado por defecto. En NVIDIA: Panel de control > Resolucion > Rango dinamico de salida = Completo."},
            'fr': {'aria':"Test de plage de couleur - detecte RGB limite vs complet",'instruction':"Regardez chaque ligne. Un ecran COMPLET montre toutes les tuiles distinctes. Un ecran LIMITE fond les premieres (en noir pur) et les dernieres (en blanc pur).",'near_black':"Pres du noir (RGB 0-31)",'near_white':"Pres du blanc (RGB 224-255)",'ramp':"Degrade continu (0 a 255)",'fullscreen':"Plein ecran",'exit_fs':"Quitter",'reference':"Astuce : Windows envoie souvent HDMI en plage limitee par defaut. NVIDIA : Resolution > Plage dynamique de sortie = Complet."},
            'de': {'aria':"Farbumfang-Test - erkennt Limited vs Full RGB",'instruction':"Sieh dir jede Zeile an. Ein FULL-Display zeigt jede Kachel getrennt. Ein LIMITED-Display verschmilzt die ersten (zu Schwarz) und letzten (zu Weiss).",'near_black':"Nahe Schwarz (RGB 0-31)",'near_white':"Nahe Weiss (RGB 224-255)",'ramp':"Kontinuierlicher Verlauf (0 bis 255)",'fullscreen':"Vollbild",'exit_fs':"Verlassen",'reference':"Tipp: Windows sendet HDMI oft standardmaessig in Limited. NVIDIA: Aufloesung > Dynamischer Bereich = Full."},
            'pt': {'aria':"Teste de faixa de cor - detecta RGB limitado vs completo",'instruction':"Olhe cada linha. Uma tela COMPLETA mostra cada patch distinto. Uma tela LIMITADA funde os primeiros (em preto puro) e os ultimos (em branco puro).",'near_black':"Proximo ao preto (RGB 0-31)",'near_white':"Proximo ao branco (RGB 224-255)",'ramp':"Gradiente continuo (0 a 255)",'fullscreen':"Tela cheia",'exit_fs':"Sair",'reference':"Dica: Windows costuma enviar HDMI em faixa limitada por padrao. NVIDIA: Resolucao > Faixa dinamica = Completa."},
            'ar': {'aria':"اختبار نطاق الألوان - يكتشف RGB المحدود مقابل الكامل",'instruction':"انظر إلى كل صف. الشاشة الكاملة تُظهر كل رقعة مميزة. الشاشة المحدودة تمزج الأوائل (إلى أسود خالص) والأواخر (إلى أبيض خالص).",'near_black':"قرب الأسود (RGB 0-31)",'near_white':"قرب الأبيض (RGB 224-255)",'ramp':"تدرج مستمر (0 إلى 255)",'fullscreen':"ملء الشاشة",'exit_fs':"خروج",'reference':"نصيحة: Windows يرسل HDMI غالباً بنطاق محدود افتراضياً. NVIDIA: الدقة > نطاق الإخراج الديناميكي = Full."},
            'ru': {'aria':"Тест диапазона цвета - обнаруживает Limited vs Full RGB",'instruction':"Смотрите на каждую строку. FULL-дисплей показывает каждый патч отличным. LIMITED-дисплей сливает первые (в чисто чёрный) и последние (в чисто белый).",'near_black':"Рядом с чёрным (RGB 0-31)",'near_white':"Рядом с белым (RGB 224-255)",'ramp':"Непрерывный градиент (0 до 255)",'fullscreen':"Полный экран",'exit_fs':"Выход",'reference':"Совет: Windows часто отправляет HDMI в Limited по умолчанию. NVIDIA: Разрешение > Динамический диапазон = Full."},
            'ja': {'aria':"カラーレンジテスト - 制限RGBとフルRGBを判別",'instruction':"各行を見てください。フル表示はすべてのパッチが区別可能。制限表示は最暗部（純黒に潰れ）と最明部（純白に潰れ）が融合します。",'near_black':"ブラック近傍 (RGB 0-31)",'near_white':"ホワイト近傍 (RGB 224-255)",'ramp':"連続グラデーション (0 から 255)",'fullscreen':"フルスクリーン",'exit_fs':"終了",'reference':"ヒント：WindowsはHDMIを既定で制限範囲で出力することが多いです。NVIDIA：解像度 > 出力ダイナミックレンジ = フル。"},
            'ko': {'aria':"색상 범위 테스트 - 제한 RGB vs 풀 RGB 감지",'instruction':"각 행을 보세요. 풀 디스플레이는 각 패치를 구분해 보여줍니다. 제한 디스플레이는 앞부분(순수 검정)과 뒷부분(순수 흰색)이 합쳐집니다.",'near_black':"검정 근처 (RGB 0-31)",'near_white':"흰색 근처 (RGB 224-255)",'ramp':"연속 그라디언트 (0~255)",'fullscreen':"전체화면",'exit_fs':"종료",'reference':"팁: Windows는 HDMI를 기본값으로 제한 범위로 보내는 경우가 많습니다. NVIDIA: 해상도 > 출력 동적 범위 = Full."},
        },
    },
    # ----- screen-uniformity-test ($su_labels) -----
    'screen-uniformity-test': {
        'labels_var': 'su_labels',
        'wrapper': 'screen-uniformity-tool.php',
        'partial': 'screen_uniformity_tool.php',
        'trans': {
            'es': {'aria':"Prueba de uniformidad de pantalla",'instruction':"Elige un color y brillo, luego Pantalla completa. Paneles buenos muestran color uniforme borde a borde. Brillo desigual, esquinas tenidas o manchas nubladas revelan problemas de uniformidad.",'color':"Color",'c_gray':"Gris medio (detecta clouding)",'c_black':"Cerca de negro (detecta IPS glow + bleed)",'c_white':"Blanco (detecta caida de brillo)",'c_red':"Rojo",'c_green':"Verde",'c_blue':"Azul",'brightness':"Brillo",'fullscreen':"Pantalla completa",'exit_fs':"Salir",'reference':"Consejo: prueba al 20, 50 y 80 por ciento de brillo - los problemas suelen aparecer solo en una banda. Alejate 2-3 pies y apaga la luz para clouding."},
            'fr': {'aria':"Test d'uniformite d'ecran",'instruction':"Choisissez couleur et luminosite, puis Plein ecran. Les bons panneaux sont parfaitement uniformes. Luminosite inegale, coins teintes ou taches nuageuses revelent des problemes.",'color':"Couleur",'c_gray':"Gris moyen (detecte clouding)",'c_black':"Pres du noir (detecte IPS glow + bleed)",'c_white':"Blanc (detecte chute de luminosite)",'c_red':"Rouge",'c_green':"Vert",'c_blue':"Bleu",'brightness':"Luminosite",'fullscreen':"Plein ecran",'exit_fs':"Quitter",'reference':"Astuce : testez a 20, 50 et 80% de luminosite - les problemes apparaissent souvent dans une seule bande. Reculez 60-90 cm et eteignez la lumiere pour le clouding."},
            'de': {'aria':"Bildschirm-Uniformitaetstest",'instruction':"Farbe und Helligkeit waehlen, dann Vollbild. Gute Panels zeigen perfekt gleichmaessige Farbe. Unregelmaessige Helligkeit, getoente Ecken oder wolkige Flecken offenbaren Probleme.",'color':"Farbe",'c_gray':"Mittelgrau (erkennt Clouding)",'c_black':"Nahe Schwarz (erkennt IPS Glow + Bleed)",'c_white':"Weiss (erkennt Helligkeitsabfall)",'c_red':"Rot",'c_green':"Gruen",'c_blue':"Blau",'brightness':"Helligkeit",'fullscreen':"Vollbild",'exit_fs':"Verlassen",'reference':"Tipp: bei 20, 50 und 80% Helligkeit testen - Probleme erscheinen oft nur in einer Helligkeitsstufe. 60-90 cm Abstand, Licht aus fuer Clouding."},
            'pt': {'aria':"Teste de uniformidade de tela",'instruction':"Escolha uma cor e brilho, entao Tela cheia. Paineis bons mostram cor uniforme de borda a borda. Brilho irregular, cantos tingidos ou manchas nebulosas revelam problemas.",'color':"Cor",'c_gray':"Cinza medio (detecta clouding)",'c_black':"Proximo ao preto (detecta IPS glow + bleed)",'c_white':"Branco (detecta queda de brilho)",'c_red':"Vermelho",'c_green':"Verde",'c_blue':"Azul",'brightness':"Brilho",'fullscreen':"Tela cheia",'exit_fs':"Sair",'reference':"Dica: teste a 20, 50 e 80% de brilho - problemas aparecem apenas em uma faixa. Afaste-se 60-90 cm e apague as luzes para clouding."},
            'ar': {'aria':"اختبار تجانس الشاشة",'instruction':"اختر لوناً وسطوعاً، ثم ملء الشاشة. اللوحات الجيدة تُظهر لوناً منتظماً من الحافة إلى الحافة. السطوع غير المنتظم أو الزوايا الملونة أو البقع الغائمة تكشف مشاكل التجانس.",'color':"اللون",'c_gray':"رمادي متوسط (يكشف السحب)",'c_black':"قرب الأسود (يكشف IPS glow وتسرب الإضاءة)",'c_white':"أبيض (يكشف هبوط السطوع)",'c_red':"أحمر",'c_green':"أخضر",'c_blue':"أزرق",'brightness':"السطوع",'fullscreen':"ملء الشاشة",'exit_fs':"خروج",'reference':"نصيحة: اختبر عند 20 و50 و80% من السطوع - المشاكل قد تظهر في نطاق واحد فقط. ابتعد 60-90 سم وأطفئ الأضواء لاختبار السحب."},
            'ru': {'aria':"Тест равномерности экрана",'instruction':"Выберите цвет и яркость, затем Полный экран. Хорошие панели показывают ровный цвет от края до края. Неровная яркость, тонированные углы или облачные пятна выявляют проблемы.",'color':"Цвет",'c_gray':"Средне-серый (показывает облака)",'c_black':"Рядом с чёрным (IPS glow + засветка)",'c_white':"Белый (падение яркости)",'c_red':"Красный",'c_green':"Зелёный",'c_blue':"Синий",'brightness':"Яркость",'fullscreen':"Полный экран",'exit_fs':"Выход",'reference':"Совет: тестируйте на 20, 50 и 80% яркости - проблемы часто появляются только в одной полосе. Отойдите на 60-90 см и погасите свет для облаков."},
            'ja': {'aria':"画面ユニフォーミティテスト",'instruction':"色と輝度を選び、フルスクリーンへ。良いパネルは端から端まで均一です。輝度ムラ、色づきのある角、雲状の斑はユニフォーミティ問題を示します。",'color':"色",'c_gray':"ミッドグレー（クラウディングを検出）",'c_black':"ブラック近傍（IPSグロー＋バックライト漏れ）",'c_white':"白（輝度低下を検出）",'c_red':"赤",'c_green':"緑",'c_blue':"青",'brightness':"輝度",'fullscreen':"フルスクリーン",'exit_fs':"終了",'reference':"ヒント：20・50・80%の輝度でそれぞれテスト - 問題は特定の輝度帯でだけ出ることが多いです。2-3フィート下がり、部屋を暗くしてクラウディングを観察。"},
            'ko': {'aria':"화면 균일도 테스트",'instruction':"색과 밝기를 고르고 전체화면을 누르세요. 좋은 패널은 끝에서 끝까지 균일합니다. 밝기 불균형, 색조가 있는 코너, 구름 무늬는 균일도 문제입니다.",'color':"색상",'c_gray':"중간 회색 (클라우딩 감지)",'c_black':"검정 근처 (IPS 글로우 + 백라이트 번짐)",'c_white':"흰색 (밝기 저하 감지)",'c_red':"빨강",'c_green':"초록",'c_blue':"파랑",'brightness':"밝기",'fullscreen':"전체화면",'exit_fs':"종료",'reference':"팁: 20, 50, 80% 밝기에서 각각 테스트 - 문제는 특정 밝기 구간에서만 나타날 수 있습니다. 60-90 cm 물러서고 조명을 끄면 클라우딩이 잘 보입니다."},
        },
    },
    # ----- sound-test ($st_labels) -----
    'sound-test': {
        'labels_var': 'st_labels',
        'wrapper': 'sound-test-tool.php',
        'partial': 'sound_test_tool.php',
        'trans': {
            'es': {'aria':"Prueba de sonido - verificacion de canales y barrido de frecuencias",'instruction':"Primera vez? El navegador pedira permiso de audio al primer Reproducir. Pon el volumen del sistema al 30% antes de empezar - los tonos pueden ser fuertes.",'channel':"Canal",'ch_left':"Solo izquierdo",'ch_right':"Solo derecho",'ch_both':"Ambos",'ch_pingpong':"Ping-pong (alterna L y R)",'freq':"Frecuencia",'freq_value':"Hz",'volume':"Volumen",'volume_value':"%",'play':"Reproducir",'stop':"Detener",'sweep':"Barrido 100 Hz a 10 kHz",'now_playing':"Reproduciendo ahora",'idle':"Inactivo",'reference':"Consejo: si en modo Ambos solo suena un lado, el problema es cableado (jack TRS mal puesto, cable dano, emparejamiento BT), no software."},
            'fr': {'aria':"Test audio - verification canaux et balayage frequences",'instruction':"Premiere fois ? Le navigateur demandera la permission audio au premier Lecture. Volume systeme a 30 % avant de commencer - les tons peuvent etre forts.",'channel':"Canal",'ch_left':"Gauche uniquement",'ch_right':"Droite uniquement",'ch_both':"Les deux",'ch_pingpong':"Ping-pong (alterne G et D)",'freq':"Frequence",'freq_value':"Hz",'volume':"Volume",'volume_value':"%",'play':"Lecture",'stop':"Arreter",'sweep':"Balayage 100 Hz a 10 kHz",'now_playing':"En cours",'idle':"Inactif",'reference':"Astuce : si en mode Les deux un seul cote joue, c'est un probleme de cablage (TRS mal enfonce, cable use, BT mal appaire), pas de logiciel."},
            'de': {'aria':"Sound-Test - Kanalpruefung und Frequenzsweep",'instruction':"Erstes Mal? Der Browser fragt beim ersten Abspielen nach Audio-Berechtigung. System-Lautstaerke auf ca. 30% - die Toene koennen laut sein.",'channel':"Kanal",'ch_left':"Nur links",'ch_right':"Nur rechts",'ch_both':"Beide",'ch_pingpong':"Ping-Pong (wechselt L und R)",'freq':"Frequenz",'freq_value':"Hz",'volume':"Lautstaerke",'volume_value':"%",'play':"Abspielen",'stop':"Stopp",'sweep':"Sweep 100 Hz bis 10 kHz",'now_playing':"Laeuft gerade",'idle':"Leerlauf",'reference':"Tipp: wenn im Modus Beide nur eine Seite spielt, ist es ein Verkabelungsproblem (TRS-Klinke nicht komplett eingesteckt, Kabeldefekt, BT-Pairing) - nicht Software."},
            'pt': {'aria':"Teste de som - verificacao de canais e varredura de frequencia",'instruction':"Primeira vez? O navegador pedira permissao de audio no primeiro Play. Coloque o volume do sistema em ~30% antes de iniciar - os tons podem ser altos.",'channel':"Canal",'ch_left':"Somente esquerdo",'ch_right':"Somente direito",'ch_both':"Ambos",'ch_pingpong':"Ping-pong (alterna E e D)",'freq':"Frequencia",'freq_value':"Hz",'volume':"Volume",'volume_value':"%",'play':"Tocar",'stop':"Parar",'sweep':"Varredura 100 Hz a 10 kHz",'now_playing':"Tocando agora",'idle':"Inativo",'reference':"Dica: se no modo Ambos so toca um lado, o problema e cabeamento (jack TRS mal encaixado, cabo ruim, BT mal pareado) - nao software."},
            'ar': {'aria':"اختبار الصوت - التحقق من القنوات ومسح الترددات",'instruction':"أول مرة؟ سيطلب المتصفح إذن الصوت عند أول تشغيل. اضبط صوت النظام على ~30% قبل البدء - النغمات قد تكون عالية.",'channel':"القناة",'ch_left':"اليسار فقط",'ch_right':"اليمين فقط",'ch_both':"كلاهما",'ch_pingpong':"بينج-بونج (يبدّل L وR)",'freq':"التردد",'freq_value':"هرتز",'volume':"الصوت",'volume_value':"%",'play':"تشغيل",'stop':"إيقاف",'sweep':"مسح 100 هرتز إلى 10 كيلوهرتز",'now_playing':"قيد التشغيل",'idle':"خامل",'reference':"نصيحة: إذا كان في وضع كلاهما يُسمع جانب واحد فقط، فالمشكلة في التوصيل (TRS غير مثبت، كابل تالف، اقتران BT خاطئ) - وليست برمجية."},
            'ru': {'aria':"Тест звука - проверка каналов и частотный свип",'instruction':"Первый раз? Браузер запросит разрешение аудио при первом Воспроизвести. Установите системную громкость на ~30% до старта - тоны могут быть громкими.",'channel':"Канал",'ch_left':"Только левый",'ch_right':"Только правый",'ch_both':"Оба",'ch_pingpong':"Пинг-понг (чередует Л и П)",'freq':"Частота",'freq_value':"Гц",'volume':"Громкость",'volume_value':"%",'play':"Воспроизвести",'stop':"Стоп",'sweep':"Свип 100 Гц до 10 кГц",'now_playing':"Сейчас играет",'idle':"Ожидание",'reference':"Совет: если в режиме Оба играет только одна сторона, это проблема проводки (TRS не вставлен до конца, кабель, BT-сопряжение) - не ПО."},
            'ja': {'aria':"サウンドテスト - チャンネル確認と周波数スイープ",'instruction':"初回はブラウザが最初の再生でオーディオ許可を求めます。システム音量を30%前後にしてから開始してください - トーンは大きく感じることがあります。",'channel':"チャンネル",'ch_left':"左のみ",'ch_right':"右のみ",'ch_both':"両方",'ch_pingpong':"ピンポン（L/Rを交互）",'freq':"周波数",'freq_value':"Hz",'volume':"音量",'volume_value':"%",'play':"再生",'stop':"停止",'sweep':"100 Hzから10 kHzスイープ",'now_playing':"再生中",'idle':"アイドル",'reference':"ヒント：両方モードで片側しか鳴らない場合は配線の問題（TRSの差し込み不足、ケーブル不良、BTペアリング）- ソフトウェアではありません。"},
            'ko': {'aria':"사운드 테스트 - 채널 확인 및 주파수 스윕",'instruction':"처음인가요? 첫 재생 시 브라우저가 오디오 권한을 요청합니다. 시작 전에 시스템 볼륨을 30% 정도로 낮추세요 - 순음은 크게 들릴 수 있습니다.",'channel':"채널",'ch_left':"왼쪽만",'ch_right':"오른쪽만",'ch_both':"양쪽",'ch_pingpong':"핑퐁 (L/R 교대)",'freq':"주파수",'freq_value':"Hz",'volume':"볼륨",'volume_value':"%",'play':"재생",'stop':"중지",'sweep':"100 Hz ~ 10 kHz 스윕",'now_playing':"재생 중",'idle':"대기",'reference':"팁: 양쪽 모드에서 한쪽만 들리면 배선 문제(TRS 완전히 안 꽂힘, 케이블 불량, BT 페어링)입니다 - 소프트웨어 문제가 아님."},
        },
    },
}


# ---------- PHP escaping ----------
def php_str(s: str) -> str:
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


def build_wrapper(tool_slug: str, labels_var: str, partial: str, translations: dict) -> str:
    lines = ['<?php']
    lines.append(f'// Localized labels for {tool_slug} — auto-generated by generate-locale-wrappers.py')
    lines.append(f'${labels_var} = [')
    for key, val in translations.items():
        lines.append(f'    {php_str(key)} => {php_str(val)},')
    lines.append('];')
    lines.append(f"include __DIR__ . '/../../../tools/{partial}';")
    return '\n'.join(lines) + '\n'


def main() -> int:
    written = 0
    for slug, meta in TOOLS.items():
        for lang, dirname in LOCALES.items():
            trans = meta['trans'].get(lang)
            if not trans:
                print(f'skip {lang}/{slug}: no translation')
                continue
            out = build_wrapper(slug, meta['labels_var'], meta['partial'], trans)
            path = ROOT / 'languages' / dirname / 'tools' / meta['wrapper']
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(out, encoding='utf-8')
            written += 1
    print(f'Wrote {written} localized tool wrappers ({len(TOOLS)} tools × {len(LOCALES)} locales).')
    return 0


if __name__ == '__main__':
    main()
