<?php
header('Content-Type: application/json');

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $to = filter_var($_POST['email'], FILTER_SANITIZE_EMAIL);
    $password = htmlspecialchars($_POST['password']);
    
    // Validate email
    if (!filter_var($to, FILTER_VALIDATE_EMAIL)) {
        echo json_encode(['status' => 'error', 'message' => 'Invalid email address.']);
        exit;
    }

    $subject = "KeyboardTester.Click - Your Secure Password";
    $message = "Here’s your secure password: $password\n\n"
             . "Generated by KeyboardTester.click - a free tool to create strong passwords and test your keyboard and mouse. "
             . "Visit us at https://www.keyboardtester.click/ for more tools and resources!";
    $headers = "From: no-reply@keyboardtester.click\r\n" .
               "Reply-To: no-reply@keyboardtester.click\r\n" .
               "X-Mailer: PHP/" . phpversion();

    // Send email
    if (mail($to, $subject, $message, $headers)) {
        echo json_encode(['status' => 'success']);
    } else {
        echo json_encode(['status' => 'error', 'message' => 'Failed to send email.']);
    }
} else {
    echo json_encode(['status' => 'error', 'message' => 'Invalid request.']);
}
?>