<?php
/**
 * French localized landing page for color-range-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-fr.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Test de Plage de Couleur - RGB Complet vs Limité';
$pageDescription = 'Test de plage de couleur : détecte Full RGB (0-255) vs Limited (16-235) avec grilles de patchs proches du noir et du blanc. Corrige l\'écrêtage des ombres et hautes lumières.';
?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('color-range-test.php'); ?>">
  <link rel="alternate" hreflang="fr" href="<?php echo absoluteUrl('languages/french/color-range-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('color-range-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-fr.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnostic écran</p>
          <h1 class="hero-title">Test de Plage de Couleur</h1>
          <p class="hero-lede">Les écrans RGB complet montrent chaque patch distinct. Les écrans en plage limitée écrasent les patches les plus sombres et les plus clairs en noir et blanc purs.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#color-range-test">Lancer le test</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Voir tous les outils</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="color-range-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Diagnostic écran</p>
          <h2>Test de Plage de Couleur</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/color-range-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-fr.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
