<?php
/**
 * french localized landing page for gamertag-generator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-fr.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Générateur de Gamertag - Pseudos aléatoires Xbox, PSN, Steam';
$pageDescription = 'Générez 10 pseudos gamer aléatoires en 6 styles (edgy, funny, cute, pro, fantasy, cyber) avec limites Xbox, PSN, Steam et Discord.';
?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('gamertag-generator.php'); ?>">
  <link rel="alternate" hreflang="fr" href="<?php echo absoluteUrl('languages/french/gamertag-generator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('gamertag-generator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('gamertag_generator', [['name'=>'Home','url'=>'/'],['name'=>'Générateur de Gamertag','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-fr.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Utilitaire gaming</p>
          <h1 class="hero-title">Générateur de Gamertag</h1>
          <p class="hero-lede">Génère 10 pseudos aléatoires en 6 styles (edgy, funny, cute, pro, fantasy, cyber). Copiez en un clic, enregistrez vos favoris et limitez la longueur pour Xbox/PSN/Steam/Discord.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#gamertag-generator">Générer des noms</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Voir tous les outils</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/gamertag-generator/hero.jpg'); ?>" width="1200" height="800" alt="Générateur de Gamertag" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="gamertag-generator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Outil principal</p>
          <h2>Générateur de Gamertag</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/gamertag_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'gamertag-generator'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-fr.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
