<?php
/**
 * french localized landing page for guild-name-generator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-fr.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Générateur de noms de guilde - Noms de clan MMO';
$pageDescription = 'Générateur de noms de guilde et clan MMO en 6 thèmes et 5 modèles, avec limites WoW, FFXIV, Destiny et Discord.';
?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('guild-name-generator.php'); ?>">
  <link rel="alternate" hreflang="fr" href="<?php echo absoluteUrl('languages/french/guild-name-generator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('guild-name-generator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('guild_name_generator', [['name'=>'Home','url'=>'/'],['name'=>'Générateur de noms de guilde','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-fr.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Utilitaire gaming</p>
          <h1 class="hero-title">Générateur de noms de guilde</h1>
          <p class="hero-lede">Génère 10 noms de guilde aléatoires en 6 thèmes (fantasy, sci-fi, sombre, noble, rogue, mythique) avec des modèles comme "Ordre de X", "Maison X", "Les X". Copie en un clic et favoris sauvegardés.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#guild-name-generator">Générer des noms</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Voir tous les outils</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/guild-name-generator/hero.jpg'); ?>" width="1200" height="800" alt="Générateur de noms de guilde" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="guild-name-generator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Outil principal</p>
          <h2>Générateur de noms de guilde</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/guild_name_generator_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/guild-name-generator.php'; ?>
    <?php $currentTool = 'mouse'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/guild-name-generator.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-fr.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
