<?php
/**
 * French localized landing page for mouse-spin-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-fr.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Test de Rotation Souris - Compteur 360°';
$pageDescription = 'Test de rotation de souris : compte les rotations complètes à 360° en sessions de 15, 30 ou 60 secondes avec détection du pic de tours par seconde. Sans installation, en direct.';
?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('mouse-spin-test.php'); ?>">
  <link rel="alternate" hreflang="fr" href="<?php echo absoluteUrl('languages/french/mouse-spin-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('mouse-spin-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-fr.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnostic souris</p>
          <h1 class="hero-title">Test de Rotation Souris</h1>
          <p class="hero-lede">Combien de rotations complètes à 360° pouvez-vous faire en 30 secondes ? Maintenez et tournez autour du centre du pad.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#mouse-spin-test">Commencer à tourner</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Voir tous les outils</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="mouse-spin-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Diagnostic souris</p>
          <h2>Test de Rotation Souris</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/mouse-spin-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-fr.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
