<?php
/**
 * french localized landing page for pitch-detector
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-fr.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Detecteur de Hauteur en Ligne - Quelle Note Je Chante ?';
$pageDescription = 'Detecteur de hauteur gratuit en ligne. Chantez ou jouez dans le microphone pour voir la frequence en Hz, la note la plus proche (C0-C8), l octave et les cents en direct.';
?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('pitch-detector.php'); ?>">
  <link rel="alternate" hreflang="fr" href="<?php echo absoluteUrl('languages/french/pitch-detector.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('pitch-detector.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('pitch_detector', [['name'=>'Home','url'=>'/'],['name'=>'Detecteur de Hauteur en Ligne - Quelle Note Est-Ce Que Je Chante ?','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-fr.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnostic audio</p>
          <h1 class="hero-title">Detecteur de Hauteur en Ligne - Quelle Note Est-Ce Que Je Chante ?</h1>
          <p class="hero-lede">Chantez, fredonnez ou jouez n importe quelle note pour voir instantanement la frequence, la note musicale et les cents. Graphique defilant des 10 dernieres secondes.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#pitch-detector">Lancer le detecteur</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Voir tous les outils</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/pitch-detector/hero.jpg'); ?>" width="1200" height="800" alt="Detecteur de Hauteur en Ligne - Quelle Note Est-Ce Que Je Chante ?" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="pitch-detector">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Outil principal</p>
          <h2>Detecteur de Hauteur</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/pitch_detector_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'pitch-detector'; $localizedRelatedCategory = 'audio'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-fr.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
