<?php
/**
 * French localized landing page for resolution-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-fr.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Test de Résolution d\'Écran - Résolution, DPR, Profondeur';
$pageDescription = 'Test de résolution d\'écran : lecture en direct de résolution, pixels natifs, DPR, profondeur de couleur et gamut. Vérifiez la vraie sortie de votre écran instantanément.';
?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('resolution-test.php'); ?>">
  <link rel="alternate" hreflang="fr" href="<?php echo absoluteUrl('languages/french/resolution-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('resolution-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-fr.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnostic écran</p>
          <h1 class="hero-title">Test de Résolution d'Écran</h1>
          <p class="hero-lede">Lecture instantanée de toutes les propriétés d'écran : résolution CSS + pixels natifs, DPR, profondeur couleur, gamut, viewport, orientation, ratio d'aspect. Mise à jour au redimensionnement.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#resolution-test">Voir ma résolution</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Voir tous les outils</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="resolution-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Diagnostic écran</p>
          <h2>Test de Résolution d'Écran</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/resolution-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-fr.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
