<?php
/**
 * French localized landing page for sound-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-fr.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Test Audio - Canaux Haut-parleurs et Casques';
$pageDescription = 'Test de son gratuit : vérifie les canaux gauche/droite des haut-parleurs et casques, plus balayage de fréquence 100 Hz → 10 kHz. Sans installation, dans le navigateur.';
?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('sound-test.php'); ?>">
  <link rel="alternate" hreflang="fr" href="<?php echo absoluteUrl('languages/french/sound-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('sound-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-fr.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnostic audio</p>
          <h1 class="hero-title">Test Audio</h1>
          <p class="hero-lede">Vérifiez vos canaux gauche, droit et stéréo avec des sinus purs. Mode ping-pong pour A/B les deux haut-parleurs. Balayage 100 Hz → 10 kHz pour la plage de fréquence.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#sound-test">Lancer le test audio</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Voir tous les outils</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="sound-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Diagnostic audio</p>
          <h2>Test Audio</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/sound-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-fr.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
