<?php
/**
 * French localized landing page for viewing-distance-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-fr.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Calculateur de Distance de Vision TV et Moniteur';
$pageDescription = 'Calculateur de distance de vision : distance optimale TV/moniteur selon THX (36° FoV), SMPTE (30° FoV) et la limite de résolution 4K/8K. En pieds et en mètres.';
?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('viewing-distance-calculator.php'); ?>">
  <link rel="alternate" hreflang="fr" href="<?php echo absoluteUrl('languages/french/viewing-distance-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('viewing-distance-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-fr.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Calculateurs d'écran</p>
          <h1 class="hero-title">Calculateur de Distance de Vision</h1>
          <p class="hero-lede">À quelle distance s'asseoir d'une TV ou d'un moniteur ? THX (36° FoV immersif), SMPTE (30° cinéma), et la distance maximale de résolution 4K/8K.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#viewing-distance-calculator">Ouvrir le calculateur</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Voir tous les outils</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="viewing-distance-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Calculateurs d'écran</p>
          <h2>Calculateur de Distance de Vision</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/viewing-distance-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-fr.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
