<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>Auditory Reaction Time Test Guide</h2><p>How the test works and what your score means.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>How to run the test</h3><ol><li>Put on <strong>wired headphones</strong> if you have them (Bluetooth adds 40-200&nbsp;ms of latency).</li><li>Click the black stage to start. Do <strong>not</strong> click until you hear the beep.</li><li>When you hear the tone, click immediately (or press Space).</li><li>Repeat for 5 rounds. Avg / best / worst update after each round.</li><li>If you click before the beep, the round resets as a false start.</li></ol></div>
    <div class="help-card"><h3>What counts as a good score</h3><ul><li><strong>140-180 ms</strong>: very fast, comparable to trained e-sports pros.</li><li><strong>180-220 ms</strong>: above average for healthy adults.</li><li><strong>220-280 ms</strong>: average range for most people.</li><li><strong>300+ ms</strong>: slower than typical &mdash; check for fatigue, sleep deprivation, or wireless audio latency.</li><li>Auditory reaction time is <em>faster than visual</em> by 20-40&nbsp;ms on average because the brainstem processes sound faster than the retina processes light.</li></ul></div>
    <div class="help-card"><h3>Why headphones matter</h3><ul><li>Your device-to-ear audio path adds latency between the timer and your ears.</li><li><strong>Wired 3.5mm</strong>: under 10&nbsp;ms.</li><li><strong>USB-C wired</strong>: 10-30&nbsp;ms.</li><li><strong>Bluetooth (SBC/AAC)</strong>: 150-250&nbsp;ms &mdash; adds a huge systematic error.</li><li><strong>Bluetooth (aptX LL / LC3)</strong>: 40-80&nbsp;ms &mdash; still measurable.</li><li>For cross-run consistency, stick with one output device.</li></ul></div>
    <div class="help-card"><h3>Troubleshooting</h3><ul><li><strong>No sound:</strong> some browsers require a click before audio plays. Click the stage first.</li><li><strong>Results all around 250&nbsp;ms:</strong> you are on Bluetooth &mdash; switch to wired to measure real reflex.</li><li><strong>Getting false starts:</strong> the delay is randomized 1.5-4&nbsp;s specifically to prevent rhythm prediction.</li><li><strong>iPhone / iPad:</strong> unmute the silent switch and turn the volume up; otherwise the beep will not play.</li></ul></div>
  </div>
</section>
