<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>CPU Stress Test Guide</h2><p>How to run it, what the numbers mean, and what to watch for.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>How to run the test</h3><ol><li>The thread count defaults to your <em>logical core count</em> (physical cores &times; SMT/hyperthreading multiplier).</li><li>Pick a duration. 20&nbsp;s is enough to see instantaneous throughput; 2&nbsp;min is enough to see thermal throttle on laptops.</li><li>Close other heavy tabs and apps so the numbers reflect your hardware, not tab contention.</li><li>Click <strong>Start stress</strong>. Fans will spin up quickly.</li><li>Watch the per-thread bars &mdash; if some threads drop to half-speed midway, that is thermal or power throttling.</li></ol></div>
    <div class="help-card"><h3>What the numbers mean</h3><ul><li><strong>Total ops/sec:</strong> combined SHA-256 hashes per second across all threads. A modern desktop hits 200,000+; a thin-and-light laptop may hit 40,000-80,000.</li><li><strong>Avg per thread:</strong> a quick way to spot throttling &mdash; if per-thread drops while thread count stays flat, you are throttling.</li><li><strong>Peak ops/sec:</strong> sticks at your best moment. The gap between peak and current shows sustained-vs-burst performance.</li><li>Numbers are not directly comparable across browsers &mdash; Chrome's SubtleCrypto is faster than Firefox's in most builds.</li></ul></div>
    <div class="help-card"><h3>What to watch for</h3><ul><li><strong>Laptop throttle:</strong> full-speed for 20-40&nbsp;s, then a cliff drop to 50-70% for the rest of the run.</li><li><strong>Battery throttle:</strong> unplug a laptop and run again &mdash; many drop 30% immediately.</li><li><strong>One slow thread:</strong> indicates a "little" / efficiency core on hybrid CPUs (Intel E-cores, Apple Silicon efficiency cores). They are running at half the speed of "big" cores by design.</li><li><strong>Background music or calls stuttering:</strong> expected during max CPU load.</li></ul></div>
    <div class="help-card"><h3>Safety notes</h3><ul><li>Stress-testing is safe on stock hardware &mdash; modern CPUs will throttle before damage.</li><li>If your laptop goes silent (fans off) and the OS appears to freeze, let it recover naturally; thermal shutdown is a safety feature.</li><li>Desktop enthusiasts with manual overclocks should limit runs to 5-10 minutes until cooling is verified.</li><li>Phones: limit to 30-60&nbsp;s. Phone SoCs throttle aggressively but can still get hot to the touch.</li></ul></div>
  </div>
</section>
