<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>Download Time Calculator Guide</h2><p>Why three different numbers, and which one to trust.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>The three numbers</h3><ul><li><strong>Realistic (85% efficient):</strong> what you should actually plan around. Accounts for TCP/IP overhead and typical CDN throughput.</li><li><strong>Theoretical (100%):</strong> the best-case math, treating the link as perfectly efficient. You will rarely hit this.</li><li><strong>Slow path (60%):</strong> what congested Wi-Fi or a busy evening Internet peak looks like. Use this as a worst-case.</li><li>The three numbers bracket the real-world range. If your download falls outside 60-85%, something else is wrong.</li></ul></div>
    <div class="help-card"><h3>File size presets</h3><ul><li><strong>AAA game (Call of Duty):</strong> 200&nbsp;GB is now realistic for titles with multiple campaigns, HD textures, and DLC.</li><li><strong>AAA game (standard):</strong> 100&nbsp;GB is typical for new releases.</li><li><strong>4K HDR Blu-ray rip:</strong> 75&nbsp;GB (uncompressed or lightly compressed).</li><li><strong>4K streaming:</strong> 25&nbsp;GB (more compressed, lower bitrate).</li><li><strong>Linux ISO:</strong> 4&nbsp;GB (Ubuntu, Fedora desktop).</li><li>Click any preset to load its size.</li></ul></div>
    <div class="help-card"><h3>Why downloads vary so much</h3><ul><li><strong>CDN proximity:</strong> if the file is served from a POP 5&nbsp;ms from you, you get line rate. If it's 80&nbsp;ms away, expect 60-70%.</li><li><strong>Server upload cap:</strong> free file hosts and small game mirrors often cap per-connection at 5-20&nbsp;MB/s.</li><li><strong>Wi-Fi vs wired:</strong> even Wi-Fi 6 averages 60-70% of wired throughput under load.</li><li><strong>Evening congestion:</strong> ISPs oversubscribe, peak hours (7-11 PM) can be 30-50% slower than 3 AM.</li><li><strong>Steam / Epic / Battle.net:</strong> throttle per-client to not saturate your link &mdash; check client settings for a manual cap.</li></ul></div>
    <div class="help-card"><h3>Tips to speed up actual downloads</h3><ul><li><strong>Wired Ethernet:</strong> nearly always faster than Wi-Fi on the same link.</li><li><strong>Pause other devices:</strong> streaming 4K on another device takes ~25&nbsp;Mbps of your link.</li><li><strong>Steam region:</strong> switch download region manually if the default is congested.</li><li><strong>DNS:</strong> 1.1.1.1 or 8.8.8.8 can resolve CDN endpoints closer than your ISP default.</li><li><strong>VPN:</strong> almost always slows downloads 20-40%. Turn off unless needed.</li></ul></div>
  </div>
</section>
