<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>Frame Skipping Test Guide</h2><p>How to run the test and interpret the stutter log.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>How to run the test</h3><ol><li>Close other heavy browser tabs to isolate the test.</li><li>Click <strong>Start test</strong>. The first ~1 second calibrates the expected refresh interval.</li><li>Watch the moving bar for hitching (visual confirmation of skipped frames).</li><li>Let the test run the full 15&nbsp;s duration for a stable result.</li><li>Check the stutter log to see exactly when skips happened.</li></ol></div>
    <div class="help-card"><h3>What "skipped frames" means</h3><ul><li>If your refresh is 60&nbsp;Hz, each frame should take 16.67&nbsp;ms.</li><li>A frame that takes 33&nbsp;ms = 1 skipped frame (2 refresh intervals).</li><li>A frame that takes 50&nbsp;ms = 2 skipped frames (3 refresh intervals).</li><li>At 144&nbsp;Hz, expected = 6.94&nbsp;ms, and any frame over ~10.4&nbsp;ms counts (1.5x threshold).</li><li>Lower the threshold to catch smaller jitter; raise it to only flag large hitches.</li></ul></div>
    <div class="help-card"><h3>What to expect</h3><ul><li><strong>0 skipped:</strong> perfect. Your browser is keeping up.</li><li><strong>1-3 skipped in 15&nbsp;s:</strong> normal. Browser GC or background process stole a frame or two.</li><li><strong>10+ skipped:</strong> something is competing for GPU or main thread. Check extensions, tab count, or thermal throttling.</li><li><strong>Regular stutter every 1-2 seconds:</strong> hardware acceleration may be off, or a browser extension is hooking into frames.</li></ul></div>
    <div class="help-card"><h3>Troubleshooting</h3><ul><li><strong>Detected Hz way off:</strong> battery saver may be throttling rAF; unplug/plug or check power profile.</li><li><strong>Huge jitter on Firefox:</strong> check <code>about:config</code> for <code>privacy.resistFingerprinting</code> &mdash; it rounds timestamps.</li><li><strong>Background tab test:</strong> browsers throttle rAF in hidden tabs; keep this tab focused.</li><li><strong>Laptops on battery:</strong> GPU downclocks can cause skips that disappear when plugged in.</li></ul></div>
  </div>
</section>
