<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>GPU Stress Test Guide</h2><p>How to push the shader, what to look for, and when to stop.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>How to run the test</h3><ol><li>Default settings (1500 iterations, 1x resolution) will load most mid-range GPUs to 60-144&nbsp;fps.</li><li>Click <strong>Start stress</strong>. The canvas renders a Mandelbrot set every frame.</li><li>Raise iterations until FPS drops below your refresh rate &mdash; that is the point where your GPU becomes the bottleneck.</li><li>Raise resolution for supersampling (2x = 4x pixels rendered).</li><li>Let it run 60-120&nbsp;seconds to catch thermal throttling.</li></ol></div>
    <div class="help-card"><h3>What to watch for</h3><ul><li><strong>Steady FPS:</strong> GPU has headroom, your panel refresh rate is the cap.</li><li><strong>FPS drops mid-run:</strong> thermal throttle (GPU clock drops to prevent overheat).</li><li><strong>Very low FPS at 1500 iterations:</strong> you are on integrated graphics or WebGL is software-rendering.</li><li><strong>Renderer shows SwiftShader / llvmpipe:</strong> hardware acceleration is disabled in your browser. Results are CPU-bound, not a real GPU test.</li><li><strong>GPU vendor hidden:</strong> Chrome strips <code>WEBGL_debug_renderer_info</code> for privacy unless the extension is re-enabled.</li></ul></div>
    <div class="help-card"><h3>What iterations mean</h3><ul><li>Each pixel on the canvas runs up to <em>iterations</em> Mandelbrot iterations before bailing out.</li><li>1000 iterations &asymp; light load &mdash; any modern GPU holds refresh rate.</li><li>2500 iterations &asymp; stresses mid-range discrete GPUs (GTX 1060, RTX 2060).</li><li>4000+ iterations &asymp; stresses high-end GPUs (RTX 3080 class).</li><li>Integrated GPUs (Intel UHD, older AMD APUs) will drop to 10-20&nbsp;fps at 1500+.</li></ul></div>
    <div class="help-card"><h3>Safety notes</h3><ul><li>GPUs will throttle before damage &mdash; this test is safe on stock hardware.</li><li>If the browser crashes, reload. No state is saved mid-test.</li><li>Watch laptop case temperature. If uncomfortably hot, stop and let it cool.</li><li>Phones throttle hard within 30-60&nbsp;s &mdash; expect dramatic FPS drops.</li><li>Desktop overclockers: this is a good artifact and stability check for GPU overclocks.</li></ul></div>
  </div>
</section>
