<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>Guild Name Generator Guide</h2><p>How to pick a guild name that raiders remember and name checkers approve.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>Step 1: pick a theme</h3><ol><li><strong>Fantasy</strong>: dragons, runes, emerald forests &mdash; WoW, FFXIV, Lost Ark.</li><li><strong>Sci-fi</strong>: orbital legions, nebula corsairs &mdash; Destiny 2, Eve Online, Star Citizen.</li><li><strong>Dark / evil</strong>: shadow covenants, cursed orders &mdash; antagonist roleplay.</li><li><strong>Noble / heroic</strong>: paladins, lions, radiant orders &mdash; Alliance, light-aligned factions.</li><li><strong>Rogue / outlaw</strong>: thieves, smugglers, crews &mdash; pirate / bandit fiction.</li><li><strong>Mythic / legendary</strong>: titans, ascendants, godhood &mdash; end-game elitist aesthetic.</li></ol></div>
    <div class="help-card"><h3>Step 2: pick a template</h3><ul><li><strong>Order of the X</strong>: classic paladin / clerical vibe (<em>Order of the Phoenix</em>).</li><li><strong>House of X</strong>: ASOIAF, royal roleplay (<em>House Ravenrock</em>).</li><li><strong>The Xs</strong>: short, sharp (<em>The Silent Daggers</em>).</li><li><strong>Adjective + Noun</strong>: two-word standard (<em>Crimson Wolves</em>).</li><li><strong>X of Y</strong>: evocative (<em>Reapers of Mordor</em>).</li><li>Or choose <em>Mix it up</em> to roll across all templates.</li></ul></div>
    <div class="help-card"><h3>Step 3: match platform length limits</h3><ul><li><strong>WoW guild:</strong> 2-24 characters, letters + apostrophe + space.</li><li><strong>FFXIV Free Company:</strong> 4-20 characters, letters and digits.</li><li><strong>Destiny 2 clan:</strong> 3-32 characters, most characters allowed.</li><li><strong>Discord server:</strong> 2-100 characters, full Unicode.</li><li>Set "Max length" before generating so names fit on first try.</li></ul></div>
    <div class="help-card"><h3>Things to avoid</h3><ul><li>Trademarked IP (Stormwind, Jedi, Dark Brotherhood will be auto-flagged).</li><li>Profanity &mdash; most MMO name filters will reject and auto-rename you.</li><li>Names already used by famous raiding guilds (Method, Echo) unless roleplay tribute is intentional.</li><li>Overloaded punctuation and numbers &mdash; they look like throwaway alts.</li><li>Impossible-to-pronounce strings &mdash; raid leaders have to say it on voice chat.</li></ul></div>
  </div>
</section>
