<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>Hearing Age Test Guide</h2><p>How the test works, how to read your result, and why headphones matter at high frequencies.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>How to run the test</h3><ol><li>Put on <strong>wired headphones</strong> at low volume. Most laptop speakers cannot reproduce above 16 kHz, which will fake-fail the test.</li><li>Press <strong>Start test</strong>. You'll hear a 2-second sine tone at the first frequency (8 kHz).</li><li>Click <strong>I can hear it</strong> or <strong>I can't hear it</strong> for each step.</li><li>The lowest frequency where you click "I can't hear it" determines your hearing-age bucket.</li><li>After the 12 steps, use the <strong>manual slider</strong> to fine-tune your exact upper limit.</li></ol></div>
    <div class="help-card"><h3>Hearing age buckets</h3><ul><li><strong>22 kHz audible</strong>: under 20 - exceptional young hearing</li><li><strong>20 kHz</strong>: 20-29</li><li><strong>18 kHz</strong>: 30-39</li><li><strong>16 kHz</strong>: 40-49</li><li><strong>14 kHz</strong>: 50-59</li><li><strong>Below 12 kHz</strong>: 60+</li><li>Hearing tops out at ~20 kHz at birth and drops about 2 kHz per decade (presbycusis).</li></ul></div>
    <div class="help-card"><h3>Why headphones matter at high frequencies</h3><ul><li>Most laptop speakers and phone speakers roll off hard above <strong>14-16 kHz</strong> &mdash; the driver simply can't move fast enough.</li><li>If you "can't hear" 17 kHz on a laptop speaker, that is the speaker, not your ears.</li><li>Bluetooth headphones may also low-pass-filter to save bandwidth on SBC/AAC codecs.</li><li>For the most accurate test, use <strong>wired over-ear or in-ear</strong> headphones with a known-flat frequency response.</li></ul></div>
    <div class="help-card"><h3>Safety and accuracy</h3><ul><li>Start at <strong>20-30% system volume</strong>. High-frequency tones do not feel as loud as they actually are &mdash; that is how they damage hearing.</li><li>This is a <strong>screening tool, not a medical audiogram</strong>. A real audiologist tests at calibrated SPL in a sound booth.</li><li>If you suspect hearing loss, see an audiologist. Sudden one-sided loss is a medical emergency.</li><li>Use a quiet room. HVAC, fans, and traffic mask the highest frequencies.</li></ul></div>
  </div>
</section>
