<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>Memory Test Guide</h2><p>How the heap meter and allocator work.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>What the three numbers mean</h3><ul><li><strong>Used heap:</strong> how much the current page is actually holding &mdash; includes the DOM, JS objects, and any allocations you trigger.</li><li><strong>Total heap:</strong> how much the browser has reserved for this tab. It grows as Used grows and shrinks after GC.</li><li><strong>Heap limit:</strong> the browser's hard cap per tab. On 64-bit Chrome desktop this is typically ~2-4&nbsp;GB; on mobile browsers it is much lower.</li><li>The meter bar is Used / Limit in percent.</li></ul></div>
    <div class="help-card"><h3>Running the allocator</h3><ol><li>Pick a chunk size (10&nbsp;MB default) and interval (300&nbsp;ms default).</li><li>Click <strong>Start allocating</strong>. Every interval a fresh typed array is created and retained.</li><li>Watch the meter climb and the Used heap track allocations.</li><li>Allocation auto-stops at 85% of the heap limit to avoid crashing the tab.</li><li>Click <strong>Release &amp; GC</strong> to drop all references and trigger a cleanup. The Used heap should fall within a few seconds as the GC runs.</li></ol></div>
    <div class="help-card"><h3>Browser differences</h3><ul><li><strong>Chrome/Edge:</strong> <code>performance.memory</code> is exposed by default, all three values update live.</li><li><strong>Firefox:</strong> <code>performance.memory</code> is not shipped &mdash; the tool falls back to tracking how much the test has allocated.</li><li><strong>Safari:</strong> same as Firefox, no heap API.</li><li><strong>Mobile browsers:</strong> heap limits are aggressive (often 256-512&nbsp;MB). Allocation will hit 85% fast.</li></ul></div>
    <div class="help-card"><h3>Is this a "RAM test"?</h3><ul><li>This is a <em>browser heap</em> test, not a hardware RAM stability test. Chrome will not let a tab allocate more than its limit, regardless of how much physical RAM the system has.</li><li>For actual RAM stability testing (bad DIMMs, overclock validation), use <strong>MemTest86</strong> as a bootable USB &mdash; a browser cannot exercise memory at the hardware level.</li><li>This tool is useful for: spotting memory leaks in web apps, confirming your tab has enough room to load a big asset, comparing heap limits across browsers.</li></ul></div>
  </div>
</section>
