<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>Minecraft Circle Generator Guide</h2><p>How to use each mode and build a smooth circle in a blocky world.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>The 4 modes</h3><ul><li><strong>Outline:</strong> single-block-thick ring, best for walls of a round tower or a small decoration.</li><li><strong>Filled disc:</strong> every block inside the circle. Use for floors, roof caps, and clock faces.</li><li><strong>Thick ring:</strong> two-block-thick wall &mdash; more structural, less "stair-stepped" visual jitter.</li><li><strong>Sphere layer:</strong> a horizontal slice of a full sphere at the given offset from equator. Change offset to walk layers from bottom (-R) to top (+R).</li></ul></div>
    <div class="help-card"><h3>Building a sphere / dome</h3><ol><li>Pick your radius and switch to <strong>Sphere layer</strong> mode.</li><li>Set offset to -R (bottom layer) and build the disc.</li><li>Increment offset by 1 each time and build the next layer directly above.</li><li>For a dome (half sphere), stop at offset 0 (equator). For a full sphere, continue to +R.</li><li>Check "Sphere total" for the full block count &mdash; useful to know before you start mining.</li></ol></div>
    <div class="help-card"><h3>Choosing a radius</h3><ul><li><strong>Radius 5-8:</strong> small accent circle (fountain, decorative pillar base).</li><li><strong>Radius 10-20:</strong> typical round tower or small dome.</li><li><strong>Radius 30-50:</strong> medium dome, arena interior, Redstone clock face.</li><li><strong>Radius 60+:</strong> mega-builds, megastructures &mdash; expect thousands of blocks.</li><li>Odd-number diameters (radius 5 = 11 diameter) have a single center block; even diameters (radius 5.5 impossible &mdash; use 5 or 6) look less symmetric for small shapes.</li></ul></div>
    <div class="help-card"><h3>Tips for the cleanest build</h3><ul><li>Download the PNG and keep it on a second monitor or phone while building.</li><li>For hollow round towers, pick the outline mode and stack identical layers &mdash; the algorithm is symmetric so every layer matches.</li><li>For buildings that need both a floor and a wall, use filled disc for the floor and outline for the walls (same radius).</li><li>Use a grid resource pack or F3+G debug lines in-game to keep track of coordinates.</li></ul></div>
  </div>
</section>
