<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>Monitor Sharpness Test Guide</h2><p>How to read the patterns, what good sharpness looks like, and what to fix when it does not.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>How to run the test</h3><ol><li>Set your browser to <strong>100% zoom</strong> (Ctrl+0 / Cmd+0). Anything else changes the per-pixel mapping.</li><li>Set Windows / macOS display scaling to a <em>round</em> value (100%, 200%) and the resolution to your panel's <em>native</em> resolution.</li><li>Open the <strong>Pixel grid</strong> tab and step back roughly arm's length. Each block should look like a uniform mid-grey at distance.</li><li>Switch to <strong>Text clarity</strong> and check that 12-14&nbsp;px text is crisp, not fuzzy.</li><li>Use the <strong>Fullscreen</strong> button to evaluate any single pattern without browser chrome.</li></ol></div>
    <div class="help-card"><h3>What the patterns reveal</h3><ul><li><strong>Pixel grid (1px checker):</strong> visible banding or moire = wrong scaling, non-native resolution, or a monitor "sharpness" setting that is not at neutral.</li><li><strong>Text samples:</strong> uneven stem thickness or fuzzy edges at small sizes = sub-optimal anti-aliasing or low pixel density.</li><li><strong>Color fringing:</strong> red/blue halos along letter edges = sub-pixel rendering on a non-RGB-stripe panel (BGR, OLED PenTile).</li><li><strong>Sub-pixel ruler:</strong> the order of color stripes you see (R-G-B vs B-G-R) tells you the panel's actual sub-pixel layout.</li></ul></div>
    <div class="help-card"><h3>Common fixes</h3><ul><li><strong>Set monitor sharpness to neutral.</strong> Most monitors have a sharpness control 0-100; "0" or "5" is usually neutral, anything higher is over-sharpening that creates halos.</li><li><strong>Run native resolution.</strong> 1080p content on a 4K panel will look soft regardless of monitor settings.</li><li><strong>Avoid 125% / 150% scaling on Windows</strong> if the app does not support fractional scaling - text becomes blurry. Use 100% or 200% where possible.</li><li><strong>Enable ClearType (Windows)</strong> or font smoothing (macOS). This makes a huge difference at small sizes.</li><li><strong>Match sub-pixel order:</strong> on a BGR panel, ClearType tuned for RGB will show fringes - re-run the ClearType tuner.</li></ul></div>
    <div class="help-card"><h3>What is normal vs broken</h3><ul><li><strong>Normal:</strong> 1px grids look uniform grey, text is crisp at 12px, no obvious color halos at arm's length.</li><li><strong>Suspect:</strong> mild fringing on a 4K OLED is expected (PenTile sub-pixel) - look at it as a tradeoff, not a fault.</li><li><strong>Broken:</strong> wavy moire across a checker, banded vertical stripes, or text that is unreadable below 16px on a desktop monitor.</li><li><strong>If patterns shimmer when you scroll</strong>, that is your GPU's sub-pixel positioning, not the panel - try a different browser to confirm.</li></ul></div>
  </div>
</section>
