<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>Online Ruler Guide</h2><p>How to calibrate, how to measure, and what to do when the markings look off.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>Calibrate with a credit card</h3><ol><li>Pick up any ISO ID-1 card &mdash; credit card, debit card, or driver's license. They are all standardized at <strong>85.6&nbsp;mm x 54&nbsp;mm</strong>.</li><li>Hold the card flat against the screen on the dotted outline.</li><li>Drag the right-hand handle until the on-screen rectangle matches the real card width exactly.</li><li>Click <strong>Save calibration</strong>. The setting is stored in your browser, so the ruler is accurate next time you visit.</li></ol></div>
    <div class="help-card"><h3>Calibrate by DPI</h3><ul><li>If you already know your display's pixel density, type it into the <em>Monitor DPI</em> field or pick a common preset (96, 109, 119, 120, 144, 163, 216).</li><li>96&nbsp;DPI is the Windows default for older displays. Most modern laptops are 120-160. iPad and 4K monitors often sit near 264 or 218.</li><li>Use our <a href="<?php echo url('ppi-calculator.php'); ?>">PPI calculator</a> to compute your screen's exact density from resolution and diagonal size.</li></ul></div>
    <div class="help-card"><h3>Measure something</h3><ul><li>Hold the object flat against the screen, lined up with the zero mark on the ruler.</li><li>Switch <em>Show: cm only / inch only / both</em> as needed.</li><li>Click <em>Vertical</em> to rotate the ruler 90 degrees for taller objects.</li><li>For best accuracy, set browser zoom to 100% before calibrating &mdash; otherwise re-calibrate when you change zoom.</li></ul></div>
    <div class="help-card"><h3>Why the ruler may look wrong</h3><ul><li><strong>Browser zoom is not 100%.</strong> Press Ctrl+0 (Windows) or Cmd+0 (Mac) to reset, then recalibrate.</li><li><strong>Display scaling.</strong> Windows "150% scaling" or macOS "More Space" both lie about pixel size. Calibrate with the credit card to override.</li><li><strong>You moved to a different monitor.</strong> Each display has its own DPI &mdash; recalibrate per monitor.</li><li><strong>You're on a phone.</strong> Phone DPIs vary wildly (300-500+); always credit-card calibrate on mobile.</li></ul></div>
  </div>
</section>
