<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>Pitch Detector Guide</h2><p>How real-time pitch detection works and how to read your numbers.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>How to use the detector</h3><ol><li>Press <strong>Start</strong> and allow microphone access when the browser prompts.</li><li>Sing or play a sustained note &mdash; vowels like "ah" or "oo" work best for vocals.</li><li>Watch the live readout: note name (e.g. <em>A4</em>), frequency in Hz, octave number, and cents sharp/flat.</li><li>Use <strong>Hold peak</strong> to lock the loudest pitch from the last 2&nbsp;seconds &mdash; useful when you cannot watch the screen while singing.</li><li>Adjust the <strong>noise threshold</strong> if a noisy room is triggering false readings.</li></ol></div>
    <div class="help-card"><h3>Reading the cents value</h3><ul><li><strong>0 to &plusmn;5 cents</strong>: in tune. The human ear typically cannot distinguish anything tighter.</li><li><strong>&plusmn;5 to &plusmn;15 cents</strong>: subtle drift &mdash; trained ears notice; choirs aim for this.</li><li><strong>&plusmn;15 to &plusmn;30 cents</strong>: audibly off. Solo vocalists should re-pitch.</li><li><strong>&plusmn;30 to &plusmn;50 cents</strong>: about a quarter-tone off &mdash; listeners hear it as flat or sharp.</li><li><strong>Beyond &plusmn;50 cents</strong>: closer to the next semitone &mdash; the detector snaps to that note instead.</li></ul></div>
    <div class="help-card"><h3>Note range and octaves</h3><ul><li>The detector reads the full piano range, <strong>C0 to C8</strong>, plus a little above for whistles.</li><li>Typical adult <strong>male voices</strong>: bass C2-E4, baritone G2-G4, tenor C3-C5.</li><li>Typical adult <strong>female voices</strong>: alto F3-F5, mezzo A3-A5, soprano C4-C6.</li><li>Standard tuning reference is <strong>A4 = 440&nbsp;Hz</strong>. The whole chromatic scale derives from this.</li><li>Each octave doubles in frequency: A3 = 220&nbsp;Hz, A4 = 440&nbsp;Hz, A5 = 880&nbsp;Hz.</li></ul></div>
    <div class="help-card"><h3>Troubleshooting</h3><ul><li><strong>No reading:</strong> raise your mic volume in the OS sound settings, or lower the noise threshold slider.</li><li><strong>Reading jumps an octave:</strong> common in low male voices &mdash; the detector occasionally locks onto the second harmonic. Sing slightly louder or move closer to the mic.</li><li><strong>All readings are flat by ~50 cents:</strong> your audio interface may be running at a non-standard sample rate. Try a different browser or device.</li><li><strong>iOS Safari:</strong> mic only works on HTTPS pages. The site runs HTTPS so this is fine on production, but localhost over plain HTTP will not work on iOS.</li><li><strong>Background noise triggers false notes:</strong> raise the threshold slider until ambient room sound stops registering.</li></ul></div>
  </div>
</section>
