<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>RAID Calculator Guide</h2><p>Pick the right level for your use case &mdash; and understand what "fault tolerance" actually means.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>The 7 RAID levels in plain English</h3><ul><li><strong>RAID 0 (stripe):</strong> data split across drives for speed. Zero redundancy &mdash; any drive failure loses everything.</li><li><strong>RAID 1 (mirror):</strong> same data on every drive. Survives n-1 drive failures, uses half or less of raw capacity.</li><li><strong>RAID 5 (single parity):</strong> 1 drive's worth of parity spread across all drives. Survives 1 drive failure.</li><li><strong>RAID 6 (dual parity):</strong> 2 drives' worth of parity. Survives 2 simultaneous failures &mdash; recommended for 8+ TB drives.</li><li><strong>RAID 10 (1+0):</strong> mirrored pairs, then striped. Fast and safe, but 50% capacity cost.</li><li><strong>RAID 50 / 60:</strong> RAID 5 or 6 groups striped together. Balances speed and fault tolerance for large arrays.</li></ul></div>
    <div class="help-card"><h3>How to pick</h3><ul><li><strong>Home media server:</strong> RAID 5 with 4 drives is classic. RAID 6 if drives are 8&nbsp;TB or larger (rebuild time matters).</li><li><strong>VM / database host:</strong> RAID 10 for random I/O performance.</li><li><strong>Boot / OS mirror:</strong> RAID 1 with 2 drives.</li><li><strong>Scratch / video editing:</strong> RAID 0 if you can lose the data (and have a separate backup).</li><li><strong>Large archive (12+ drives):</strong> RAID 60 &mdash; 2-drive tolerance per group, good for cold data.</li></ul></div>
    <div class="help-card"><h3>Fault tolerance vs backup</h3><ul><li><strong>RAID is not backup.</strong> A ransomware attack, fire, flood, or accidental delete kills every drive in the array.</li><li>Always have a separate backup &mdash; 3-2-1 rule: 3 copies, 2 media types, 1 off-site.</li><li>Fault tolerance only covers <em>hardware drive failure</em>, and only up to the parity count.</li><li>A rebuild after a drive failure is <em>dangerous</em> on large arrays &mdash; it can trigger a second failure in a tired drive.</li></ul></div>
    <div class="help-card"><h3>Performance reality check</h3><ul><li>Read multipliers are theoretical best-case. Real-world depends on controller, cache, and workload.</li><li>Parity RAIDs (5 / 6) have a <strong>write penalty</strong>: each small write requires reading old data + old parity, computing new parity, and writing both back.</li><li>Controller cache masks most of the penalty for small workloads. Sustained sequential writes show the true cost.</li><li>For latency-sensitive work (databases), RAID 10 beats RAID 5/6 every time.</li></ul></div>
  </div>
</section>
