<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>RAM Latency Calculator Guide</h2><p>The math behind the number, and when latency vs bandwidth actually matters.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>The formula</h3><ul><li><strong>ns = (CL &times; 2000) / MT/s</strong></li><li>Why 2000? A cycle on DDR memory takes <em>2000 / MT/s</em> nanoseconds because DDR transfers on both edges of the clock (so MT/s = 2 &times; clock MHz).</li><li>CAS latency (CL) is the number of clock cycles between a READ command and the first word of data appearing.</li><li>Multiply cycles by cycle time (in ns) to get the real access time.</li><li>Example: DDR4 3200 CL16 &rarr; (16 &times; 2000) / 3200 = 10 ns.</li></ul></div>
    <div class="help-card"><h3>Common conversions</h3><ul><li><strong>DDR4 3200 CL16</strong> = 10.00 ns</li><li><strong>DDR4 3600 CL18</strong> = 10.00 ns (same access time as above, more bandwidth)</li><li><strong>DDR4 3600 CL16</strong> = 8.89 ns (tightest DDR4)</li><li><strong>DDR5 5200 CL40</strong> = 15.38 ns (early DDR5 kits)</li><li><strong>DDR5 6000 CL30</strong> = 10.00 ns (sweet-spot DDR5)</li><li><strong>DDR5 7200 CL36</strong> = 10.00 ns (high-end DDR5)</li><li>Notice: all the popular kits land around 10 ns &mdash; that's not a coincidence, it's where manufacturers target.</li></ul></div>
    <div class="help-card"><h3>Latency vs bandwidth</h3><ul><li>Two kits with identical ns (say 10 ns) will feel different in different workloads.</li><li><strong>Bandwidth matters</strong> for: 3D rendering, video encode, compilation, large-file I/O.</li><li><strong>Latency matters</strong> for: gaming (especially Ryzen with Infinity Fabric), pointer-heavy data structures, single-threaded CPU-bound work.</li><li>A DDR5 6000 CL30 kit at 48 GB/s bandwidth will outperform a DDR4 3200 CL16 kit at 25.6 GB/s in multi-threaded benchmarks even at matched latency.</li></ul></div>
    <div class="help-card"><h3>Reverse solve</h3><ul><li>Want to know what CL you need at DDR5-7200 to match DDR5-6000 CL30's 10 ns?</li><li>Enter 10 ns and 7200 MT/s in the reverse section &mdash; you get CL 36.</li><li>Use this when evaluating manual timing sets: if you can hit CL 34 at 7200, you've beaten DDR5-6000 CL30 on latency.</li><li>Real-world tightening is limited by the IMC (integrated memory controller) and motherboard trace length &mdash; not every kit will hit the numbers the calculator suggests.</li></ul></div>
  </div>
</section>
