<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>Surround Sound Test Guide</h2><p>How to walk your setup and catch the three most common wiring mistakes.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>How to run the test</h3><ol><li>Pick your layout (5.1 or 7.1). Use Stereo fallback if on headphones.</li><li>Click <strong>Walk all channels</strong>. The test plays a 1-second tone through each channel in order: FL, FR, C, SUB, RL, RR (and SL, SR for 7.1).</li><li>As each tone plays, note which physical speaker actually makes sound.</li><li>Compare against the on-screen diagram.</li><li>If the wrong speaker lights up, swap the cables or re-map channels in your audio control panel.</li></ol></div>
    <div class="help-card"><h3>Three common wiring mistakes</h3><ul><li><strong>Front L and R reversed:</strong> stereo still sounds "fine" but dialog centers poorly and every game's spatial audio is mirrored.</li><li><strong>Rear L and R swapped:</strong> Dolby upmix rotation sounds backwards on pans.</li><li><strong>Sub plugged into LFE but receiver crossover set to full-range:</strong> sub runs constantly hot or never. Fix crossover at 80&nbsp;Hz unless you have dedicated full-range mains.</li><li><strong>Center muted:</strong> you'll mistake this for "my dialog is quiet" in every movie until you walk the channels.</li></ul></div>
    <div class="help-card"><h3>When fallback kicks in</h3><ul><li>Chrome, Firefox, and Safari can only output up to 2 channels (stereo) via Web Audio in most setups.</li><li>True 5.1 / 7.1 discrete output requires a desktop OS with the right audio driver AND a browser build that reports <code>maxChannelCount >= 6</code>.</li><li>On headphones, the stereo-fallback mode pans each channel left/right so you still hear rough positioning and can check the walk order.</li><li>Listen for rear channels being quieter than front &mdash; that's the fallback shaping the mix, not a real surround effect.</li></ul></div>
    <div class="help-card"><h3>Troubleshooting</h3><ul><li><strong>No sound at all:</strong> click the page first (browsers need a gesture before audio plays).</li><li><strong>Only front L/R plays:</strong> your browser is 2-channel only. Use the dedicated OS channel test (Windows Sound control panel) to verify discrete output.</li><li><strong>Sub makes no sound:</strong> the LFE tone is 60&nbsp;Hz. Some tiny sub drivers under-reproduce that &mdash; try the <a href="<?php echo url('bass-test.php'); ?>">bass test</a> to sweep 20-200&nbsp;Hz.</li><li><strong>Virtual / spatial audio on:</strong> turn off Windows Sonic, Dolby Atmos for Headphones, or DTS Headphone:X to measure raw channels.</li></ul></div>
  </div>
</section>
