<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>TTK Calculator Guide</h2><p>The math behind the number, and how to read TTK for a given matchup.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>The TTK formula</h3><ul><li><strong>Bullets to kill (BTK)</strong> = ceiling(HP / effective damage per bullet).</li><li><strong>TTK</strong> = (BTK - 1) × interval, where interval = 60000 / RPM in ms.</li><li>Note: the first bullet has 0&nbsp;ms TTK &mdash; TTK is the <em>time between first impact and death</em>, not the time for all bullets to travel.</li><li>Example: AK-47 at 36 dmg, 600 RPM, 100 HP, no armor: BTK = ceil(100/36) = 3, interval = 100&nbsp;ms, TTK = 200&nbsp;ms.</li></ul></div>
    <div class="help-card"><h3>Armor and damage reduction</h3><ul><li>The armor field is flat damage reduction %. A 50% armor rating means each bullet deals half damage.</li><li>Real games vary: CS2 helmet reduces rifle headshot damage by ~21%, Valorant shields absorb damage up to shield HP, Apex Evo shields add flat HP.</li><li>For best results, look up the exact damage value in that game's wiki for the armor type you want to test (e.g. CS2 "AK-47 vs Kevlar" = 36 dmg confirmed from wiki).</li></ul></div>
    <div class="help-card"><h3>Headshot multipliers by game</h3><ul><li><strong>CS2:</strong> 4x head, 1x chest, 0.75x stomach, 0.5x leg for most rifles.</li><li><strong>Valorant:</strong> 3.5x head on most weapons (different from CS2!).</li><li><strong>Apex:</strong> 2x head for most weapons, 1.75x for some shotguns.</li><li><strong>Call of Duty:</strong> typically 1.3-1.5x head on modern entries.</li><li><strong>Overwatch:</strong> 2x head on most heroes (some have no headshot multiplier by design).</li></ul></div>
    <div class="help-card"><h3>Reading the TTK output</h3><ul><li>Lower TTK = stronger weapon in pure duels. But <strong>consistency</strong> matters as much as raw TTK.</li><li>A sniper with 0&nbsp;ms TTK on a bodyshot (AWP) is king on long sightlines but useless in close quarters.</li><li>The DPS column shows sustained damage &mdash; useful if the encounter extends past the initial bullet exchange.</li><li>Peeking advantage: if your ping+server tick gives you a 30&nbsp;ms first-shot advantage, any weapon with TTK under 30&nbsp;ms auto-wins trades; weapons with higher TTK need you to land first-bullet headshots.</li></ul></div>
  </div>
</section>
