<?php // Help ?>
<section class="guidelines landing-guide" id="guidelines">
  <div class="help-header"><h2>Webcam Mirror Guide</h2><p>How to use your webcam as a real mirror in the browser, plus tips for makeup, posture, and pre-call framing.</p></div>
  <div class="help-grid">
    <div class="help-card"><h3>How to use the mirror</h3><ol><li>Click <strong>Start mirror</strong> and allow the browser to use your camera.</li><li>The video opens flipped horizontally so it behaves like a real mirror &mdash; raise your right hand and the on-screen reflection raises its right hand too.</li><li>Use <strong>Mirror mode</strong> to toggle the flip off when you need to see the camera's true orientation (for example, when reading text held up to the lens).</li><li>Pick a different camera from the dropdown if you have more than one (USB webcam, built-in cam, virtual cam).</li><li>Adjust <strong>Brightness</strong> and <strong>Contrast</strong> until you can clearly see your face under your current lighting.</li></ol></div>
    <div class="help-card"><h3>Snapshot, grid &amp; fullscreen</h3><ul><li><strong>Snapshot</strong> captures the current frame &mdash; including the mirror flip and any brightness/contrast tweaks &mdash; and downloads it as a PNG (<code>mirror-snapshot-&lt;timestamp&gt;.png</code>).</li><li>The <strong>Rule-of-thirds grid</strong> overlay helps with face placement for makeup tutorials, eye-level alignment, and centering yourself on calls.</li><li><strong>Fullscreen</strong> turns the whole tab into a wall mirror &mdash; great on a tablet propped on a vanity or a laptop on a desk.</li><li><strong>Reset filters</strong> snaps brightness and contrast back to 100% in one click.</li></ul></div>
    <div class="help-card"><h3>Common use cases</h3><ul><li><strong>Makeup &amp; grooming:</strong> good light + 1080p webcam beats most handheld mirrors. The grid keeps your face centered.</li><li><strong>Posture &amp; ergonomics:</strong> see how you sit during a long work session. Spot a hunched neck or slouched shoulder you would not otherwise notice.</li><li><strong>Pre-call framing:</strong> check what coworkers will see &mdash; framing, lighting, what is in the background &mdash; before joining the call.</li><li><strong>Public speaking practice:</strong> rehearse a presentation while watching your gestures and facial expressions in real time.</li></ul></div>
    <div class="help-card"><h3>Privacy &amp; troubleshooting</h3><ul><li>The video stream stays inside your browser tab. Nothing is sent to a server, recorded, or uploaded.</li><li>If the camera does not start, the browser usually shows a blocked-camera icon in the address bar &mdash; click it to grant permission.</li><li>On phones, both Safari and Chrome require an HTTPS page before <code>getUserMedia</code> works (this site is HTTPS).</li><li>Other apps holding the camera (Zoom, Teams, OBS) can block the browser. Close them and reload.</li><li>For a wider hardware check, try the <a href="<?php echo url('webcamtesterindex.php'); ?>">main webcam tester</a> &mdash; it reports resolution and FPS and lets you switch resolutions explicitly.</li></ul></div>
  </div>
</section>
