<?php
/**
 * Russian localized landing page for aspect-ratio-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Калькулятор соотношения сторон - Ширина, Высота';
$pageDescription = 'Бесплатный калькулятор соотношения сторон: введите любые два из ширины, высоты или соотношения (16:9, 21:9, 4:3) — автоматически сводит к целым с живым превью.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('aspect-ratio-calculator.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/aspect-ratio-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('aspect-ratio-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Калькуляторы экрана</p>
          <h1 class="hero-title">Калькулятор соотношения сторон</h1>
          <p class="hero-lede">Введите два из трёх: ширина, высота или соотношение. Автоматически упрощает до целых (1920×1080 → 16:9) с живым превью.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#aspect-ratio-calculator">Открыть калькулятор</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="aspect-ratio-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Калькуляторы экрана</p>
          <h2>Калькулятор соотношения сторон</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/aspect-ratio-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
