<?php
/**
 * Russian localized landing page for burn-in-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Тест выгорания OLED - Остаточное изображение';
$pageDescription = 'Тест burn-in для OLED: циклически показывает 8 сплошных цветов, мелкую шахматку и прокручивающийся refresher в полный экран — выявление выгорания и image retention.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('burn-in-test.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/burn-in-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('burn-in-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Диагностика экрана</p>
          <h1 class="hero-title">Тест выгорания OLED</h1>
          <p class="hero-lede">Обнаружьте остаточные изображения и выгорание. Цикл 8 сплошных цветов, мелкая шахматка для залипших субпикселей и бегущий обновитель для восстановления OLED.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#burn-in-test">Запустить тест</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="burn-in-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Диагностика экрана</p>
          <h2>Тест выгорания OLED</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/burn-in-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
