<?php
/**
 * russian localized landing page for cpu-stress-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Стресс-тест CPU - Бенчмарк WebWorker в браузере';
$pageDescription = 'Многопоточный стресс-тест CPU с циклами SHA-256 в WebWorker. Выдаёт операции/с всего и на поток. Обнаруживает тепловой троттлинг.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('cpu-stress-test.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/cpu-stress-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('cpu-stress-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('cpu_stress_test', [['name'=>'Home','url'=>'/'],['name'=>'Стресс-тест CPU','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Тест оборудования</p>
          <h1 class="hero-title">Стресс-тест CPU</h1>
          <p class="hero-lede">Запускает WebWorker по числу логических ядер для нагрузки CPU циклами SHA-256. Выводит операции/с всего и на поток для выявления теплового троттлинга. Без установки.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#cpu-stress-test">Запустить</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/cpu-stress-test/hero.jpg'); ?>" width="1200" height="800" alt="Стресс-тест CPU" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="cpu-stress-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Основной инструмент</p>
          <h2>Стресс-тест CPU</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/cpu_stress_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/cpu-stress-test.php'; ?>
    <?php $currentTool = 'mouse'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/cpu-stress-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
