<?php
/**
 * Russian localized landing page for edpi-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Калькулятор eDPI - Эффективный DPI для FPS';
$pageDescription = 'Бесплатный eDPI-калькулятор: вычисляет эффективный DPI (DPI × чувствительность) и см/360 для CS2, Valorant, Apex, Overwatch и других FPS. С yaw-пресетами по играм.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('edpi-calculator.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/edpi-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('edpi-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Калькуляторы чувствительности</p>
          <h1 class="hero-title">Калькулятор eDPI - Эффективный DPI</h1>
          <p class="hero-lede">Рассчитайте ваш эффективный DPI (eDPI = DPI × чувствительность) для сравнения прицеливания в CS2, Valorant, Apex. Включает конвертацию cm/360.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#edpi-calculator">Рассчитать eDPI</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="edpi-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Калькуляторы чувствительности</p>
          <h2>Калькулятор eDPI - Эффективный DPI</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/edpi-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
