<?php
/**
 * russian localized landing page for frequency-response-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Тест частотной характеристики - развёртка 20 Гц - 20 кГц';
$pageDescription = 'Аудио-развёртка от 20 Гц до 20 кГц с отметками третьоктавы для определения вашего диапазона слуха и оценки наушников.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('frequency-response-test.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/frequency-response-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('frequency-response-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('frequency_response_test', [['name'=>'Home','url'=>'/'],['name'=>'Тест частотной характеристики','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Аудиодиагностика</p>
          <h1 class="hero-title">Тест частотной характеристики</h1>
          <p class="hero-lede">Развёртка от 20 Гц до 20 кГц с ISO-пресетами 1/3 октавы. Определяет пределы слуха и реальную АЧХ наушников или колонок. Чистые синусоиды, генерируемые локально в браузере.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#frequency-response-test">Запустить тест</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/frequency-response-test/hero.jpg'); ?>" width="1200" height="800" alt="Тест частотной характеристики" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="frequency-response-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Основной инструмент</p>
          <h2>Тест частотной характеристики</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/frequency_response_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/frequency-response-test.php'; ?>
    <?php $currentTool = 'audio'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/frequency-response-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
