<?php
/**
 * russian localized landing page for gpu-stress-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Стресс-тест GPU - Бенчмарк шейдера WebGL';
$pageDescription = 'Фрагментный шейдер Мандельброта на WebGL2 для нагрузки любой GPU. Показывает FPS, минимум FPS и обнаруживает программный рендер.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('gpu-stress-test.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/gpu-stress-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('gpu-stress-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('gpu_stress_test', [['name'=>'Home','url'=>'/'],['name'=>'Стресс-тест GPU','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Тест оборудования</p>
          <h1 class="hero-title">Стресс-тест GPU</h1>
          <p class="hero-lede">Рендерит высокоитерационный Mandelbrot-фрагментный шейдер на WebGL2, чтобы нагрузить любую GPU. Показывает мгновенный FPS, среднее за 1 с, минимум и обнаруживает программный рендер (SwiftShader).</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#gpu-stress-test">Запустить</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/gpu-stress-test/hero.jpg'); ?>" width="1200" height="800" alt="Стресс-тест GPU" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="gpu-stress-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Основной инструмент</p>
          <h2>Стресс-тест GPU</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/gpu_stress_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/gpu-stress-test.php'; ?>
    <?php $currentTool = 'screen'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/gpu-stress-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
