<?php
/**
 * russian localized landing page for hearing-age-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Тест Возраста Слуха - Тон Комара (Сколько Лет Вашим Ушам?)';
$pageDescription = 'Бесплатный тест возраста слуха. Развёртка 12 частот от 8 кГц до 22 кГц включая комариный тон 17.4 кГц, с ручным слайдером и безопасной громкостью.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('hearing-age-test.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/hearing-age-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('hearing-age-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('hearing_age_test', [['name'=>'Home','url'=>'/'],['name'=>'Тест Возраста Слуха - Сколько Лет Вашим Ушам?','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Аудиодиагностика</p>
          <h1 class="hero-title">Тест Возраста Слуха - Сколько Лет Вашим Ушам?</h1>
          <p class="hero-lede">Вирусный тест возраста слуха с 12 частотами от 8 кГц до 22 кГц, включая комариный тон 17.4 кГц. Для точности используйте проводные наушники.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#hearing-age-test">Запустить тест</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/hearing-age-test/hero.jpg'); ?>" width="1200" height="800" alt="Тест Возраста Слуха - Сколько Лет Вашим Ушам?" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="hearing-age-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Основной инструмент</p>
          <h2>Тест Возраста Слуха</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/hearing_age_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'hearing-age-test'; $localizedRelatedCategory = 'audio'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
