<?php
/**
 * russian localized landing page for minecraft-circle-generator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Генератор кругов Minecraft - контур, диск, сфера';
$pageDescription = 'Генератор пиксельных кругов для Minecraft: контур, заливка, толстое кольцо и слои сферы. Радиус 1-256.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('minecraft-circle-generator.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/minecraft-circle-generator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('minecraft-circle-generator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('minecraft_circle', [['name'=>'Home','url'=>'/'],['name'=>'Генератор кругов Minecraft','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Игровой инструмент</p>
          <h1 class="hero-title">Генератор кругов Minecraft</h1>
          <p class="hero-lede">Рисует идеальные круги, заполненные диски, толстые кольца и слои 3D-сферы радиусом от 1 до 256 блоков. Считает блоки, скачивает PNG для второго монитора, копирует рисунок слой за слоем в игре.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#minecraft-circle-generator">Нарисовать круг</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/minecraft-circle-generator/hero.jpg'); ?>" width="1200" height="800" alt="Генератор кругов Minecraft" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="minecraft-circle-generator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Основной инструмент</p>
          <h2>Генератор кругов Minecraft</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/minecraft_circle_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'minecraft-circle-generator'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
