<?php
/**
 * russian localized landing page for monitor-sharpness-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Тест чёткости монитора - онлайн проверка текста';
$pageDescription = 'Бесплатный тест чёткости монитора. Сетка 1 px в стиле Lagom, текстовые образцы разных размеров, блоки цветной каймы и RGB-линейка субпикселей.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('monitor-sharpness-test.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/monitor-sharpness-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('monitor-sharpness-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('monitor_sharpness_test', [['name'=>'Home','url'=>'/'],['name'=>'Бесплатный тест чёткости монитора - онлайн проверка текста','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Диагностика дисплея</p>
          <h1 class="hero-title">Бесплатный тест чёткости монитора - онлайн проверка текста</h1>
          <p class="hero-lede">Отрисовывает сетку 1 px в стиле Lagom, образцы текста (засечки, гротеск, моноширинный), блоки цветной каймы и RGB-линейку субпикселей для оценки чёткости дисплея.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#monitor-sharpness-test">Запустить тест</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/monitor-sharpness-test/hero.jpg'); ?>" width="1200" height="800" alt="Бесплатный тест чёткости монитора - онлайн проверка текста" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="monitor-sharpness-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Основной инструмент</p>
          <h2>Тест чёткости монитора</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/monitor_sharpness_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/monitor-sharpness-test.php'; ?>
    <?php $currentTool = 'screen'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/monitor-sharpness-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
