<?php
/**
 * Russian localized landing page for mouse-spin-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Тест вращения мыши - Счётчик 360°';
$pageDescription = 'Тест вращения мыши: считает полные обороты 360° в сессиях 15, 30 или 60 секунд с определением пика оборотов в секунду. В реальном времени, без установки.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('mouse-spin-test.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/mouse-spin-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('mouse-spin-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Диагностика мыши</p>
          <h1 class="hero-title">Тест вращения мыши</h1>
          <p class="hero-lede">Сколько полных 360° вращений мышью за 30 секунд? Зажмите и крутите вокруг центра.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#mouse-spin-test">Начать вращать</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="mouse-spin-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Диагностика мыши</p>
          <h2>Тест вращения мыши</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/mouse-spin-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
