<?php
/**
 * russian localized landing page for online-ruler
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Онлайн Линейка в Натуральную Величину - см и Дюймы с Калибровкой';
$pageDescription = 'Бесплатная онлайн-линейка в натуральную величину на экране. Измеряйте в см, мм и дюймах. Калибруйте по кредитной карте (ISO ID-1) или вводом DPI монитора.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('online-ruler.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/online-ruler.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('online-ruler.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('online_ruler', [['name'=>'Home','url'=>'/'],['name'=>'Онлайн Линейка в Натуральную Величину - см и Дюймы с Калибровкой','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Калькулятор</p>
          <h1 class="hero-title">Онлайн Линейка в Натуральную Величину - см и Дюймы с Калибровкой</h1>
          <p class="hero-lede">SVG-линейка в см и дюймах, которую вы подгоняете к экрану реальной банковской картой (стандарт ISO ID-1) или DPI монитора. Калибровка сохраняется в браузере.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#online-ruler">Открыть линейку</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/online-ruler/hero.jpg'); ?>" width="1200" height="800" alt="Онлайн Линейка в Натуральную Величину - см и Дюймы с Калибровкой" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="online-ruler">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Основной инструмент</p>
          <h2>Онлайн Линейка</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/online_ruler_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/online-ruler.php'; ?>
    <?php $currentTool = 'mouse'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/online-ruler.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
