<?php
/**
 * russian localized landing page for ram-latency-calculator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Калькулятор латентности RAM - CAS в наносекунды';
$pageDescription = 'Переводит латентность CAS (CL) и скорость (MT/s) в реальные наносекунды. Сравнивает наборы DDR4 и DDR5.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('ram-latency-calculator.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/ram-latency-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('ram-latency-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('ram_latency_calc', [['name'=>'Home','url'=>'/'],['name'=>'Калькулятор латентности RAM','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Калькулятор</p>
          <h1 class="hero-title">Калькулятор латентности RAM</h1>
          <p class="hero-lede">Переводит CL и MT/s в реальные наносекунды по формуле ns = (CL × 2000) / MT/s. Сравнивает два набора DDR4 или DDR5 рядом или решает обратную задачу: какой CL нужен для заданного ns.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#ram-latency-calculator">Рассчитать</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/ram-latency-calculator/hero.jpg'); ?>" width="1200" height="800" alt="Калькулятор латентности RAM" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="ram-latency-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Основной инструмент</p>
          <h2>Калькулятор латентности RAM</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/ram_latency_calc_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'ram-latency-calculator'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
