<?php
/**
 * Russian localized landing page for screen-size-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Калькулятор размера экрана - Диагональ, Ширина';
$pageDescription = 'Калькулятор размера экрана: вычисляет диагональ, ширину, высоту и видимую площадь из соотношения сторон и одного размера — в дюймах и см. Бесплатно, мгновенно.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('screen-size-calculator.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/screen-size-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('screen-size-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Калькуляторы экрана</p>
          <h1 class="hero-title">Калькулятор размера экрана</h1>
          <p class="hero-lede">Введите соотношение сторон и одно измерение. Инструмент рассчитывает другие два в дюймах и см плюс видимую площадь.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#screen-size-calculator">Открыть калькулятор</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="screen-size-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Калькуляторы экрана</p>
          <h2>Калькулятор размера экрана</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/screen-size-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
