<?php
/**
 * russian localized landing page for surround-sound-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Тест объёмного звука - каналы 5.1 и 7.1';
$pageDescription = 'Обход каналов 5.1 и 7.1 для проверки подключения и размещения колонок. Стерео-панорамный фолбек для наушников.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('surround-sound-test.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/surround-sound-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('surround-sound-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('surround_sound_test', [['name'=>'Home','url'=>'/'],['name'=>'Тест объёмного звука','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Аудиодиагностика</p>
          <h1 class="hero-title">Тест объёмного звука</h1>
          <p class="hero-lede">Прогоняет каналы 5.1 или 7.1 по одному, чтобы убедиться, что каждый динамик подключён к правильному каналу. Если браузер не даёт многоканал, переключается на стерео-панораму для наушников.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#surround-sound-test">Запустить</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/surround-sound-test/hero.jpg'); ?>" width="1200" height="800" alt="Тест объёмного звука" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="surround-sound-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Основной инструмент</p>
          <h2>Тест объёмного звука</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/surround_sound_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/surround-sound-test.php'; ?>
    <?php $currentTool = 'audio'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/surround-sound-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
