<?php
/**
 * russian localized landing page for vibration-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Тест вибрации - тактильная отдача телефона и геймпада';
$pageDescription = 'Проверьте Vibration API телефона с пресетами и вибрацию геймпада с раздельными ползунками.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('vibration-test.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/vibration-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('vibration-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('vibration_test', [['name'=>'Home','url'=>'/'],['name'=>'Тест вибрации','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Датчик устройства</p>
          <h1 class="hero-title">Тест вибрации</h1>
          <p class="hero-lede">Проверяет вибрацию телефона (Vibration API) с пресетами паттернов и вибрацию геймпада со слайдерами отдельно для каждого мотора. Всё в браузере, без установки.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#vibration-test">Запустить</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/vibration-test/hero.jpg'); ?>" width="1200" height="800" alt="Тест вибрации" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="vibration-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Основной инструмент</p>
          <h2>Тест вибрации</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/vibration_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'vibration-test'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
