<?php
/**
 * Russian localized landing page for viewing-distance-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ru.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Калькулятор дистанции просмотра ТВ и Монитор';
$pageDescription = 'Калькулятор дистанции просмотра: оптимальная дистанция TV/монитора по THX (36° FoV), SMPTE (30° FoV) и пределу разрешения 4K/8K. В футах и метрах, бесплатно.';
?>
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('viewing-distance-calculator.php'); ?>">
  <link rel="alternate" hreflang="ru" href="<?php echo absoluteUrl('languages/russian/viewing-distance-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('viewing-distance-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ru.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Калькуляторы экрана</p>
          <h1 class="hero-title">Калькулятор дистанции просмотра</h1>
          <p class="hero-lede">На каком расстоянии сидеть от ТВ или монитора? THX (36° FoV погружение), SMPTE (30° кино) и максимальная дистанция различимости 4K/8K.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#viewing-distance-calculator">Открыть калькулятор</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Все инструменты</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="viewing-distance-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Калькуляторы экрана</p>
          <h2>Калькулятор дистанции просмотра</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/viewing-distance-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ru.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
