<?php
/**
 * japanese localized landing page for accelerometer-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ja.php'; if (file_exists($__c)) include $__c;
$pageTitle = '加速度センサーテスト - スマホの動きセンサー';
$pageDescription = 'スマートフォンやタブレットの加速度センサーをリアルタイム表示。3D キューブとシェイク検出付き。';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('accelerometer-test.php'); ?>">
  <link rel="alternate" hreflang="ja" href="<?php echo absoluteUrl('languages/japanese/accelerometer-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('accelerometer-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('accelerometer_test', [['name'=>'Home','url'=>'/'],['name'=>'加速度センサーテスト','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ja.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">デバイスセンサー</p>
          <h1 class="hero-title">加速度センサーテスト</h1>
          <p class="hero-lede">スマートフォンやタブレットの加速度センサー(DeviceMotionEvent)をリアルタイムで表示。XYZ を m/s² で、向きを 3D キューブで、シェイクカウンターも。iOS は明示的な許可を求めます。</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#accelerometer-test">センサー開始</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">すべてのツールを見る</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/accelerometer-test/hero.jpg'); ?>" width="1200" height="800" alt="加速度センサーテスト" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="accelerometer-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">メインツール</p>
          <h2>加速度センサーテスト</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/accelerometer_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/accelerometer-test.php'; ?>
    <?php $currentTool = 'mouse'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/accelerometer-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ja.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
