<?php
/**
 * Japanese localized landing page for apm-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ja.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'APMテスト - RTS・MOBA用 分あたりアクション';
$pageDescription = '無料APMテスト。キー押下とクリックを60秒ローリングウィンドウでカウント。';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('apm-test.php'); ?>">
  <link rel="alternate" hreflang="ja" href="<?php echo absoluteUrl('languages/japanese/apm-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('apm-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ja.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">ゲーミング診断</p>
          <h1 class="hero-title">APMテスト</h1>
          <p class="hero-lede">StarCraft・DotA・LoLなどマイクロ重視のゲームで、分あたりのアクション数を計測。60秒ローリングウィンドウにピークAPMとセッション平均。</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#apm-test">APMテスト開始</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">全ツール</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="apm-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">ゲーミング診断</p>
          <h2>APMテスト</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/apm-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ja.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
