<?php
/**
 * japanese localized landing page for bandwidth-calculator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ja.php'; if (file_exists($__c)) include $__c;
$pageTitle = '帯域幅計算ツール - サイズ、速度、時間';
$pageDescription = 'ファイルサイズと回線速度を転送時間に変換。3 方向で計算可能、ビット vs バイトの変換を自動処理。';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('bandwidth-calculator.php'); ?>">
  <link rel="alternate" hreflang="ja" href="<?php echo absoluteUrl('languages/japanese/bandwidth-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('bandwidth-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('bandwidth_calc', [['name'=>'Home','url'=>'/'],['name'=>'帯域幅計算ツール','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ja.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">計算ツール</p>
          <h1 class="hero-title">帯域幅計算ツール</h1>
          <p class="hero-lede">3 方向(時間・サイズ・必要速度)で計算できます。KB/MB/GB/TB と Kbps/Mbps/Gbps の切替、ビット vs バイトの罠を自動処理します。</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#bandwidth-calculator">計算</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">すべてのツールを見る</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/bandwidth-calculator/hero.jpg'); ?>" width="1200" height="800" alt="帯域幅計算ツール" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="bandwidth-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">メインツール</p>
          <h2>帯域幅計算ツール</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/bandwidth_calc_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'bandwidth-calculator'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ja.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
