<?php
/**
 * Japanese localized landing page for burn-in-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ja.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'OLED焼き付きテスト - 画像保持';
$pageDescription = '無料のOLED焼き付きテスト。単色サイクル、市松模様、スクロールリフレッシャー。';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('burn-in-test.php'); ?>">
  <link rel="alternate" hreflang="ja" href="<?php echo absoluteUrl('languages/japanese/burn-in-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('burn-in-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ja.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">ディスプレイ診断</p>
          <h1 class="hero-title">OLED焼き付きテスト</h1>
          <p class="hero-lede">画面の画像保持と焼き付きを検出。8色の単色サイクル、固着サブピクセル用の細かい市松模様、OLED回復用のスクロールリフレッシャー。</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#burn-in-test">テスト開始</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">全ツール</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="burn-in-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">ディスプレイ診断</p>
          <h2>OLED焼き付きテスト</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/burn-in-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ja.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
