<?php
/**
 * japanese localized landing page for download-time-calculator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ja.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'ダウンロード時間計算ツール - ゲーム・動画・バックアップ';
$pageDescription = '回線速度に対するゲーム・動画・バックアップのダウンロード時間を推定。15 以上のプリセットと理論・現実・低速シナリオ。';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('download-time-calculator.php'); ?>">
  <link rel="alternate" hreflang="ja" href="<?php echo absoluteUrl('languages/japanese/download-time-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('download-time-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('download_time_calc', [['name'=>'Home','url'=>'/'],['name'=>'ダウンロード時間計算ツール','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ja.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">計算ツール</p>
          <h1 class="hero-title">ダウンロード時間計算ツール</h1>
          <p class="hero-lede">プリセット(AAA タイトル、4K 映画、Linux ISO、Steam バックアップ)を選ぶかサイズを入力すれば、Xh Ym Zs 形式で時間を表示します。現実値 85%、理論値 100%、低速ネットワーク 60% の 3 本立て。</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#download-time-calculator">推定</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">すべてのツールを見る</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/download-time-calculator/hero.jpg'); ?>" width="1200" height="800" alt="ダウンロード時間計算ツール" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="download-time-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">メインツール</p>
          <h2>ダウンロード時間計算ツール</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/download_time_calc_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'download-time-calculator'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ja.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
