<?php
/**
 * japanese localized landing page for frequency-response-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ja.php'; if (file_exists($__c)) include $__c;
$pageTitle = '周波数特性テスト - 20 Hz から 20 kHz スイープ';
$pageDescription = '20 Hz から 20 kHz までのオーディオスイープで、聴力の限界を知りヘッドホンやモニターを評価します。';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('frequency-response-test.php'); ?>">
  <link rel="alternate" hreflang="ja" href="<?php echo absoluteUrl('languages/japanese/frequency-response-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('frequency-response-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('frequency_response_test', [['name'=>'Home','url'=>'/'],['name'=>'周波数特性テスト','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ja.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">オーディオ診断</p>
          <h1 class="hero-title">周波数特性テスト</h1>
          <p class="hero-lede">20 Hz から 20 kHz のスイープと ISO 1/3 オクターブプリセットで、聴力の上限とヘッドホン・スピーカーの実際の応答を確認します。ブラウザ内で生成される純粋な正弦波。</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#frequency-response-test">テスト開始</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">すべてのツールを見る</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/frequency-response-test/hero.jpg'); ?>" width="1200" height="800" alt="周波数特性テスト" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="frequency-response-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">メインツール</p>
          <h2>周波数特性テスト</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/frequency_response_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/frequency-response-test.php'; ?>
    <?php $currentTool = 'audio'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/frequency-response-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ja.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
