<?php
/**
 * japanese localized landing page for monitor-sharpness-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ja.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'モニター鮮明度テスト - オンラインテキスト鮮明度';
$pageDescription = 'モニターの鮮明度を無料でテスト。Lagom風の1pxピクセルグリッド、複数サイズのテキスト見本、色フリンジブロック、RGBサブピクセル定規。';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('monitor-sharpness-test.php'); ?>">
  <link rel="alternate" hreflang="ja" href="<?php echo absoluteUrl('languages/japanese/monitor-sharpness-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('monitor-sharpness-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('monitor_sharpness_test', [['name'=>'Home','url'=>'/'],['name'=>'無料モニター鮮明度テスト - オンラインのテキスト鮮明度確認','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ja.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">ディスプレイ診断</p>
          <h1 class="hero-title">無料モニター鮮明度テスト - オンラインのテキスト鮮明度確認</h1>
          <p class="hero-lede">Lagom風の1pxピクセルグリッド、セリフ・サンセリフ・等幅のテキスト見本、色フリンジブロック、RGBサブピクセル定規を表示してモニターの鮮明さを評価します。</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#monitor-sharpness-test">テスト開始</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">すべてのツールを見る</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/monitor-sharpness-test/hero.jpg'); ?>" width="1200" height="800" alt="無料モニター鮮明度テスト - オンラインのテキスト鮮明度確認" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="monitor-sharpness-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">メインツール</p>
          <h2>モニター鮮明度テスト</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/monitor_sharpness_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'monitor-sharpness-test'; $localizedRelatedCategory = 'screen'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ja.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
