<?php
/**
 * japanese localized landing page for online-ruler
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ja.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'オンライン定規 実寸表示 - cm・インチ、キャリブレーション対応';
$pageDescription = '画面に実寸で表示される無料オンライン定規。cm、mm、インチで測定可能。クレジットカード（ISO ID-1）またはモニターDPIでキャリブレーション。';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('online-ruler.php'); ?>">
  <link rel="alternate" hreflang="ja" href="<?php echo absoluteUrl('languages/japanese/online-ruler.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('online-ruler.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('online_ruler', [['name'=>'Home','url'=>'/'],['name'=>'オンライン定規 実寸表示 - cm・インチ、キャリブレーション対応','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ja.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">計算ツール</p>
          <h1 class="hero-title">オンライン定規 実寸表示 - cm・インチ、キャリブレーション対応</h1>
          <p class="hero-lede">実物のクレジットカード（ISO ID-1規格）または画面DPIで合わせて使うcm・インチ表示のSVG定規。キャリブレーションはブラウザに保存されます。</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#online-ruler">定規を開く</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">すべてのツールを見る</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/online-ruler/hero.jpg'); ?>" width="1200" height="800" alt="オンライン定規 実寸表示 - cm・インチ、キャリブレーション対応" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="online-ruler">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">メインツール</p>
          <h2>オンライン定規</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/online_ruler_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/online-ruler.php'; ?>
    <?php $currentTool = 'mouse'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/online-ruler.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ja.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
