<?php
/**
 * japanese localized landing page for pitch-detector
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ja.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'オンラインピッチ検出器 - 歌っている音は何？';
$pageDescription = '無料のオンラインピッチ検出器。マイクに歌うか演奏すると、周波数（Hz）、最も近い音名（C0〜C8）、オクターブ、セント単位のずれをリアルタイム表示。';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('pitch-detector.php'); ?>">
  <link rel="alternate" hreflang="ja" href="<?php echo absoluteUrl('languages/japanese/pitch-detector.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('pitch-detector.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('pitch_detector', [['name'=>'Home','url'=>'/'],['name'=>'無料オンラインピッチ検出器 - 歌っている音は何？','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ja.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">オーディオ診断</p>
          <h1 class="hero-title">無料オンラインピッチ検出器 - 歌っている音は何？</h1>
          <p class="hero-lede">歌う、ハミングする、演奏する。周波数、音名、セントずれを瞬時に表示。直近10秒のスクロールグラフ付き。</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#pitch-detector">検出開始</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">すべてのツールを見る</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/pitch-detector/hero.jpg'); ?>" width="1200" height="800" alt="無料オンラインピッチ検出器 - 歌っている音は何？" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="pitch-detector">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">メインツール</p>
          <h2>ピッチ検出器</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/pitch_detector_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'pitch-detector'; $localizedRelatedCategory = 'audio'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ja.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
