<?php
/**
 * Japanese localized landing page for screen-uniformity-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ja.php'; if (file_exists($__c)) include $__c;
$pageTitle = '画面ユニフォーミティテスト - クラウディング、IPSグロー';
$pageDescription = '無料のユニフォーミティテスト。フルスクリーンで灰・黒・白・RGBを表示しクラウディング、IPSグロー、バックライト漏れを検出。';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('screen-uniformity-test.php'); ?>">
  <link rel="alternate" hreflang="ja" href="<?php echo absoluteUrl('languages/japanese/screen-uniformity-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('screen-uniformity-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ja.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">ディスプレイ診断</p>
          <h1 class="hero-title">画面ユニフォーミティテスト</h1>
          <p class="hero-lede">色と明るさを選びフルスクリーンに切り替え、暗い角、雲状の斑、色相ドリフトを観察。色ごとに異なる問題が浮き上がります。</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#screen-uniformity-test">テスト開始</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">全ツール</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="screen-uniformity-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">ディスプレイ診断</p>
          <h2>画面ユニフォーミティテスト</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/screen-uniformity-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ja.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
