<?php
/**
 * Japanese localized landing page for screen-size-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ja.php'; if (file_exists($__c)) include $__c;
$pageTitle = '画面サイズ計算機 - 対角・幅・高さ';
$pageDescription = '無料の画面サイズ計算機。対角・幅・高さをインチとcmで。';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('screen-size-calculator.php'); ?>">
  <link rel="alternate" hreflang="ja" href="<?php echo absoluteUrl('languages/japanese/screen-size-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('screen-size-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ja.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">画面計算機</p>
          <h1 class="hero-title">画面サイズ計算機</h1>
          <p class="hero-lede">アスペクト比と1つの寸法を入力。残り2つの寸法をインチとcmで計算し、可視面積も表示。</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#screen-size-calculator">計算機を開く</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">全ツール</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="screen-size-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">画面計算機</p>
          <h2>画面サイズ計算機</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/screen-size-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ja.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
