<?php
/**
 * japanese localized landing page for webcam-mirror
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ja.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'オンラインウェブカメラミラー - カメラをバーチャルミラーに';
$pageDescription = '無料のウェブカメラミラー。水平反転、明るさ/コントラスト、三分割グリッド、PNG保存に対応。何もアップロードしません。';
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('webcam-mirror.php'); ?>">
  <link rel="alternate" hreflang="ja" href="<?php echo absoluteUrl('languages/japanese/webcam-mirror.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('webcam-mirror.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('webcam_mirror', [['name'=>'Home','url'=>'/'],['name'=>'オンラインウェブカメラミラー - カメラをバーチャルミラーに','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ja.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">デバイスセンサー</p>
          <h1 class="hero-title">オンラインウェブカメラミラー - カメラをバーチャルミラーに</h1>
          <p class="hero-lede">水平反転、明るさ・コントラスト、三分割グリッド、スナップショット保存に対応したライブカメラ。映像はブラウザ内のみで処理されます。</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#webcam-mirror">ミラーを開く</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">すべてのツールを見る</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/webcam-mirror/hero.jpg'); ?>" width="1200" height="800" alt="オンラインウェブカメラミラー - カメラをバーチャルミラーに" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="webcam-mirror">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">メインツール</p>
          <h2>ウェブカメラミラー</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/webcam_mirror_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/webcam-mirror.php'; ?>
    <?php $currentTool = 'webcam'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/webcam-mirror.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ja.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
