<?php
/**
 * Portuguese localized landing page for color-range-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-pt.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Teste de Faixa de Cor - RGB Completo vs Limitado';
$pageDescription = 'Teste de faixa de cor: detecta Full RGB (0-255) vs Limited (16-235) com grades de patches próximos ao preto e ao branco. Corrige corte de sombras e realces, no navegador.';
?>
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('color-range-test.php'); ?>">
  <link rel="alternate" hreflang="pt" href="<?php echo absoluteUrl('languages/portuguese/color-range-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('color-range-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-pt.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de tela</p>
          <h1 class="hero-title">Teste de Faixa de Cor</h1>
          <p class="hero-lede">Monitores RGB completo mostram cada patch distinto. Faixa limitada esmaga os patches mais escuros e mais claros em preto e branco puros.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#color-range-test">Executar teste</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Todas as ferramentas</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="color-range-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Diagnóstico de tela</p>
          <h2>Teste de Faixa de Cor</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/color-range-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-pt.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
