<?php
/**
 * Portuguese localized landing page for fps-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-pt.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Teste de FPS - Taxa de Quadros do Navegador';
$pageDescription = 'Teste de FPS online: medição em tempo real da taxa de quadros do navegador com média/mín/máx/1%-low e detecção automática 60/120/144/240 Hz. Sem instalação.';
?>
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('fps-test.php'); ?>">
  <link rel="alternate" hreflang="pt" href="<?php echo absoluteUrl('languages/portuguese/fps-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('fps-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-pt.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de desempenho</p>
          <h1 class="hero-title">Teste de FPS</h1>
          <p class="hero-lede">Mede a taxa de quadros do navegador ao vivo via requestAnimationFrame. Mostra FPS atual, média, min, max e 1%-low.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#fps-test">Iniciar teste</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Todas as ferramentas</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="fps-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Diagnóstico de desempenho</p>
          <h2>Teste de FPS</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/fps-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-pt.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
