<?php
/**
 * portuguese localized landing page for guild-name-generator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-pt.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Gerador de nomes de guild - Nomes de clã para MMO';
$pageDescription = 'Gerador de nomes de guild e clã em 6 temas e 5 modelos com limites de WoW, FFXIV, Destiny e Discord.';
?>
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('guild-name-generator.php'); ?>">
  <link rel="alternate" hreflang="pt" href="<?php echo absoluteUrl('languages/portuguese/guild-name-generator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('guild-name-generator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('guild_name_generator', [['name'=>'Home','url'=>'/'],['name'=>'Gerador de nomes de guild','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-pt.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Utilitário de gaming</p>
          <h1 class="hero-title">Gerador de nomes de guild</h1>
          <p class="hero-lede">Gera 10 nomes de guild aleatórios em 6 temas (fantasia, ficção, sombrio, nobre, rogue, mítico) com modelos como "Ordem de X", "Casa X", "Os X". Cópia em um clique e favoritos.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#guild-name-generator">Gerar nomes</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas as ferramentas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/guild-name-generator/hero.jpg'); ?>" width="1200" height="800" alt="Gerador de nomes de guild" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="guild-name-generator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Ferramenta principal</p>
          <h2>Gerador de nomes de guild</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/guild_name_generator_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'guild-name-generator'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-pt.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
