<?php
/**
 * portuguese localized landing page for hearing-age-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-pt.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Teste de Idade Auditiva - Tom Mosquito (Que Idade Tem Seus Ouvidos?)';
$pageDescription = 'Teste de idade auditiva gratis. Varredura de 12 frequencias de 8 kHz a 22 kHz incluindo o tom mosquito de 17.4 kHz, com slider manual e volume seguro.';
?>
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('hearing-age-test.php'); ?>">
  <link rel="alternate" hreflang="pt" href="<?php echo absoluteUrl('languages/portuguese/hearing-age-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('hearing-age-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('hearing_age_test', [['name'=>'Home','url'=>'/'],['name'=>'Teste de Idade Auditiva - Que Idade Tem Seus Ouvidos?','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-pt.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de áudio</p>
          <h1 class="hero-title">Teste de Idade Auditiva - Que Idade Tem Seus Ouvidos?</h1>
          <p class="hero-lede">Teste viral de idade auditiva com 12 frequencias de 8 kHz a 22 kHz, incluindo o tom mosquito de 17.4 kHz. Use fones com fio para resultados precisos.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#hearing-age-test">Iniciar teste</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas as ferramentas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/hearing-age-test/hero.jpg'); ?>" width="1200" height="800" alt="Teste de Idade Auditiva - Que Idade Tem Seus Ouvidos?" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="hearing-age-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Ferramenta principal</p>
          <h2>Teste de Idade Auditiva</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/hearing_age_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/hearing-age-test.php'; ?>
    <?php $currentTool = 'audio'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/hearing-age-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-pt.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
