<?php
/**
 * portuguese localized landing page for minecraft-circle-generator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-pt.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Gerador de círculos Minecraft - Contorno, disco e esfera';
$pageDescription = 'Gerador de círculos em pixels para Minecraft: contorno, preenchido, anel grosso e camadas de esfera. Raio 1 a 256.';
?>
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('minecraft-circle-generator.php'); ?>">
  <link rel="alternate" hreflang="pt" href="<?php echo absoluteUrl('languages/portuguese/minecraft-circle-generator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('minecraft-circle-generator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('minecraft_circle', [['name'=>'Home','url'=>'/'],['name'=>'Gerador de círculos Minecraft','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-pt.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Utilitário de gaming</p>
          <h1 class="hero-title">Gerador de círculos Minecraft</h1>
          <p class="hero-lede">Desenha círculos perfeitos, discos preenchidos, anéis grossos e camadas de esfera 3D com raio 1 a 256 blocos. Conta blocos, baixa PNG para consulta no outro monitor e copia o padrão camada a camada no jogo.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#minecraft-circle-generator">Traçar círculo</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas as ferramentas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/minecraft-circle-generator/hero.jpg'); ?>" width="1200" height="800" alt="Gerador de círculos Minecraft" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="minecraft-circle-generator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Ferramenta principal</p>
          <h2>Gerador de círculos Minecraft</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/minecraft_circle_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/minecraft-circle-generator.php'; ?>
    <?php $currentTool = 'mouse'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/minecraft-circle-generator.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-pt.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
