<?php
/**
 * portuguese localized landing page for monitor-sharpness-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-pt.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Teste de nitidez do monitor - Clareza do texto online';
$pageDescription = 'Teste gratuito de nitidez do monitor. Grade de 1px estilo Lagom, amostras de texto em varios tamanhos, blocos de franjas cromaticas e regua RGB de subpixel.';
?>
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('monitor-sharpness-test.php'); ?>">
  <link rel="alternate" hreflang="pt" href="<?php echo absoluteUrl('languages/portuguese/monitor-sharpness-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('monitor-sharpness-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('monitor_sharpness_test', [['name'=>'Home','url'=>'/'],['name'=>'Teste gratuito de nitidez do monitor - Clareza do texto online','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-pt.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de tela</p>
          <h1 class="hero-title">Teste gratuito de nitidez do monitor - Clareza do texto online</h1>
          <p class="hero-lede">Renderiza uma grade de 1 px estilo Lagom, amostras de texto em serif, sans e monoespacada, blocos de franjas cromaticas e uma regua RGB de subpixel para avaliar a nitidez do monitor.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#monitor-sharpness-test">Iniciar teste</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas as ferramentas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/monitor-sharpness-test/hero.jpg'); ?>" width="1200" height="800" alt="Teste gratuito de nitidez do monitor - Clareza do texto online" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="monitor-sharpness-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Ferramenta principal</p>
          <h2>Teste de nitidez do monitor</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/monitor_sharpness_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/monitor-sharpness-test.php'; ?>
    <?php $currentTool = 'screen'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/monitor-sharpness-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-pt.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
