<?php
/**
 * Portuguese localized landing page for mouse-spin-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-pt.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Teste de Giro do Mouse - Contador 360°';
$pageDescription = 'Teste de giro do mouse: conta rotações completas de 360° em sessões de 15, 30 ou 60 segundos com detecção de pico de giros por segundo. Sem instalação, em tempo real.';
?>
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('mouse-spin-test.php'); ?>">
  <link rel="alternate" hreflang="pt" href="<?php echo absoluteUrl('languages/portuguese/mouse-spin-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('mouse-spin-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-pt.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de mouse</p>
          <h1 class="hero-title">Teste de Giro do Mouse</h1>
          <p class="hero-lede">Quantas rotações completas de 360° você consegue em 30 segundos? Segure e gire em torno do centro do pad.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#mouse-spin-test">Começar a girar</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Todas as ferramentas</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="mouse-spin-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Diagnóstico de mouse</p>
          <h2>Teste de Giro do Mouse</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/mouse-spin-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-pt.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
