<?php
/**
 * portuguese localized landing page for online-ruler
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-pt.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Regua Online em Tamanho Real - cm e Polegadas com Calibracao';
$pageDescription = 'Regua online gratuita em tamanho real na tela. Meca em cm, mm e polegadas. Calibre com cartao de credito (ISO ID-1) ou inserindo o DPI do monitor.';
?>
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('online-ruler.php'); ?>">
  <link rel="alternate" hreflang="pt" href="<?php echo absoluteUrl('languages/portuguese/online-ruler.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('online-ruler.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('online_ruler', [['name'=>'Home','url'=>'/'],['name'=>'Regua Online em Tamanho Real - cm e Polegadas com Calibracao','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-pt.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Calculadora</p>
          <h1 class="hero-title">Regua Online em Tamanho Real - cm e Polegadas com Calibracao</h1>
          <p class="hero-lede">Regua SVG em cm e polegadas que voce ajusta a tela com um cartao de credito real (padrao ISO ID-1) ou seu DPI. A calibracao e salva no navegador.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#online-ruler">Abrir regua</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas as ferramentas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/online-ruler/hero.jpg'); ?>" width="1200" height="800" alt="Regua Online em Tamanho Real - cm e Polegadas com Calibracao" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="online-ruler">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Ferramenta principal</p>
          <h2>Regua Online</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/online_ruler_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/online-ruler.php'; ?>
    <?php $currentTool = 'mouse'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/online-ruler.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-pt.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
