<?php
/**
 * portuguese localized landing page for pitch-detector
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-pt.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Detector de Tom Online - Que Nota Estou Cantando?';
$pageDescription = 'Detector de tom gratuito no navegador. Cante ou toque no microfone e veja em tempo real a frequencia em Hz, a nota mais proxima (C0-C8), a oitava e os cents.';
?>
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('pitch-detector.php'); ?>">
  <link rel="alternate" hreflang="pt" href="<?php echo absoluteUrl('languages/portuguese/pitch-detector.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('pitch-detector.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('pitch_detector', [['name'=>'Home','url'=>'/'],['name'=>'Detector de Tom Online Gratis - Que Nota Estou Cantando?','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-pt.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de áudio</p>
          <h1 class="hero-title">Detector de Tom Online Gratis - Que Nota Estou Cantando?</h1>
          <p class="hero-lede">Cante, cantarole ou toque qualquer nota e veja instantaneamente a frequencia, a nota musical e os cents. Grafico dos ultimos 10 segundos.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#pitch-detector">Iniciar detector</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas as ferramentas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/pitch-detector/hero.jpg'); ?>" width="1200" height="800" alt="Detector de Tom Online Gratis - Que Nota Estou Cantando?" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="pitch-detector">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Ferramenta principal</p>
          <h2>Detector de Tom</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/pitch_detector_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'pitch-detector'; $localizedRelatedCategory = 'audio'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-pt.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
