<?php
/**
 * Portuguese localized landing page for screen-uniformity-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-pt.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Teste de Uniformidade de Tela - Clouding e IPS Glow';
$pageDescription = 'Teste de uniformidade de tela em tela cheia: cinza, preto, branco e RGB em qualquer brilho para detectar clouding, IPS glow e backlight bleed visualmente.';
?>
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('screen-uniformity-test.php'); ?>">
  <link rel="alternate" hreflang="pt" href="<?php echo absoluteUrl('languages/portuguese/screen-uniformity-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('screen-uniformity-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-pt.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de tela</p>
          <h1 class="hero-title">Teste de Uniformidade de Tela</h1>
          <p class="hero-lede">Escolha cor e brilho, entre em tela cheia e procure cantos escuros, manchas nebulosas ou desvio de tom. Cores diferentes revelam problemas diferentes.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#screen-uniformity-test">Iniciar teste</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Todas as ferramentas</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="screen-uniformity-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Diagnóstico de tela</p>
          <h2>Teste de Uniformidade de Tela</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/screen-uniformity-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-pt.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
