<?php
/**
 * portuguese localized landing page for vibration-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-pt.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Teste de vibração - Háptica do celular e rumble do gamepad';
$pageDescription = 'Teste a Vibration API do celular com padrões (pulso, SOS, batida) e o rumble do gamepad com sliders por motor.';
?>
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('vibration-test.php'); ?>">
  <link rel="alternate" hreflang="pt" href="<?php echo absoluteUrl('languages/portuguese/vibration-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('vibration-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('vibration_test', [['name'=>'Home','url'=>'/'],['name'=>'Teste de vibração','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-pt.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Sensor do dispositivo</p>
          <h1 class="hero-title">Teste de vibração</h1>
          <p class="hero-lede">Testa a vibração do celular (Vibration API) com padrões predefinidos e o rumble do controle com sliders por motor. Tudo no navegador, sem instalação.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#vibration-test">Iniciar vibração</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas as ferramentas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/vibration-test/hero.jpg'); ?>" width="1200" height="800" alt="Teste de vibração" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="vibration-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Ferramenta principal</p>
          <h2>Teste de vibração</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/vibration_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'vibration-test'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-pt.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
