<?php
/**
 * arabic localized landing page for auditory-reaction-time-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ar.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'اختبار زمن رد الفعل السمعي - الاستجابة للصوت';
$pageDescription = 'اختبر زمن رد فعلك على نغمة باستخدام Web Audio API. 5 جولات مع متوسط وأفضل وأسوأ وكشف البدء المبكر.';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('auditory-reaction-time-test.php'); ?>">
  <link rel="alternate" hreflang="ar" href="<?php echo absoluteUrl('languages/arabic/auditory-reaction-time-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('auditory-reaction-time-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('auditory_reaction_time', [['name'=>'Home','url'=>'/'],['name'=>'اختبار زمن رد الفعل السمعي','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ar.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">تشخيص الصوت</p>
          <h1 class="hero-title">اختبار زمن رد الفعل السمعي</h1>
          <p class="hero-lede">يقيس بالمللي ثانية سرعة استجابتك لنغمة. يصدر الصفير بعد تأخير عشوائي من 1.5 إلى 4 ثوان. المتوسط والأفضل والأسوأ عبر 5 جولات وكشف البدء المبكر.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#auditory-reaction-time-test">ابدأ الاختبار</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">تصفح جميع الأدوات</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/auditory-reaction-time-test/hero.jpg'); ?>" width="1200" height="800" alt="اختبار زمن رد الفعل السمعي" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="auditory-reaction-time-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">الأداة الرئيسية</p>
          <h2>اختبار زمن رد الفعل السمعي</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/auditory_reaction_time_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'auditory-reaction-time-test'; $localizedRelatedCategory = 'audio'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ar.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
