<?php
/**
 * arabic localized landing page for download-time-calculator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ar.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'حاسبة وقت التنزيل - الألعاب والأفلام والنسخ الاحتياطية';
$pageDescription = 'تقدر وقت تنزيل الألعاب والأفلام والنسخ الاحتياطية بناءً على سرعتك. أكثر من 15 إعداداً مسبقاً وتقديرات نظرية وواقعية وبطيئة.';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('download-time-calculator.php'); ?>">
  <link rel="alternate" hreflang="ar" href="<?php echo absoluteUrl('languages/arabic/download-time-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('download-time-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('download_time_calc', [['name'=>'Home','url'=>'/'],['name'=>'حاسبة وقت التنزيل','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ar.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">حاسبة</p>
          <h1 class="hero-title">حاسبة وقت التنزيل</h1>
          <p class="hero-lede">اختر إعداداً مسبقاً (لعبة AAA، فيلم 4K، ISO لينكس، نسخة Steam) أو أدخل حجماً مخصصاً، واحصل على الوقت بصيغة Xh Ym Zs مع تقديرات واقعية 85% ونظرية 100% وشبكة بطيئة 60%.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#download-time-calculator">تقدير</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">تصفح جميع الأدوات</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/download-time-calculator/hero.jpg'); ?>" width="1200" height="800" alt="حاسبة وقت التنزيل" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="download-time-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">الأداة الرئيسية</p>
          <h2>حاسبة وقت التنزيل</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/download_time_calc_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'download-time-calculator'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ar.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
