<?php
/**
 * Arabic localized landing page for edpi-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ar.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'حاسبة eDPI - DPI الفعال لألعاب FPS';
$pageDescription = 'حاسبة eDPI مجانية: تحسب DPI الفعّال (DPI × الحساسية) وcm/360 لـ CS2 وValorant وApex وOverwatch وألعاب FPS الأخرى. مع إعدادات yaw مسبقة لكل لعبة.';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('edpi-calculator.php'); ?>">
  <link rel="alternate" hreflang="ar" href="<?php echo absoluteUrl('languages/arabic/edpi-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('edpi-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ar.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">حاسبات الحساسية</p>
          <h1 class="hero-title">حاسبة eDPI - DPI الفعال</h1>
          <p class="hero-lede">احسب DPI الفعال (eDPI = DPI × الحساسية) لمقارنة التصويب بين CS2 وValorant وApex. يشمل تحويل cm/360.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#edpi-calculator">احسب eDPI</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">كل الأدوات</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="edpi-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">حاسبات الحساسية</p>
          <h2>حاسبة eDPI - DPI الفعال</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/edpi-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ar.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
