<?php
/**
 * Arabic localized landing page for fps-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ar.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'اختبار FPS - معدل إطارات المتصفح';
$pageDescription = 'اختبار FPS عبر الإنترنت: قياس مباشر لمعدل إطارات المتصفح مع المعدل والأدنى والأقصى و1% الأسوأ، واكتشاف تلقائي لـ60/120/144/240 هرتز. بدون تثبيت.';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('fps-test.php'); ?>">
  <link rel="alternate" hreflang="ar" href="<?php echo absoluteUrl('languages/arabic/fps-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('fps-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ar.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">تشخيص الأداء</p>
          <h1 class="hero-title">اختبار FPS</h1>
          <p class="hero-lede">قياس معدل إطارات المتصفح لحظيًا عبر requestAnimationFrame. يعرض FPS الحالي والمتوسط والأدنى والأقصى و1%-low.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#fps-test">ابدأ الاختبار</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">كل الأدوات</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="fps-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">تشخيص الأداء</p>
          <h2>اختبار FPS</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/fps-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ar.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
