<?php
/**
 * arabic localized landing page for gpu-stress-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ar.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'اختبار إجهاد GPU - قياس أداء شادر WebGL';
$pageDescription = 'شادر جزيئي لمندلبرو في WebGL2 لإجهاد أي GPU. يقدم FPS وأدنى FPS ويكتشف التراجع إلى الرسم البرمجي.';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('gpu-stress-test.php'); ?>">
  <link rel="alternate" hreflang="ar" href="<?php echo absoluteUrl('languages/arabic/gpu-stress-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('gpu-stress-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('gpu_stress_test', [['name'=>'Home','url'=>'/'],['name'=>'اختبار إجهاد GPU','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ar.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">اختبار الأداء</p>
          <h1 class="hero-title">اختبار إجهاد GPU</h1>
          <p class="hero-lede">يرسم شادر جزيئي Mandelbrot عالي التكرار في WebGL2 لتحميل أي GPU. يقدم FPS اللحظي ومتوسط الثانية وأدنى FPS، ويكتشف الرسم البرمجي (SwiftShader).</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#gpu-stress-test">ابدأ الإجهاد</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">تصفح جميع الأدوات</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/gpu-stress-test/hero.jpg'); ?>" width="1200" height="800" alt="اختبار إجهاد GPU" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="gpu-stress-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">الأداة الرئيسية</p>
          <h2>اختبار إجهاد GPU</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/gpu_stress_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/gpu-stress-test.php'; ?>
    <?php $currentTool = 'screen'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/gpu-stress-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ar.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
