<?php
/**
 * arabic localized landing page for gyroscope-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ar.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'اختبار الجيروسكوب - اتجاه الهاتف';
$pageDescription = 'قراءة ألفا وبيتا وجاما للجيروسكوب مع مكعب ثلاثي الأبعاد وحلقة بوصلة ومعايرة إلى الصفر.';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('gyroscope-test.php'); ?>">
  <link rel="alternate" hreflang="ar" href="<?php echo absoluteUrl('languages/arabic/gyroscope-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('gyroscope-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('gyroscope_test', [['name'=>'Home','url'=>'/'],['name'=>'اختبار الجيروسكوب','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ar.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">مستشعر الجهاز</p>
          <h1 class="hero-title">اختبار الجيروسكوب</h1>
          <p class="hero-lede">يقرأ الجيروسكوب في هاتفك أو جهازك اللوحي. يعرض ألفا وبيتا وجاما بالدرجات، مكعباً ثلاثي الأبعاد، حلقة بوصلة، وزرّاً لمعايرة الوضع الحالي إلى صفر.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#gyroscope-test">ابدأ الجيروسكوب</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">تصفح جميع الأدوات</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/gyroscope-test/hero.jpg'); ?>" width="1200" height="800" alt="اختبار الجيروسكوب" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="gyroscope-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">الأداة الرئيسية</p>
          <h2>اختبار الجيروسكوب</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/gyroscope_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'gyroscope-test'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ar.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
