<?php
/**
 * arabic localized landing page for hearing-age-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ar.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'اختبار عمر السمع - نغمة البعوضة (كم عمر اذنيك؟)';
$pageDescription = 'اختبار مجاني لعمر السمع. مسح 12 ترددا من 8 كيلوهرتز الى 22 كيلوهرتز بما في ذلك نغمة البعوضة 17.4 كيلوهرتز، مع شريط تمرير يدوي وحجم آمن.';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('hearing-age-test.php'); ?>">
  <link rel="alternate" hreflang="ar" href="<?php echo absoluteUrl('languages/arabic/hearing-age-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('hearing-age-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('hearing_age_test', [['name'=>'Home','url'=>'/'],['name'=>'اختبار عمر السمع - كم عمر اذنيك؟','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ar.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">تشخيص الصوت</p>
          <h1 class="hero-title">اختبار عمر السمع - كم عمر اذنيك؟</h1>
          <p class="hero-lede">اختبار شائع لعمر السمع مع 12 ترددا من 8 كيلوهرتز الى 22 كيلوهرتز، بما في ذلك نغمة البعوضة 17.4 كيلوهرتز. استخدم سماعات سلكية للحصول على نتائج دقيقة.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#hearing-age-test">ابدا الاختبار</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">تصفح جميع الأدوات</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/hearing-age-test/hero.jpg'); ?>" width="1200" height="800" alt="اختبار عمر السمع - كم عمر اذنيك؟" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="hearing-age-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">الأداة الرئيسية</p>
          <h2>اختبار عمر السمع</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/hearing_age_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/hearing-age-test.php'; ?>
    <?php $currentTool = 'audio'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/hearing-age-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ar.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
