<?php
/**
 * arabic localized landing page for raid-calculator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ar.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'حاسبة RAID - السعة وتحمل الأعطال';
$pageDescription = 'السعة القابلة للاستخدام وتحمل الأعطال ومضاعفات سرعة القراءة/الكتابة لـ RAID 0 و 1 و 5 و 6 و 10 و 50 و 60.';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('raid-calculator.php'); ?>">
  <link rel="alternate" hreflang="ar" href="<?php echo absoluteUrl('languages/arabic/raid-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('raid-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('raid_calc', [['name'=>'Home','url'=>'/'],['name'=>'حاسبة RAID','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ar.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">حاسبة</p>
          <h1 class="hero-title">حاسبة RAID</h1>
          <p class="hero-lede">اختر مستوى RAID (0، 1، 5، 6، 10، 50، 60)، أدخل عدد الأقراص وحجمها، واحصل على السعة القابلة للاستخدام وعدد الأقراص التي يمكن أن تفشل ومضاعفات السرعة &mdash; مع جدول مقارنة.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#raid-calculator">احسب RAID</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">تصفح جميع الأدوات</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/raid-calculator/hero.jpg'); ?>" width="1200" height="800" alt="حاسبة RAID" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="raid-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">الأداة الرئيسية</p>
          <h2>حاسبة RAID</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/raid_calc_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'raid-calculator'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ar.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
