<?php
/**
 * arabic localized landing page for ram-latency-calculator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ar.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'حاسبة زمن انتقال الذاكرة - CAS إلى النانو ثانية';
$pageDescription = 'تحول زمن CAS (CL) والسرعة (MT/s) إلى نانو ثانية حقيقية. قارن بين كيتات DDR4 و DDR5 جنباً إلى جنب.';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('ram-latency-calculator.php'); ?>">
  <link rel="alternate" hreflang="ar" href="<?php echo absoluteUrl('languages/arabic/ram-latency-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('ram-latency-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('ram_latency_calc', [['name'=>'Home','url'=>'/'],['name'=>'حاسبة زمن انتقال الذاكرة','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ar.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">حاسبة</p>
          <h1 class="hero-title">حاسبة زمن انتقال الذاكرة</h1>
          <p class="hero-lede">تحول CL و MT/s إلى نانو ثانية حقيقية باستخدام الصيغة ns = (CL × 2000) / MT/s. قارن كيتين من DDR4 أو DDR5 جنباً إلى جنب أو احسب بالعكس: ما هو CL اللازم لهدف بالنانو ثانية.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#ram-latency-calculator">احسب</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">تصفح جميع الأدوات</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/ram-latency-calculator/hero.jpg'); ?>" width="1200" height="800" alt="حاسبة زمن انتقال الذاكرة" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="ram-latency-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">الأداة الرئيسية</p>
          <h2>حاسبة زمن انتقال الذاكرة</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/ram_latency_calc_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/ram-latency-calculator.php'; ?>
    <?php $currentTool = 'mouse'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/ram-latency-calculator.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ar.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
