<?php
/**
 * Arabic localized landing page for resolution-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ar.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'اختبار دقة الشاشة - الدقة وDPR وعمق الألوان';
$pageDescription = 'اختبار دقة الشاشة: قراءة مباشرة للدقة والبكسل الأصلي ونسبة البكسل الرقمي وعمق الألوان ونطاق الألوان. يتحقق من الإخراج الفعلي للشاشة فورًا.';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('resolution-test.php'); ?>">
  <link rel="alternate" hreflang="ar" href="<?php echo absoluteUrl('languages/arabic/resolution-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('resolution-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ar.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">تشخيص الشاشة</p>
          <h1 class="hero-title">اختبار دقة الشاشة</h1>
          <p class="hero-lede">قراءة فورية لكل خصائص الشاشة: الدقة CSS والبكسلات الأصلية وDPR وعمق الألوان والنطاق والعرض والاتجاه ونسبة العرض. يتحدث عند تغيير الحجم.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#resolution-test">اعرض دقتي</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">كل الأدوات</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="resolution-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">تشخيص الشاشة</p>
          <h2>اختبار دقة الشاشة</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/resolution-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ar.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
