<?php
/**
 * Arabic localized landing page for sound-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ar.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'اختبار الصوت - اختبار قنوات السماعات والأذن';
$pageDescription = 'اختبار الصوت المجاني: يتحقق من قنوات السماعات والأذن اليسرى/اليمنى، بالإضافة إلى مسح تردد من 100 هرتز إلى 10 كيلوهرتز. بدون تثبيت، في المتصفح.';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('sound-test.php'); ?>">
  <link rel="alternate" hreflang="ar" href="<?php echo absoluteUrl('languages/arabic/sound-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('sound-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ar.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">تشخيص الصوت</p>
          <h1 class="hero-title">اختبار الصوت</h1>
          <p class="hero-lede">تحقق من قنواتك اليسرى واليمنى والستيريو بنغمات جيبية نقية. وضع بينج-بونج لمقارنة السماعتين. مسح 100 هرتز → 10 كيلو هرتز لنطاق التردد.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#sound-test">ابدأ اختبار الصوت</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">كل الأدوات</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="sound-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">تشخيص الصوت</p>
          <h2>اختبار الصوت</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/sound-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ar.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
