<?php
/**
 * Arabic localized landing page for viewing-distance-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ar.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'حاسبة مسافة المشاهدة للتلفاز والشاشة';
$pageDescription = 'حاسبة مسافة المشاهدة: المسافة المثلى للتلفاز/الشاشة وفق THX (36° FoV) وSMPTE (30° FoV) وحد التمييز 4K/8K. بالقدم والمتر، مجانية في المتصفح.';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('viewing-distance-calculator.php'); ?>">
  <link rel="alternate" hreflang="ar" href="<?php echo absoluteUrl('languages/arabic/viewing-distance-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('viewing-distance-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ar.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">حاسبات الشاشة</p>
          <h1 class="hero-title">حاسبة مسافة المشاهدة</h1>
          <p class="hero-lede">على أي مسافة تجلس من التلفاز أو الشاشة؟ THX (36° FoV غامر)، SMPTE (30° سينما)، والحد الأقصى لدقة 4K/8K.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#viewing-distance-calculator">افتح الحاسبة</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">كل الأدوات</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="viewing-distance-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">حاسبات الشاشة</p>
          <h2>حاسبة مسافة المشاهدة</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/viewing-distance-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ar.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
