<?php
/**
 * spanish localized landing page for accelerometer-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Prueba de acelerómetro - Sensor de movimiento del móvil';
$pageDescription = 'Lectura en vivo del acelerómetro del móvil o tablet con cubo 3D, detector de agitación y visualización de aceleración XYZ.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('accelerometer-test.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/accelerometer-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('accelerometer-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('accelerometer_test', [['name'=>'Home','url'=>'/'],['name'=>'Prueba de acelerómetro','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Sensor del dispositivo</p>
          <h1 class="hero-title">Prueba de acelerómetro</h1>
          <p class="hero-lede">Lee en vivo el acelerómetro de tu móvil o tablet (DeviceMotionEvent). Muestra XYZ en m/s², orientación con un cubo 3D y un contador de sacudidas. iOS pide permiso explícito.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#accelerometer-test">Iniciar sensor</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/accelerometer-test/hero.jpg'); ?>" width="1200" height="800" alt="Prueba de acelerómetro" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="accelerometer-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Herramienta principal</p>
          <h2>Prueba de acelerómetro</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/accelerometer_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'accelerometer-test'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
