<?php
/**
 * Spanish localized landing page for aspect-ratio-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Calculadora de Relación de Aspecto - Ancho, Alto o Ratio';
$pageDescription = 'Calculadora de relación de aspecto gratuita: introduce dos de ancho, alto o ratio (16:9, 21:9, 4:3) y simplifica automáticamente a enteros con vista previa en vivo.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('aspect-ratio-calculator.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/aspect-ratio-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('aspect-ratio-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Calculadoras de pantalla</p>
          <h1 class="hero-title">Calculadora de Relación de Aspecto</h1>
          <p class="hero-lede">Introduce dos de tres: ancho, alto o ratio. Simplifica automáticamente a enteros (1920×1080 → 16:9) y muestra una vista previa en vivo.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#aspect-ratio-calculator">Abrir calculadora</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="aspect-ratio-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Calculadoras de pantalla</p>
          <h2>Calculadora de Relación de Aspecto</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/aspect-ratio-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
