<?php
/**
 * spanish localized landing page for auditory-reaction-time-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Prueba de tiempo de reacción auditiva - Respuesta a un sonido';
$pageDescription = 'Prueba tu tiempo de reacción a un tono con la Web Audio API. 5 rondas con media, mejor, peor y detección de salida en falso.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('auditory-reaction-time-test.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/auditory-reaction-time-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('auditory-reaction-time-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('auditory_reaction_time', [['name'=>'Home','url'=>'/'],['name'=>'Prueba de tiempo de reacción auditiva','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de audio</p>
          <h1 class="hero-title">Prueba de tiempo de reacción auditiva</h1>
          <p class="hero-lede">Mide en milisegundos cuán rápido reaccionas a un tono. Un beep suena tras un retardo aleatorio de 1.5 a 4 segundos. Informa media, mejor y peor a lo largo de 5 rondas. Detecta clics antes de tiempo.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#auditory-reaction-time-test">Iniciar prueba</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/auditory-reaction-time-test/hero.jpg'); ?>" width="1200" height="800" alt="Prueba de tiempo de reacción auditiva" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="auditory-reaction-time-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Herramienta principal</p>
          <h2>Prueba de reacción auditiva</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/auditory_reaction_time_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/auditory-reaction-time-test.php'; ?>
    <?php $currentTool = 'audio'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/auditory-reaction-time-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
