<?php
/**
 * Spanish localized landing page for burn-in-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Prueba de Burn-In OLED - Retención de Imagen';
$pageDescription = 'Prueba de burn-in OLED: cicla 8 colores sólidos, tablero fino y refresco móvil en pantalla completa para detectar retención de imagen y quemado en pantallas OLED.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('burn-in-test.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/burn-in-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('burn-in-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de pantalla</p>
          <h1 class="hero-title">Prueba de Burn-In OLED</h1>
          <p class="hero-lede">Detecta retención de imagen y burn-in en tu pantalla. Ciclo de 8 colores sólidos, tablero fino para subpíxeles atascados, y refrescador en movimiento que puede recuperar retención leve si se deja durante la noche.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#burn-in-test">Iniciar prueba</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="burn-in-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Diagnóstico de pantalla</p>
          <h2>Prueba de Burn-In OLED</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/burn-in-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
