<?php
/**
 * Spanish localized landing page for edpi-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Calculadora de eDPI - DPI Efectivo para FPS';
$pageDescription = 'Calculadora de eDPI gratuita: calcula DPI efectivo (DPI × sensibilidad) y cm/360 para CS2, Valorant, Apex, Overwatch y otros shooters. Incluye presets de yaw por juego.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('edpi-calculator.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/edpi-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('edpi-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Calculadoras de sensibilidad</p>
          <h1 class="hero-title">Calculadora de eDPI - DPI Efectivo para FPS</h1>
          <p class="hero-lede">Calcula tu DPI efectivo (eDPI = DPI x sensibilidad) para comparar la puntería en CS2, Valorant, Apex y otros FPS. Incluye conversión cm/360.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#edpi-calculator">Calcular eDPI</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="edpi-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Calculadoras de sensibilidad</p>
          <h2>Calculadora de eDPI - DPI Efectivo para FPS</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/edpi-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
