<?php
/**
 * spanish localized landing page for frame-skipping-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Prueba de frames saltados - Detecta frames perdidos';
$pageDescription = 'Detecta frames saltados o perdidos en tu frecuencia de refresco mediante análisis de rAF timestamp. Auto-calibra tu Hz.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('frame-skipping-test.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/frame-skipping-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('frame-skipping-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('frame_skipping_test', [['name'=>'Home','url'=>'/'],['name'=>'Prueba de frames saltados','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de pantalla</p>
          <h1 class="hero-title">Prueba de frames saltados</h1>
          <p class="hero-lede">Detecta frames saltados o perdidos mediante análisis de timestamps de requestAnimationFrame. Auto-calibra tu frecuencia de refresco y marca como skip cualquier frame > 1.5x el intervalo esperado.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#frame-skipping-test">Iniciar prueba</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/frame-skipping-test/hero.jpg'); ?>" width="1200" height="800" alt="Prueba de frames saltados" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="frame-skipping-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Herramienta principal</p>
          <h2>Prueba de frames saltados</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/frame_skipping_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/frame-skipping-test.php'; ?>
    <?php $currentTool = 'screen'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/frame-skipping-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
