<?php
/**
 * spanish localized landing page for frequency-response-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Prueba de respuesta en frecuencia - Barrido 20 Hz a 20 kHz';
$pageDescription = 'Barrido de audio de 20 Hz a 20 kHz con marcas de paso para encontrar los límites de audición y evaluar auriculares o monitores.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('frequency-response-test.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/frequency-response-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('frequency-response-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('frequency_response_test', [['name'=>'Home','url'=>'/'],['name'=>'Prueba de respuesta en frecuencia','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de audio</p>
          <h1 class="hero-title">Prueba de respuesta en frecuencia</h1>
          <p class="hero-lede">Barrido de 20 Hz a 20 kHz con presets ISO de tercio de octava. Detecta los límites de tu audición y la respuesta real de tus auriculares o altavoces. Ondas senoidales puras generadas localmente en el navegador.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#frequency-response-test">Iniciar prueba</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/frequency-response-test/hero.jpg'); ?>" width="1200" height="800" alt="Prueba de respuesta en frecuencia" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="frequency-response-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Herramienta principal</p>
          <h2>Prueba de respuesta en frecuencia</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/frequency_response_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'frequency-response-test'; $localizedRelatedCategory = 'audio'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
