<?php
/**
 * spanish localized landing page for gpu-stress-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Prueba de estrés de GPU - Benchmark de shader WebGL';
$pageDescription = 'Shader fragment Mandelbrot en WebGL2 para estresar cualquier GPU. Reporta FPS, FPS mínimo y detecta fallback a software rendering.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('gpu-stress-test.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/gpu-stress-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('gpu-stress-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('gpu_stress_test', [['name'=>'Home','url'=>'/'],['name'=>'Prueba de estrés de GPU','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Benchmark de hardware</p>
          <h1 class="hero-title">Prueba de estrés de GPU</h1>
          <p class="hero-lede">Renderiza un shader fragment Mandelbrot de alta iteración en WebGL2 para cargar cualquier GPU. Reporta FPS instantáneo, media de 1s, FPS mínimo y detecta si estás usando renderizado por software (SwiftShader).</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#gpu-stress-test">Iniciar estrés</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/gpu-stress-test/hero.jpg'); ?>" width="1200" height="800" alt="Prueba de estrés de GPU" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="gpu-stress-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Herramienta principal</p>
          <h2>Prueba de estrés de GPU</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/gpu_stress_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'gpu-stress-test'; $localizedRelatedCategory = 'screen'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
