<?php
/**
 * spanish localized landing page for guild-name-generator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Generador de nombres de clan - Nombres de guild para MMO';
$pageDescription = 'Generador de nombres de clan y guild MMO en 6 temáticas y 5 plantillas, con límites de WoW, FFXIV, Destiny y Discord.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('guild-name-generator.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/guild-name-generator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('guild-name-generator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('guild_name_generator', [['name'=>'Home','url'=>'/'],['name'=>'Generador de nombres de clan','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Utilidad de gaming</p>
          <h1 class="hero-title">Generador de nombres de clan</h1>
          <p class="hero-lede">Genera 10 nombres de guild aleatorios en 6 temáticas (fantasía, sci-fi, oscura, noble, rogue, mítica) con plantillas como "Orden de X", "Casa de X" o "Los X". Copia con un clic y guarda favoritos.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#guild-name-generator">Generar nombres</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/guild-name-generator/hero.jpg'); ?>" width="1200" height="800" alt="Generador de nombres de clan" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="guild-name-generator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Herramienta principal</p>
          <h2>Generador de nombres de clan</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/guild_name_generator_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/guild-name-generator.php'; ?>
    <?php $currentTool = 'mouse'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/guild-name-generator.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
