<?php
/**
 * spanish localized landing page for hearing-age-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Test de Edad Auditiva - Tono Mosquito (Cuantos Anos Tienen Tus Oidos?)';
$pageDescription = 'Test de edad auditiva gratis. Barrido de 12 frecuencias de 8 kHz a 22 kHz incluyendo el tono mosquito de 17.4 kHz, con slider manual y volumen seguro.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('hearing-age-test.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/hearing-age-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('hearing-age-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('hearing_age_test', [['name'=>'Home','url'=>'/'],['name'=>'Test de Edad Auditiva - Cuantos Anos Tienen Tus Oidos?','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de audio</p>
          <h1 class="hero-title">Test de Edad Auditiva - Cuantos Anos Tienen Tus Oidos?</h1>
          <p class="hero-lede">Test viral de edad auditiva con 12 frecuencias de 8 kHz a 22 kHz, incluido el tono mosquito de 17.4 kHz. Para resultados precisos, usa auriculares con cable.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#hearing-age-test">Iniciar test</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/hearing-age-test/hero.jpg'); ?>" width="1200" height="800" alt="Test de Edad Auditiva - Cuantos Anos Tienen Tus Oidos?" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="hearing-age-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Herramienta principal</p>
          <h2>Test de Edad Auditiva</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/hearing_age_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'hearing-age-test'; $localizedRelatedCategory = 'audio'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
