<?php
/**
 * Spanish localized landing page for mouse-spin-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Prueba de Giro del Ratón - Contador de Rotaciones 360°';
$pageDescription = 'Prueba de giro del ratón: cuenta rotaciones completas de 360° en sesiones de 15, 30 o 60 segundos con detección de pico de giros por segundo. Sin instalación, en vivo.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('mouse-spin-test.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/mouse-spin-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('mouse-spin-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de ratón</p>
          <h1 class="hero-title">Prueba de Giro del Ratón</h1>
          <p class="hero-lede">¿Cuántas rotaciones completas de 360° puedes hacer con el ratón en 30 segundos? Mantén y arrastra alrededor del centro — cada 360° cuenta.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#mouse-spin-test">Empezar a girar</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="mouse-spin-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Diagnóstico de ratón</p>
          <h2>Prueba de Giro del Ratón</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/mouse-spin-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
