<?php
/**
 * spanish localized landing page for pitch-detector
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Detector de Tono Online - Que Nota Estoy Cantando?';
$pageDescription = 'Detector de tono gratis online. Canta o toca al microfono y ve la frecuencia en Hz, la nota mas cercana (C0-C8), la octava y los cents desafinados en tiempo real.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('pitch-detector.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/pitch-detector.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('pitch-detector.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('pitch_detector', [['name'=>'Home','url'=>'/'],['name'=>'Detector de Tono Online - Que Nota Estoy Cantando?','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de audio</p>
          <h1 class="hero-title">Detector de Tono Online - Que Nota Estoy Cantando?</h1>
          <p class="hero-lede">Canta, tararea o toca cualquier nota y ve al instante la frecuencia, la nota musical y los cents desafinados. Grafico desplazable de los ultimos 10 segundos.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#pitch-detector">Iniciar detector</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/pitch-detector/hero.jpg'); ?>" width="1200" height="800" alt="Detector de Tono Online - Que Nota Estoy Cantando?" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="pitch-detector">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Herramienta principal</p>
          <h2>Detector de Tono</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/pitch_detector_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'pitch-detector'; $localizedRelatedCategory = 'audio'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
