<?php
/**
 * spanish localized landing page for raid-calculator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Calculadora RAID - Capacidad y tolerancia a fallos (0/1/5/6/10/50/60)';
$pageDescription = 'Capacidad útil, tolerancia a fallos y multiplicadores de lectura/escritura para RAID 0, 1, 5, 6, 10, 50 y 60.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('raid-calculator.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/raid-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('raid-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('raid_calc', [['name'=>'Home','url'=>'/'],['name'=>'Calculadora RAID','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Calculadora</p>
          <h1 class="hero-title">Calculadora RAID</h1>
          <p class="hero-lede">Elige un nivel de RAID (0, 1, 5, 6, 10, 50, 60), introduce número de discos y tamaño, y obtén capacidad útil, cuántos discos pueden fallar sin perder datos y factores de velocidad lectura/escritura &mdash; con tabla comparativa.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#raid-calculator">Calcular RAID</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/raid-calculator/hero.jpg'); ?>" width="1200" height="800" alt="Calculadora RAID" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="raid-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Herramienta principal</p>
          <h2>Calculadora RAID</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/raid_calc_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'raid-calculator'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
