<?php
/**
 * Spanish localized landing page for screen-uniformity-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Prueba de Uniformidad de Pantalla - Nubes y IPS Glow';
$pageDescription = 'Prueba de uniformidad de pantalla a pantalla completa: gris, negro, blanco y RGB a cualquier brillo para detectar clouding, IPS glow y backlight bleed visualmente.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('screen-uniformity-test.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/screen-uniformity-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('screen-uniformity-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de pantalla</p>
          <h1 class="hero-title">Prueba de Uniformidad de Pantalla</h1>
          <p class="hero-lede">Elige un color y brillo, entra en pantalla completa y busca esquinas oscuras, manchas nubladas o desviación de tono en tu monitor. Diferentes colores revelan diferentes problemas.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#screen-uniformity-test">Iniciar prueba</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="screen-uniformity-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Diagnóstico de pantalla</p>
          <h2>Prueba de Uniformidad de Pantalla</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/screen-uniformity-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
