<?php
/**
 * Spanish localized landing page for screen-size-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Calculadora de Tamaño de Pantalla - Diagonal, Ancho, Alto';
$pageDescription = 'Calculadora de tamaño de pantalla: calcula diagonal, ancho, alto y área visible desde la relación de aspecto y una sola medida — en pulgadas y centímetros. Gratuita, al instante.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('screen-size-calculator.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/screen-size-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('screen-size-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Calculadoras de pantalla</p>
          <h1 class="hero-title">Calculadora de Tamaño de Pantalla</h1>
          <p class="hero-lede">Introduce la relación de aspecto y una medida (diagonal, ancho o alto). La herramienta calcula las otras dos en pulgadas y cm, más el área visible.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#screen-size-calculator">Abrir calculadora</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="screen-size-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Calculadoras de pantalla</p>
          <h2>Calculadora de Tamaño de Pantalla</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/screen-size-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
