<?php
/**
 * Spanish localized landing page for sound-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Prueba de Sonido - Test de Canales de Altavoz y Auriculares';
$pageDescription = 'Prueba de sonido gratuita: verifica canales izquierdo/derecho de altavoces y auriculares, más barrido de frecuencia 100 Hz → 10 kHz. Sin instalación, en navegador.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('sound-test.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/sound-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('sound-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Diagnóstico de audio</p>
          <h1 class="hero-title">Prueba de Sonido</h1>
          <p class="hero-lede">Verifica tus canales izquierdo, derecho y estéreo con tonos sinusoidales puros. Usa el modo ping-pong para comparar los dos altavoces. Barrido de 100 Hz a 10 kHz para rango de frecuencia.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#sound-test">Iniciar prueba de sonido</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="sound-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Diagnóstico de audio</p>
          <h2>Prueba de Sonido</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/sound-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
