<?php
/**
 * spanish localized landing page for ttk-calculator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Calculadora de TTK - Tiempo hasta matar en FPS';
$pageDescription = 'TTK (tiempo hasta matar) en milisegundos para CS2, Valorant, Apex y Call of Duty. Balas para matar y comparación cuerpo vs cabeza.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('ttk-calculator.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/ttk-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('ttk-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('ttk_calc', [['name'=>'Home','url'=>'/'],['name'=>'Calculadora de TTK','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Utilidad de gaming</p>
          <h1 class="hero-title">Calculadora de TTK</h1>
          <p class="hero-lede">Introduce daño, cadencia (RPM), HP del objetivo, armadura y multiplicador de headshot; la calculadora devuelve balas para matar y TTK en milisegundos para cuerpo y cabeza, lado a lado. Con presets para CS2, Valorant, Apex, CoD.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#ttk-calculator">Calcular TTK</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/ttk-calculator/hero.jpg'); ?>" width="1200" height="800" alt="Calculadora de TTK" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="ttk-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Herramienta principal</p>
          <h2>Calculadora de TTK</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/ttk_calc_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'ttk-calculator'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
