<?php
/**
 * Spanish localized landing page for viewing-distance-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-es.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Calculadora de Distancia de Visión - TV y Monitor';
$pageDescription = 'Calculadora de distancia de visualización: distancia óptima de TV/monitor según THX (36° FoV), SMPTE (30° FoV) y el límite de resolución 4K/8K. En pies y metros.';
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('viewing-distance-calculator.php'); ?>">
  <link rel="alternate" hreflang="es" href="<?php echo absoluteUrl('languages/spanish/viewing-distance-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('viewing-distance-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-es.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Calculadoras de pantalla</p>
          <h1 class="hero-title">Calculadora de Distancia de Visión</h1>
          <p class="hero-lede">¿A qué distancia sentarte de tu TV o monitor? THX (36° FoV inmersivo), SMPTE (30° cine) y la distancia máxima de resolución 4K/8K.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#viewing-distance-calculator">Abrir calculadora</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Ver todas las herramientas</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="viewing-distance-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Calculadoras de pantalla</p>
          <h2>Calculadora de Distancia de Visión</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/viewing-distance-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-es.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
