<?php
// Localized labels for apm-test — auto-generated by generate-locale-wrappers.py
$apm_labels = [
    'aria' => 'Prueba de APM - contador de acciones por minuto',
    'instruction' => 'Pulsa Iniciar, haz foco en el pad y realiza tus acciones normales (clics, hotkeys, arrastres). Cada clic o pulsacion cuenta como una accion.',
    'start' => 'Iniciar',
    'stop' => 'Detener',
    'reset' => 'Reiniciar',
    'current_apm' => 'APM actual',
    'peak_apm' => 'Pico de APM',
    'avg_apm' => 'Promedio de sesion',
    'total_actions' => 'Acciones totales',
    'elapsed' => 'Tiempo',
    'clicks' => 'Clics',
    'keys' => 'Teclas',
    'pad_hint' => 'Haz clic aqui para enfocar el pad y actuar.',
    'reference' => 'Consejo: RTS casual 40-80 APM, plata 100, platino 200, master 300+, pro 300-450 sostenido con picos de 800.',
];
include __DIR__ . '/../../../tools/apm_test_tool.php';
