<?php
// Localized labels for aspect-ratio-calculator — auto-generated by generate-locale-wrappers.py
$ar_labels = [
    'aria' => 'Calculadora de relacion de aspecto - resuelve ancho, alto o ratio',
    'instruction' => 'Edita dos de tres (ancho, alto o ratio). La herramienta resuelve el tercero. El ratio acepta \'16:9\' o \'1.7778\'.',
    'preset' => 'Ratio preajustado',
    'width' => 'Ancho (px)',
    'height' => 'Alto (px)',
    'ratio' => 'Relacion de aspecto',
    'simplified' => 'Simplificado',
    'decimal' => 'Decimal',
    'orientation' => 'Orientacion',
    'landscape' => 'Horizontal',
    'portrait' => 'Vertical',
    'square' => 'Cuadrado',
    'reference' => 'Consejo: introduce ancho y alto para ver el ratio, o elige un preset y escribe una dimension.',
];
include __DIR__ . '/../../../tools/aspect_calc_tool.php';
