<?php
// Localized labels for mouse-spin-test — auto-generated by generate-locale-wrappers.py
$ms_labels = [
    'aria' => 'Prueba de giro del raton - cuenta rotaciones de 360',
    'instruction' => 'Pulsa Iniciar, coloca el cursor en el pad, manten el boton izquierdo y gira alrededor del punto central. Cada 360 cuenta como un giro.',
    'duration' => 'Duracion',
    'dur_15' => '15 segundos',
    'dur_30' => '30 segundos',
    'dur_60' => '60 segundos',
    'start' => 'Iniciar',
    'stop' => 'Detener',
    'reset' => 'Reiniciar',
    'pad_hint' => 'Manten el boton izquierdo y gira alrededor del centro.',
    'time_left' => 'Tiempo restante',
    'spins' => 'Giros',
    'peak_sps' => 'Giros/seg pico',
    'degrees' => 'Rotacion total',
    'direction' => 'Direccion',
    'dir_cw' => 'Horario',
    'dir_ccw' => 'Antihorario',
    'dir_idle' => '-',
    'reference' => 'Consejo: DPI alto permite girar mas con menos movimiento. Prueba en ambos sentidos y rondas lentas vs flicks rapidos.',
];
include __DIR__ . '/../../../tools/mouse_spin_tool.php';
