<?php
// Localized labels for screen-size-calculator — auto-generated by generate-locale-wrappers.py
$ss_labels = [
    'aria' => 'Calculadora de tamano de pantalla',
    'instruction' => 'Elige la relacion de aspecto y escribe diagonal, ancho o alto. Las otras dos se rellenan en pulgadas y cm. Tambien se muestra el area visible.',
    'aspect' => 'Relacion de aspecto',
    'measured' => 'Conozco la',
    'measure_diagonal' => 'diagonal',
    'measure_width' => 'ancho',
    'measure_height' => 'alto',
    'value' => 'Valor',
    'unit' => 'Unidad',
    'diagonal' => 'Diagonal',
    'width' => 'Ancho',
    'height' => 'Alto',
    'area' => 'Area visible',
    'reference' => 'Consejo: los TV se anuncian por diagonal, pero lo que ocupa en el mueble es el ancho. 55 16:9 y 55 21:9 son muy diferentes.',
];
include __DIR__ . '/../../../tools/screen_size_calc_tool.php';
