<?php
// Localized labels for screen-uniformity-test — auto-generated by generate-locale-wrappers.py
$su_labels = [
    'aria' => 'Prueba de uniformidad de pantalla',
    'instruction' => 'Elige un color y brillo, luego Pantalla completa. Paneles buenos muestran color uniforme borde a borde. Brillo desigual, esquinas tenidas o manchas nubladas revelan problemas de uniformidad.',
    'color' => 'Color',
    'c_gray' => 'Gris medio (detecta clouding)',
    'c_black' => 'Cerca de negro (detecta IPS glow + bleed)',
    'c_white' => 'Blanco (detecta caida de brillo)',
    'c_red' => 'Rojo',
    'c_green' => 'Verde',
    'c_blue' => 'Azul',
    'brightness' => 'Brillo',
    'fullscreen' => 'Pantalla completa',
    'exit_fs' => 'Salir',
    'reference' => 'Consejo: prueba al 20, 50 y 80 por ciento de brillo - los problemas suelen aparecer solo en una banda. Alejate 2-3 pies y apaga la luz para clouding.',
];
include __DIR__ . '/../../../tools/screen_uniformity_tool.php';
