<?php
// Localized labels for sound-test — auto-generated by generate-locale-wrappers.py
$st_labels = [
    'aria' => 'Prueba de sonido - verificacion de canales y barrido de frecuencias',
    'instruction' => 'Primera vez? El navegador pedira permiso de audio al primer Reproducir. Pon el volumen del sistema al 30% antes de empezar - los tonos pueden ser fuertes.',
    'channel' => 'Canal',
    'ch_left' => 'Solo izquierdo',
    'ch_right' => 'Solo derecho',
    'ch_both' => 'Ambos',
    'ch_pingpong' => 'Ping-pong (alterna L y R)',
    'freq' => 'Frecuencia',
    'freq_value' => 'Hz',
    'volume' => 'Volumen',
    'volume_value' => '%',
    'play' => 'Reproducir',
    'stop' => 'Detener',
    'sweep' => 'Barrido 100 Hz a 10 kHz',
    'now_playing' => 'Reproduciendo ahora',
    'idle' => 'Inactivo',
    'reference' => 'Consejo: si en modo Ambos solo suena un lado, el problema es cableado (jack TRS mal puesto, cable dano, emparejamiento BT), no software.',
];
include __DIR__ . '/../../../tools/sound_test_tool.php';
