<?php
/**
 * ╔══════════════════════════════════════════════════════════════╗
 * ║           BLOG POSTS REGISTRY — Single Source of Truth      ║
 * ║                                                              ║
 * ║  ADD NEW POSTS HERE ONLY. They automatically appear in:      ║
 * ║    • Blog index page  (blog/index.php)                       ║
 * ║    • AI chatbot knowledge base  (ai-chat.php)                ║
 * ║    • No other files need touching for new posts.             ║
 * ╚══════════════════════════════════════════════════════════════╝
 *
 * Fields:
 *   path    — file path from site root (used for links in blog index)
 *   url     — full canonical URL (used by the AI bot for linking)
 *   image   — hero image path (relative to site root)
 *   alt     — image alt text
 *   date    — human-readable publish date
 *   title   — full article title
 *   excerpt — short description (shown on blog cards)
 */
return [

    [
        'path'    => 'blog/best-laptops-with-good-gpu-2026.php',
        'url'     => 'https://keyboardtester.click/blog/best-laptops-with-good-gpu-2026.php',
        'image'   => 'blog/images/good-gpu-laptop-2026-asus-scar-18.webp',
        'alt'     => 'ASUS ROG Strix SCAR 18 gaming laptop with RTX 5090 graphics',
        'date'    => 'May 2, 2026',
        'title'   => 'Best Laptops With Good GPU in 2026: RTX 5090 and RTX 5080 Picks',
        'excerpt' => 'A researched buyer guide to laptops with good GPUs, including RTX 5090 and RTX 5080 models, current prices, review notes, specs, and practical buying advice.',
    ],

    // ── 2026 — May ──────────────────────────────────────────────────────────
    [
        'path'    => 'blog/ai-gpu-test-webgpu-browser-ai-readiness.php',
        'url'     => 'https://keyboardtester.click/blog/ai-gpu-test-webgpu-browser-ai-readiness.php',
        'image'   => 'images/gpu-stress-test/hero.jpg',
        'alt'     => 'Graphics card used for an AI GPU test, WebGPU test, and browser AI readiness check',
        'date'    => 'May 1, 2026',
        'title'   => 'AI GPU Test: Check WebGPU, WebNN and Browser AI Readiness (2026 Guide)',
        'excerpt' => 'A practical guide to AI GPU testing in the browser: WebGPU, WebNN, WebGL2, software-rendering fallback, matrix benchmarks, and local AI readiness.',
    ],
    [
        'path'    => 'blog/mouse-acceleration-windows-11-disable-raw-input-gaming-guide.php',
        'url'     => 'https://keyboardtester.click/blog/mouse-acceleration-windows-11-disable-raw-input-gaming-guide.php',
        'image'   => 'blog/images/mouse-acceleration-rgb-gaming-mouse-hero.webp',
        'alt'     => 'RGB gaming mouse on a competitive setup — testing mouse acceleration in Windows 11',
        'date'    => 'May 1, 2026',
        'title'   => 'Mouse Acceleration on Windows 11: How to Disable It and Use Raw Input (2026 Gaming Guide)',
        'excerpt' => 'Step-by-step guide to turning off mouse acceleration in Windows 11, why Enhance Pointer Precision hurts FPS aim, and how raw input works in Valorant, CS2, and Apex.',
    ],

    // ── 2026 — April ────────────────────────────────────────────────────────
    [
        'path'    => 'blog/keyboard-polling-rate-test-check-keyboard-hz.php',
        'url'     => 'https://keyboardtester.click/blog/keyboard-polling-rate-test-check-keyboard-hz.php',
        'image'   => 'blog/images/keyboard-polling-rate-test-hero.webp',
        'alt'     => 'Mechanical keyboards used for an online keyboard polling rate test',
        'date'    => 'April 28, 2026',
        'title'   => 'Keyboard Polling Rate Test: Check Keyboard Hz Online (2026 Guide)',
        'excerpt' => 'Learn how to check keyboard polling rate and keyboard Hz online, why browser tests can show lower numbers than advertised, and when 1000Hz vs 8000Hz actually matters.',
    ],
    [
        'path'    => 'blog/v4n4g0n-keyboard-45-percent-custom-mechanical-guide.php',
        'url'     => 'https://keyboardtester.click/blog/v4n4g0n-keyboard-45-percent-custom-mechanical-guide.php',
        'image'   => 'blog/images/v4n4g0n-hero.webp',
        'alt'     => 'Two colourful custom mechanical keyboards with pastel keycaps — the V4N4G0N 45% custom keyboard aesthetic',
        'date'    => 'April 24, 2026',
        'title'   => 'V4N4G0N Keyboard: The 45% Custom Mechanical Cult Classic Explained (2026)',
        'excerpt' => 'The V4N4G0N is a 45% custom mechanical keyboard with a half numrow — a Vanagon-inspired MiniVan upgrade. Full specs, R1-R4 group buy history, Bullet Train wireless successor, pricing, and honest pros and cons.',
    ],
    [
        'path'    => 'blog/what-is-webrtc-leak-how-to-fix-guide.php',
        'url'     => 'https://keyboardtester.click/blog/what-is-webrtc-leak-how-to-fix-guide.php',
        'image'   => 'blog/images/webrtc-leak-vpn-laptop-hero.jpg',
        'alt'     => 'Laptop with active VPN app — testing for a WebRTC IP leak in the browser',
        'date'    => 'April 22, 2026',
        'title'   => 'What Is a WebRTC Leak? How to Test and Fix It (2026 Guide)',
        'excerpt' => 'A WebRTC leak exposes your real IP through the browser even with a VPN on. This guide covers how to test, how to fix leaks in Chrome, Firefox, Brave and Safari, and why a .local mDNS address is not actually a leak.',
    ],
    [
        'path'    => 'blog/how-to-copy-pro-crosshair-cs2-valorant-generator-guide.php',
        'url'     => 'https://keyboardtester.click/blog/how-to-copy-pro-crosshair-cs2-valorant-generator-guide.php',
        'image'   => 'blog/images/crosshair-cs2-valorant-pro-hero.webp',
        'alt'     => 'Pro esports gaming setup showing an FPS aim reticle on a high-refresh-rate monitor',
        'date'    => 'April 21, 2026',
        'title'   => 'How to Copy a Pro\'s Crosshair in CS2 & Valorant (and Build Your Own) — 2026 Generator Guide',
        'excerpt' => 'Copy any pro player\'s crosshair in CS2 or Valorant by code, or design your own with a free crosshair generator. Pro codes, console commands, dot vs cross, color theory, and the two-week rule that actually improves aim.',
    ],
    [
        'path'    => 'blog/what-is-keyboard-ghosting-anti-ghosting-fix-guide.php',
        'url'     => 'https://keyboardtester.click/blog/what-is-keyboard-ghosting-anti-ghosting-fix-guide.php',
        'image'   => 'blog/images/keyboard-ghosting-mechanical-rgb-hero.jpg',
        'alt'     => 'Close-up of a blue-backlit keyboard — what is keyboard ghosting and anti-ghosting explained',
        'date'    => 'April 20, 2026',
        'title'   => 'What Is Keyboard Ghosting? Anti-Ghosting, NKRO & Every Fix Explained (2026)',
        'excerpt' => 'Keyboard ghosting is when some keys silently fail to register during multi-key presses. This guide explains why it happens, how anti-ghosting and NKRO fix it, and how to test, enable, and disable ghosting on laptop and gaming keyboards in Windows 11.',
    ],
    [
        'path'    => 'blog/keyboard-shortcuts-windows-mac-linux-complete-cheat-sheet.php',
        'url'     => 'https://keyboardtester.click/blog/keyboard-shortcuts-windows-mac-linux-complete-cheat-sheet.php',
        'image'   => 'blog/images/keyboard-shortcuts-v2-hero.webp',
        'alt'     => 'Keyboard shortcuts cheat sheet — Windows, macOS and Linux',
        'date'    => 'April 19, 2026',
        'title'   => 'The Complete Keyboard Shortcuts Cheat Sheet: Windows, macOS & Linux (2026)',
        'excerpt' => 'Every keyboard shortcut worth knowing for Windows 11, macOS Sequoia, and Linux (GNOME/Ubuntu) — cross-referenced side by side. Text editing, browsers, screenshots, system, terminal, YouTube.',
    ],
    [
        'path'    => 'blog/keyboard-not-typing-lagging-sticky-fix-clean-guide.php',
        'url'     => 'https://keyboardtester.click/blog/keyboard-not-typing-lagging-sticky-fix-clean-guide.php',
        'image'   => 'blog/images/keyboard-troubleshooting-fix-clean-hero.webp',
        'alt'     => 'Keyboard troubleshooting — fix delay, dead keys, and clean sticky keys',
        'date'    => 'April 18, 2026',
        'title'   => 'Keyboard Not Typing, Lagging, or Sticky? The Complete 2026 Fix & Clean Guide',
        'excerpt' => 'Keyboard not typing, laggy, or sticky keys? The 2026 fix-everything guide — diagnose with the free tester, fix input delay in Windows 11, and safely deep-clean keys on membrane, scissor, and mechanical boards.',
    ],
    [
        'path'    => 'blog/double-click-test-check-mouse-switch-bounce.php',
        'url'     => 'https://keyboardtester.click/blog/double-click-test-check-mouse-switch-bounce.php',
        'image'   => 'blog/images/double-click-test-switch-bounce-hero.webp',
        'alt'     => 'Double Click Test: Check If Your Mouse Double-Clicks on Single Click',
        'date'    => 'April 18, 2026',
        'title'   => 'Double Click Test: Check If Your Mouse Double-Clicks on Single Click (2026 Guide)',
        'excerpt' => 'Free online double click test to diagnose switch bounce, plus every working fix for 2026 — Windows settings, the viral Reddit squeeze trick, and permanent switch replacement.',
    ],
    [
        'path'    => 'blog/keyboard-typing-double-letters-fix-key-chatter.php',
        'url'     => 'https://keyboardtester.click/blog/keyboard-typing-double-letters-fix-key-chatter.php',
        'image'   => 'blog/images/keyboard-online-test-complete-guide.webp',
        'alt'     => 'Keyboard at a desk — fixing key chatter and double typing',
        'date'    => 'April 12, 2026',
        'title'   => 'Keyboard Typing Double Letters? The Complete Key Chatter Fix Guide (2026)',
        'excerpt' => 'Keys typing twice or double letters appearing? That\'s key chatter — a hardware failure in your switch contacts. Every practical fix covered, from a 30-second software tweak to switch replacement.',
    ],
    [
        'path'    => 'blog/best-recent-gaming-headphone-launches-2026.php',
        'url'     => 'https://keyboardtester.click/blog/best-recent-gaming-headphone-launches-2026.php',
        'image'   => 'blog/images/gaming-headphones-2026-featured-g522.jpg',
        'alt'     => '5 Best Recent Gaming Headphone Launches in 2026: Honest Picks by Brand',
        'date'    => 'April 11, 2026',
        'title'   => '5 Best Recent Gaming Headphone Launches in 2026: Honest Picks by Brand',
        'excerpt' => 'A researched, honest guide to five recent gaming headset launches worth considering in 2026, with official dates, prices, features, and a realistic assessment.',
    ],
    [
        'path'    => 'blog/best-mechanical-keyboards-for-gaming-2026.php',
        'url'     => 'https://keyboardtester.click/blog/best-mechanical-keyboards-for-gaming-2026.php',
        'image'   => 'blog/images/wooting-80he-gaming-keyboard.webp',
        'alt'     => 'Best gaming keyboard 2026 mechanical picks',
        'date'    => 'April 11, 2026',
        'title'   => 'Best Gaming Keyboard 2026: 6 Mechanical Picks Tested',
        'excerpt' => 'Best gaming keyboard 2026 guide covering budget, Hall Effect, wireless, full-size, Reddit-popular, and mechanical gaming picks with prices.',
    ],
    [
        'path'    => 'blog/best-recent-wireless-keyboard-launches-2026.php',
        'url'     => 'https://keyboardtester.click/blog/best-recent-wireless-keyboard-launches-2026.php',
        'image'   => 'blog/images/asus-rog-azoth-x-wireless-official-webp.webp',
        'alt'     => '5 Best Recent Wireless Keyboard Launches in 2026',
        'date'    => 'April 11, 2026',
        'title'   => '5 Best Recent Wireless Keyboard Launches in 2026: Honest Picks for Gaming and Work',
        'excerpt' => 'A researched, honest guide to five recent wireless keyboard launches worth considering in 2026, with official launch timing, features, pricing, and a clear verdict.',
    ],
    [
        'path'    => 'blog/best-recent-gaming-keyboard-launches-2026.php',
        'url'     => 'https://keyboardtester.click/blog/best-recent-gaming-keyboard-launches-2026.php',
        'image'   => 'blog/images/logitech-g515-rapid-tkl-official-png.png',
        'alt'     => '5 Best Recent Gaming Keyboard Launches in 2026',
        'date'    => 'April 10, 2026',
        'title'   => '5 Best Recent Gaming Keyboard Launches in 2026: Honest Picks by Brand',
        'excerpt' => 'A researched, honest guide to five recent gaming keyboard launches worth buying in 2026, with official specs, launch dates, pricing, and a clear verdict.',
    ],
    [
        'path'    => 'blog/best-recent-gaming-mouse-launches-2026.php',
        'url'     => 'https://keyboardtester.click/blog/best-recent-gaming-mouse-launches-2026.php',
        'image'   => 'blog/images/razer-viper-v4-pro-official-product-image.webp',
        'alt'     => '5 Best Recent Gaming Mouse Launches in 2026',
        'date'    => 'April 10, 2026',
        'title'   => '5 Best Recent Gaming Mouse Launches in 2026: Honest Picks by Brand',
        'excerpt' => 'A researched, honest guide to five recent gaming mouse launches worth buying in 2026, with official specs, launch dates, pricing, and a clear verdict.',
    ],

    // ── 2026 — March ────────────────────────────────────────────────────────
    [
        'path'    => 'blog/lucky-wheel-spinner-random-selection.php',
        'url'     => 'https://keyboardtester.click/blog/lucky-wheel-spinner-random-selection.php',
        'image'   => 'blog/images/lucky-wheel-spinner-guide.webp',
        'alt'     => 'Lucky Wheel Spinner: Free Random Selection Tool',
        'date'    => 'March 28, 2026',
        'title'   => 'Lucky Wheel Spinner: Free Random Selection Tool for Decisions and Giveaways',
        'excerpt' => 'Spin the lucky wheel to make random selections for giveaways, decisions, games, and classroom activities. Add custom options and spin.',
    ],
    [
        'path'    => 'blog/whatsapp-link-generator-direct-chat.php',
        'url'     => 'https://keyboardtester.click/blog/whatsapp-link-generator-direct-chat.php',
        'image'   => 'blog/images/whatsapp-link-direct-chat-guide.webp',
        'alt'     => 'WhatsApp Link Generator: Create Direct Chat Links',
        'date'    => 'March 28, 2026',
        'title'   => 'WhatsApp Link Generator: Create Direct Chat Links Without Saving Contacts',
        'excerpt' => 'Create WhatsApp direct chat links (wa.me) with pre-filled messages. Start conversations without saving contacts first.',
    ],
    [
        'path'    => 'blog/secure-password-generator-strong-random.php',
        'url'     => 'https://keyboardtester.click/blog/secure-password-generator-strong-random.php',
        'image'   => 'blog/images/password-generator-security-guide.webp',
        'alt'     => 'Secure Password Generator: Create Strong Random Passwords',
        'date'    => 'March 28, 2026',
        'title'   => 'Secure Password Generator: Create Strong Random Passwords',
        'excerpt' => 'Generate cryptographically strong random passwords with customizable length and character sets. All generation happens locally in your browser.',
    ],
    [
        'path'    => 'blog/free-ocr-tool-extract-text-from-images.php',
        'url'     => 'https://keyboardtester.click/blog/free-ocr-tool-extract-text-from-images.php',
        'image'   => 'blog/images/ocr-tool-text-extraction-guide.webp',
        'alt'     => 'Free OCR Tool: Extract Text from Images Online',
        'date'    => 'March 28, 2026',
        'title'   => 'Free OCR Tool: Extract Text from Images and Screenshots Online',
        'excerpt' => 'Extract text from images, screenshots, and photos using free browser-based OCR. No upload to servers — all processing happens locally.',
    ],
    [
        'path'    => 'blog/qr-code-reader-scan-decode-images.php',
        'url'     => 'https://keyboardtester.click/blog/qr-code-reader-scan-decode-images.php',
        'image'   => 'blog/images/qr-reader-online-guide.webp',
        'alt'     => 'QR Code Reader: Scan and Decode QR Codes from Images',
        'date'    => 'March 28, 2026',
        'title'   => 'QR Code Reader: Scan and Decode QR Codes from Images',
        'excerpt' => 'Scan and decode QR codes from uploaded images or screenshots. No camera needed — works entirely with image files.',
    ],
    [
        'path'    => 'blog/free-qr-code-generator-create-online.php',
        'url'     => 'https://keyboardtester.click/blog/free-qr-code-generator-create-online.php',
        'image'   => 'blog/images/qr-generator-online-guide.webp',
        'alt'     => 'Free QR Code Generator: Create QR Codes Online',
        'date'    => 'March 28, 2026',
        'title'   => 'Free QR Code Generator: Create QR Codes Online in Seconds',
        'excerpt' => 'Create free QR codes online from any URL, text, or message. Download as PNG. No signup required.',
    ],
    [
        'path'    => 'blog/webcam-test-check-camera-video-calls.php',
        'url'     => 'https://keyboardtester.click/blog/webcam-test-check-camera-video-calls.php',
        'image'   => 'blog/images/webcam-video-call-check-guide.webp',
        'alt'     => 'Webcam Test: How to Check Your Camera Before Video Calls',
        'date'    => 'March 28, 2026',
        'title'   => 'Webcam Test: How to Check Your Camera Before Video Calls',
        'excerpt' => 'Test your webcam online for free. Preview your camera, check resolution, and troubleshoot webcam issues before Zoom, Teams, or Google Meet calls.',
    ],
    [
        'path'    => 'blog/headphone-speaker-test-left-right-channels.php',
        'url'     => 'https://keyboardtester.click/blog/headphone-speaker-test-left-right-channels.php',
        'image'   => 'blog/images/speaker-headphone-channel-guide.webp',
        'alt'     => 'Headphone and Speaker Test: Check Left and Right Audio Channels',
        'date'    => 'March 28, 2026',
        'title'   => 'Headphone and Speaker Test: Check Left and Right Audio Channels',
        'excerpt' => 'Test your headphones and speakers for left/right channel balance. Verify stereo separation and identify faulty audio drivers.',
    ],
    [
        'path'    => 'blog/how-to-test-microphone-online.php',
        'url'     => 'https://keyboardtester.click/blog/how-to-test-microphone-online.php',
        'image'   => 'blog/images/microphone-online-test-guide.webp',
        'alt'     => 'How to Test Your Microphone Online',
        'date'    => 'March 28, 2026',
        'title'   => 'How to Test Your Microphone Online Before Meetings and Calls',
        'excerpt' => 'Test your microphone online for free before Zoom, Teams, or Discord calls. Check if your mic is detected, verify volume levels, and troubleshoot common issues.',
    ],
    [
        'path'    => 'blog/dead-pixel-test-check-monitor.php',
        'url'     => 'https://keyboardtester.click/blog/dead-pixel-test-check-monitor.php',
        'image'   => 'blog/images/dead-pixel-test-monitor-guide.webp',
        'alt'     => 'Dead Pixel Test: How to Check Your Monitor',
        'date'    => 'March 28, 2026',
        'title'   => 'Dead Pixel Test: How to Check Your Monitor for Defective Pixels',
        'excerpt' => 'Test your monitor for dead and stuck pixels with free fullscreen color panels. Works on LCD, LED, OLED, and IPS displays.',
    ],
    [
        'path'    => 'blog/input-latency-checker-keyboard-mouse-delay.php',
        'url'     => 'https://keyboardtester.click/blog/input-latency-checker-keyboard-mouse-delay.php',
        'image'   => 'blog/images/input-latency-measure-guide.webp',
        'alt'     => 'Input Latency Checker: Measure Keyboard and Mouse Delay',
        'date'    => 'March 28, 2026',
        'title'   => 'Input Latency Checker: Measure Keyboard and Mouse Delay',
        'excerpt' => 'Measure your keyboard and mouse input latency in milliseconds. Test reaction time and identify input lag from peripherals, USB ports, or wireless connections.',
    ],
    [
        'path'    => 'blog/mouse-trail-visualizer-movement-patterns.php',
        'url'     => 'https://keyboardtester.click/blog/mouse-trail-visualizer-movement-patterns.php',
        'image'   => 'blog/images/mouse-trail-visualizer-guide.webp',
        'alt'     => 'Mouse Trail Visualizer: See Your Mouse Movement Patterns',
        'date'    => 'March 28, 2026',
        'title'   => 'Mouse Trail Visualizer: See Your Mouse Movement Patterns',
        'excerpt' => 'Visualize your mouse movement patterns with colorful trails. Test tracking smoothness, sensor accuracy, and cursor consistency.',
    ],
    [
        'path'    => 'blog/mouse-dpi-tester-measure-sensitivity.php',
        'url'     => 'https://keyboardtester.click/blog/mouse-dpi-tester-measure-sensitivity.php',
        'image'   => 'blog/images/mouse-dpi-tester-sensitivity-hero.webp',
        'alt'     => 'Mouse DPI test — measure actual vs advertised mouse sensitivity',
        'date'    => 'March 28, 2026',
        'title'   => 'Mouse DPI Test: Measure Actual vs Advertised Sensitivity (2026 Guide)',
        'excerpt' => 'Free online mouse DPI test: find out if your mouse delivers what the label claims, learn the right DPI for Valorant, CS2 and productivity, and how polling rate and eDPI combine into the feel you are actually tuning.',
    ],
    [
        'path'    => 'blog/ghost-click-detector-fix-double-clicking.php',
        'url'     => 'https://keyboardtester.click/blog/ghost-click-detector-fix-double-clicking.php',
        'image'   => 'blog/images/ghost-click-double-click-guide.webp',
        'alt'     => 'Ghost Click Detector: How to Fix Mouse Double Clicking',
        'date'    => 'March 28, 2026',
        'title'   => 'Ghost Click Detector: How to Fix Mouse Double Clicking',
        'excerpt' => 'Is your mouse double clicking on its own? Use the free ghost click detector to diagnose phantom clicks and learn how to fix worn-out mouse switches.',
    ],
    [
        'path'    => 'blog/click-speed-test-measure-cps.php',
        'url'     => 'https://keyboardtester.click/blog/click-speed-test-measure-cps.php',
        'image'   => 'blog/images/click-speed-online-guide.webp',
        'alt'     => 'Click Speed Test: How to Measure Your CPS',
        'date'    => 'March 28, 2026',
        'title'   => 'Click Speed Test: How to Measure Your CPS (Clicks Per Second)',
        'excerpt' => 'Measure your click speed in CPS with a free online test. Learn jitter clicking, butterfly clicking, and other techniques to click faster.',
    ],
    [
        'path'    => 'blog/how-to-test-mouse-buttons-scroll-wheel.php',
        'url'     => 'https://keyboardtester.click/blog/how-to-test-mouse-buttons-scroll-wheel.php',
        'image'   => 'blog/images/mouse-buttons-test-guide.webp',
        'alt'     => 'How to Test Your Mouse Buttons and Scroll Wheel Online',
        'date'    => 'March 28, 2026',
        'title'   => 'How to Test Your Mouse Buttons and Scroll Wheel Online',
        'excerpt' => 'Test all your mouse buttons and scroll wheel online for free. Diagnose left click, right click, middle click, and scroll issues instantly.',
    ],
    [
        'path'    => 'blog/how-to-measure-typing-speed-wpm.php',
        'url'     => 'https://keyboardtester.click/blog/how-to-measure-typing-speed-wpm.php',
        'image'   => 'blog/images/typing-speed-wpm-guide.webp',
        'alt'     => 'How to Measure Your Typing Speed: WPM Test Guide',
        'date'    => 'March 28, 2026',
        'title'   => 'How to Measure Your Typing Speed: WPM Test Guide',
        'excerpt' => 'Measure your typing speed in words per minute (WPM) with a free online typing test. Learn tips to improve your speed and accuracy.',
    ],
    [
        'path'    => 'blog/how-to-test-keyboard-online.php',
        'url'     => 'https://keyboardtester.click/blog/how-to-test-keyboard-online.php',
        'image'   => 'blog/images/keyboard-online-test-complete-guide.webp',
        'alt'     => 'How to Test Your Keyboard Online: A Complete Guide',
        'date'    => 'March 28, 2026',
        'title'   => 'How to Test Your Keyboard Online: A Complete Guide (2026)',
        'excerpt' => 'Learn how to test your keyboard online for free. Check for stuck keys, ghosting, N-key rollover, and more using browser-based tools — no download needed.',
    ],

];
