<?php
// Localized labels for color-range-test — auto-generated by generate-locale-wrappers.py
$cr_labels = [
    'aria' => 'Test de plage de couleur - detecte RGB limite vs complet',
    'instruction' => 'Regardez chaque ligne. Un ecran COMPLET montre toutes les tuiles distinctes. Un ecran LIMITE fond les premieres (en noir pur) et les dernieres (en blanc pur).',
    'near_black' => 'Pres du noir (RGB 0-31)',
    'near_white' => 'Pres du blanc (RGB 224-255)',
    'ramp' => 'Degrade continu (0 a 255)',
    'fullscreen' => 'Plein ecran',
    'exit_fs' => 'Quitter',
    'reference' => 'Astuce : Windows envoie souvent HDMI en plage limitee par defaut. NVIDIA : Resolution > Plage dynamique de sortie = Complet.',
];
include __DIR__ . '/../../../tools/color_range_tool.php';
