<?php
// Localized labels for screen-size-calculator — auto-generated by generate-locale-wrappers.py
$ss_labels = [
    'aria' => 'Calculateur de taille d\'ecran',
    'instruction' => 'Choisissez le ratio puis entrez diagonale, largeur ou hauteur. Les deux autres se remplissent en pouces et cm. La surface visible s\'affiche aussi.',
    'aspect' => 'Ratio d\'aspect',
    'measured' => 'Je connais la',
    'measure_diagonal' => 'diagonale',
    'measure_width' => 'largeur',
    'measure_height' => 'hauteur',
    'value' => 'Valeur',
    'unit' => 'Unite',
    'diagonal' => 'Diagonale',
    'width' => 'Largeur',
    'height' => 'Hauteur',
    'area' => 'Surface visible',
    'reference' => 'Astuce : les TV sont vendues a la diagonale mais c\'est la largeur qui compte sur le meuble. 55 16:9 != 55 21:9.',
];
include __DIR__ . '/../../../tools/screen_size_calc_tool.php';
