<?php
// Localized labels for viewing-distance-calculator — auto-generated by generate-locale-wrappers.py
$vd_labels = [
    'aria' => 'Calculateur de distance de vision',
    'instruction' => 'Saisissez la diagonale et la resolution. L\'outil donne THX optimal (36 FoV), SMPTE cinema (30 FoV) et la distance limite ou 4K ne se distingue plus de 1080p.',
    'diagonal' => 'Diagonale de l\'ecran',
    'resolution' => 'Resolution native',
    'unit' => 'Unite',
    'thx' => 'THX optimal (36 FoV)',
    'smpte' => 'SMPTE cinema (30 FoV)',
    'uhd4k' => 'Distance max 4K UHD',
    'min_4k' => 'Au-dela, 4K = 1080p a l\'oeil',
    'angle' => 'Angle en THX',
    'reference' => 'Astuce : THX = 36 (immersif), SMPTE = 30 (cinema confort). Plus loin que la limite 4K, acheter 4K ne sert a rien a cette taille.',
];
include __DIR__ . '/../../../tools/viewing_distance_calc_tool.php';
