<?php
/**
 * german localized landing page for auditory-reaction-time-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-de.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Auditiver Reaktionstest - Reaktionszeit auf Töne';
$pageDescription = 'Testen Sie Ihre Reaktionszeit auf einen Ton mit der Web Audio API. 5 Runden mit Durchschnitt, Bestzeit, schlechtester Zeit und Fehlstart-Erkennung.';
?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('auditory-reaction-time-test.php'); ?>">
  <link rel="alternate" hreflang="de" href="<?php echo absoluteUrl('languages/german/auditory-reaction-time-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('auditory-reaction-time-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('auditory_reaction_time', [['name'=>'Home','url'=>'/'],['name'=>'Auditiver Reaktionstest','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-de.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Audio-Diagnose</p>
          <h1 class="hero-title">Auditiver Reaktionstest</h1>
          <p class="hero-lede">Misst in Millisekunden, wie schnell Sie auf einen Ton reagieren. Ein Piepton ertönt nach zufälliger Verzögerung von 1,5 bis 4 Sekunden. Durchschnitt, Best- und Schlechtzeit über 5 Runden. Fehlstart-Erkennung inklusive.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#auditory-reaction-time-test">Test starten</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Alle Tools anzeigen</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/auditory-reaction-time-test/hero.jpg'); ?>" width="1200" height="800" alt="Auditiver Reaktionstest" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="auditory-reaction-time-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Haupt-Tool</p>
          <h2>Auditiver Reaktionstest</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/auditory_reaction_time_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'auditory-reaction-time-test'; $localizedRelatedCategory = 'audio'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-de.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
