<?php
/**
 * german localized landing page for download-time-calculator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-de.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Download-Zeit-Rechner - Spiele, Filme, Backups';
$pageDescription = 'Schätzt die Download-Zeit für Spiele, Filme und Backups bei Ihrer Geschwindigkeit. 15+ Presets und Schätzungen theoretisch, real und langsam.';
?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('download-time-calculator.php'); ?>">
  <link rel="alternate" hreflang="de" href="<?php echo absoluteUrl('languages/german/download-time-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('download-time-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('download_time_calc', [['name'=>'Home','url'=>'/'],['name'=>'Download-Zeit-Rechner','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-de.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Rechner</p>
          <h1 class="hero-title">Download-Zeit-Rechner</h1>
          <p class="hero-lede">Wählen Sie ein Preset (AAA-Spiel, 4K-Film, Linux-ISO, Steam-Backup) oder geben Sie eine Größe ein und erhalten Sie die Dauer in Xh Ym Zs mit Schätzungen realistisch 85%, theoretisch 100% und langsames Netz 60%.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#download-time-calculator">Schätzen</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Alle Tools anzeigen</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/download-time-calculator/hero.jpg'); ?>" width="1200" height="800" alt="Download-Zeit-Rechner" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="download-time-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Haupt-Tool</p>
          <h2>Download-Zeit-Rechner</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/download_time_calc_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/download-time-calculator.php'; ?>
    <?php $currentTool = 'mouse'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/download-time-calculator.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-de.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
