<?php
/**
 * German localized landing page for fps-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-de.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'FPS-Test - Browser-Bildrate';
$pageDescription = 'FPS-Test online: Live-Messung der Browser-Bildrate mit Durchschnitt/Min/Max/1%-Low und automatischer 60/120/144/240-Hz-Erkennung. Ohne Installation, schnell im Browser.';
?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('fps-test.php'); ?>">
  <link rel="alternate" hreflang="de" href="<?php echo absoluteUrl('languages/german/fps-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('fps-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-de.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Performance-Diagnose</p>
          <h1 class="hero-title">FPS-Test</h1>
          <p class="hero-lede">Miss die Browser-Bildrate live via requestAnimationFrame. Zeigt aktuelle FPS, Durchschnitt, Min, Max und 1%-Low.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#fps-test">Test starten</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Alle Tools</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="fps-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Performance-Diagnose</p>
          <h2>FPS-Test</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/fps-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-de.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
