<?php
/**
 * german localized landing page for guild-name-generator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-de.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Gilden-Namen-Generator - MMO-Clan-Namen';
$pageDescription = 'Generator für MMO-Gilden- und Clan-Namen in 6 Themen und 5 Vorlagen mit Limits für WoW, FFXIV, Destiny und Discord.';
?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('guild-name-generator.php'); ?>">
  <link rel="alternate" hreflang="de" href="<?php echo absoluteUrl('languages/german/guild-name-generator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('guild-name-generator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('guild_name_generator', [['name'=>'Home','url'=>'/'],['name'=>'Gilden-Namen-Generator','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-de.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Gaming-Werkzeug</p>
          <h1 class="hero-title">Gilden-Namen-Generator</h1>
          <p class="hero-lede">Erzeugt 10 zufällige Gildennamen in 6 Themen (Fantasy, Sci-Fi, dunkel, edel, Schurken, Mythos) mit Vorlagen wie "Orden von X", "Haus X", "Die X". Mit einem Klick kopieren, Favoriten im Browser.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#guild-name-generator">Namen generieren</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Alle Tools anzeigen</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/guild-name-generator/hero.jpg'); ?>" width="1200" height="800" alt="Gilden-Namen-Generator" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="guild-name-generator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Haupt-Tool</p>
          <h2>Gilden-Namen-Generator</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/guild_name_generator_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'guild-name-generator'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-de.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
