<?php
/**
 * german localized landing page for monitor-sharpness-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-de.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Monitor-Schaerfe-Test - Textklarheit im Browser';
$pageDescription = 'Kostenloser Monitor-Schaerfe-Test. 1px-Pixelraster im Lagom-Stil, Textproben in mehreren Groessen, Farbsaum-Bloecke und RGB-Subpixel-Lineal.';
?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('monitor-sharpness-test.php'); ?>">
  <link rel="alternate" hreflang="de" href="<?php echo absoluteUrl('languages/german/monitor-sharpness-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('monitor-sharpness-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('monitor_sharpness_test', [['name'=>'Home','url'=>'/'],['name'=>'Kostenloser Monitor-Schaerfe-Test - Online-Textklarheit','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-de.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Display-Diagnose</p>
          <h1 class="hero-title">Kostenloser Monitor-Schaerfe-Test - Online-Textklarheit</h1>
          <p class="hero-lede">Rendert ein 1-px-Pixelraster im Lagom-Stil, Textproben in Serif, Sans und Monospace, Farbsaum-Bloecke und ein RGB-Subpixel-Lineal zur Beurteilung der Bildschirmschaerfe.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#monitor-sharpness-test">Test starten</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Alle Tools anzeigen</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/monitor-sharpness-test/hero.jpg'); ?>" width="1200" height="800" alt="Kostenloser Monitor-Schaerfe-Test - Online-Textklarheit" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="monitor-sharpness-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Haupt-Tool</p>
          <h2>Monitor-Schaerfe-Test</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/monitor_sharpness_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'monitor-sharpness-test'; $localizedRelatedCategory = 'screen'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-de.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
