<?php
/**
 * German localized landing page for mouse-spin-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-de.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Maus-Dreh-Test - 360° Rotations-Zähler';
$pageDescription = 'Maus-Spin-Test: Zählt volle 360°-Drehungen in 15-, 30- oder 60-Sekunden-Sitzungen mit Spitzenerkennung von Drehungen pro Sekunde. Ohne Installation, live im Browser.';
?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('mouse-spin-test.php'); ?>">
  <link rel="alternate" hreflang="de" href="<?php echo absoluteUrl('languages/german/mouse-spin-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('mouse-spin-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-de.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Maus-Diagnose</p>
          <h1 class="hero-title">Maus-Dreh-Test</h1>
          <p class="hero-lede">Wie viele volle 360°-Rotationen schaffst du mit der Maus in 30 Sekunden? Halten und um den Mittelpunkt drehen.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#mouse-spin-test">Losdrehen</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Alle Tools</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="mouse-spin-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Maus-Diagnose</p>
          <h2>Maus-Dreh-Test</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/mouse-spin-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-de.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
