<?php
/**
 * german localized landing page for online-ruler
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-de.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Online-Lineal in Originalgroesse - cm und Zoll mit Kalibrierung';
$pageDescription = 'Kostenloses Online-Lineal in Originalgroesse am Bildschirm. Miss in cm, mm und Zoll. Kalibriere mit einer Kreditkarte (ISO ID-1) oder durch Eingabe des Monitor-DPI.';
?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('online-ruler.php'); ?>">
  <link rel="alternate" hreflang="de" href="<?php echo absoluteUrl('languages/german/online-ruler.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('online-ruler.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('online_ruler', [['name'=>'Home','url'=>'/'],['name'=>'Online-Lineal in Originalgroesse - cm und Zoll mit Kalibrierung','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-de.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Rechner</p>
          <h1 class="hero-title">Online-Lineal in Originalgroesse - cm und Zoll mit Kalibrierung</h1>
          <p class="hero-lede">SVG-Lineal in cm und Zoll, das du mit einer echten Kreditkarte (ISO ID-1) oder deinem DPI an deinen Bildschirm anpasst. Die Kalibrierung wird im Browser gespeichert.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#online-ruler">Lineal oeffnen</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Alle Tools anzeigen</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/online-ruler/hero.jpg'); ?>" width="1200" height="800" alt="Online-Lineal in Originalgroesse - cm und Zoll mit Kalibrierung" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="online-ruler">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Haupt-Tool</p>
          <h2>Online-Lineal</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/online_ruler_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/online-ruler.php'; ?>
    <?php $currentTool = 'mouse'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/online-ruler.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-de.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
