<?php
/**
 * german localized landing page for ram-latency-calculator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-de.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'RAM-Latenz-Rechner - CAS zu Nanosekunden';
$pageDescription = 'Wandelt CAS-Latenz (CL) und Geschwindigkeit (MT/s) in echte Nanosekunden um. Vergleicht DDR4- und DDR5-Kits nebeneinander.';
?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('ram-latency-calculator.php'); ?>">
  <link rel="alternate" hreflang="de" href="<?php echo absoluteUrl('languages/german/ram-latency-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('ram-latency-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('ram_latency_calc', [['name'=>'Home','url'=>'/'],['name'=>'RAM-Latenz-Rechner','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-de.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Rechner</p>
          <h1 class="hero-title">RAM-Latenz-Rechner</h1>
          <p class="hero-lede">Wandelt CL und MT/s mit der Formel ns = (CL × 2000) / MT/s in echte Nanosekunden um. Vergleicht zwei DDR4- oder DDR5-Kits nebeneinander oder löst rückwärts: welches CL nötig ist, um ein ns-Ziel zu erreichen.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#ram-latency-calculator">Berechnen</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Alle Tools anzeigen</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/ram-latency-calculator/hero.jpg'); ?>" width="1200" height="800" alt="RAM-Latenz-Rechner" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="ram-latency-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Haupt-Tool</p>
          <h2>RAM-Latenz-Rechner</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/ram_latency_calc_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'ram-latency-calculator'; $localizedRelatedCategory = 'mouse'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-de.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
