<?php
/**
 * German localized landing page for resolution-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-de.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Bildschirmauflösungs-Test - Auflösung, DPR, Farbtiefe';
$pageDescription = 'Bildschirmauflösungstest: Live-Anzeige von Auflösung, nativen Pixeln, DPR, Farbtiefe und Gamut. Prüft die tatsächliche Ausgabe Ihres Monitors sofort, ohne Installation.';
?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('resolution-test.php'); ?>">
  <link rel="alternate" hreflang="de" href="<?php echo absoluteUrl('languages/german/resolution-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('resolution-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-de.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Bildschirm-Diagnose</p>
          <h1 class="hero-title">Bildschirmauflösungs-Test</h1>
          <p class="hero-lede">Sofortige Anzeige aller Bildschirm-Eigenschaften: CSS-Auflösung + native Pixel, DPR, Farbtiefe, Gamut, Viewport, Orientierung, Seitenverhältnis. Aktualisiert beim Skalieren.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#resolution-test">Meine Auflösung</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Alle Tools</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="resolution-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Bildschirm-Diagnose</p>
          <h2>Bildschirmauflösungs-Test</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/resolution-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-de.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
