<?php
/**
 * German localized landing page for screen-size-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-de.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Bildschirmgrößen-Rechner - Diagonale, Breite, Höhe';
$pageDescription = 'Bildschirmgrößen-Rechner: Berechnet Diagonale, Breite, Höhe und sichtbare Fläche aus Seitenverhältnis und einer Messung — in Zoll und Zentimetern. Kostenlos, sofort.';
?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('screen-size-calculator.php'); ?>">
  <link rel="alternate" hreflang="de" href="<?php echo absoluteUrl('languages/german/screen-size-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('screen-size-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-de.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Bildschirm-Rechner</p>
          <h1 class="hero-title">Bildschirmgrößen-Rechner</h1>
          <p class="hero-lede">Gib Seitenverhältnis und eine Messung ein. Das Tool berechnet die anderen beiden in Zoll und cm plus die sichtbare Fläche.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#screen-size-calculator">Rechner öffnen</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Alle Tools</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="screen-size-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Bildschirm-Rechner</p>
          <h2>Bildschirmgrößen-Rechner</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/screen-size-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-de.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
