<?php
/**
 * German localized landing page for sound-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-de.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'Sound-Test - Lautsprecher- und Kopfhörer-Kanaltest';
$pageDescription = 'Kostenloser Sound-Test: Prüft linken/rechten Kanal von Lautsprechern und Kopfhörern, plus Frequenzsweep 100 Hz → 10 kHz. Ohne Installation, direkt im Browser.';
?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('sound-test.php'); ?>">
  <link rel="alternate" hreflang="de" href="<?php echo absoluteUrl('languages/german/sound-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('sound-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-de.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">Audio-Diagnose</p>
          <h1 class="hero-title">Sound-Test</h1>
          <p class="hero-lede">Prüfe linke, rechte und Stereo-Kanäle mit reinen Sinus-Tönen. Ping-Pong-Modus für A/B der zwei Lautsprecher. Sweep 100 Hz → 10 kHz für den Frequenzbereich.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#sound-test">Sound-Test starten</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">Alle Tools</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="sound-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">Audio-Diagnose</p>
          <h2>Sound-Test</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/sound-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-de.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
