<?php
// Localized labels for burn-in-test — auto-generated by generate-locale-wrappers.py
$bi_labels = [
    'aria' => 'Teste de burn-in OLED e retencao de imagem',
    'instruction' => 'Clique Tela cheia. Use setas ou botoes para trocar cores. Branco solido por 30-60 s revela retencao. Esc para sair.',
    'mode' => 'Modo',
    'mode_cycle' => 'Ciclo de cores (W, K, R, G, B, C, M, Y)',
    'mode_checker' => 'Xadrez fino',
    'mode_scroll' => 'Refrescador deslizante',
    'auto' => 'Auto-avanco',
    'auto_off' => 'Desligado',
    'auto_5' => 'A cada 5 s',
    'auto_15' => 'A cada 15 s',
    'auto_60' => 'A cada 60 s',
    'fullscreen' => 'Tela cheia',
    'exit_fs' => 'Sair',
    'next' => 'Proximo',
    'prev' => 'Anterior',
    'current_color' => 'Cor atual',
    'reference' => 'Dica: deixe o refrescador rodando a noite para ajudar o OLED com retencao leve. Burn-in permanente (apos 8 h de branco) nao tem conserto.',
];
include __DIR__ . '/../../../tools/burn_in_tool.php';
