<?php
// Localized labels for edpi-calculator — auto-generated by generate-locale-wrappers.py
$ec_labels = [
    'aria' => 'Calculadora de eDPI - DPI efetivo para gaming',
    'instruction' => 'Digite DPI do mouse e sensibilidade do jogo. eDPI = DPI x sensibilidade, para comparar mira entre jogos.',
    'dpi' => 'DPI do mouse',
    'sens' => 'Sensibilidade no jogo',
    'edpi' => 'DPI efetivo (eDPI)',
    'cm_360' => 'cm/360 (estimado, yaw 0.022 padrao)',
    'reference' => 'Referencia pro: 800 DPI x 0.5 sens = 400 eDPI',
];
include __DIR__ . '/../../../tools/edpi_calculator_tool.php';
