<?php
// Localized labels for mouse-spin-test — auto-generated by generate-locale-wrappers.py
$ms_labels = [
    'aria' => 'Teste de giro do mouse - conta rotacoes 360',
    'instruction' => 'Clique em Iniciar, posicione o cursor no pad, segure o botao esquerdo e gire ao redor do ponto central. Cada 360 conta.',
    'duration' => 'Duracao',
    'dur_15' => '15 segundos',
    'dur_30' => '30 segundos',
    'dur_60' => '60 segundos',
    'start' => 'Iniciar',
    'stop' => 'Parar',
    'reset' => 'Reiniciar',
    'pad_hint' => 'Segure o botao esquerdo e gire ao redor do centro.',
    'time_left' => 'Tempo restante',
    'spins' => 'Giros',
    'peak_sps' => 'Giros/s pico',
    'degrees' => 'Rotacao total',
    'direction' => 'Direcao',
    'dir_cw' => 'Horario',
    'dir_ccw' => 'Anti-horario',
    'dir_idle' => '-',
    'reference' => 'Dica: DPI alto permite mais giros com menos movimento. Teste nos dois sentidos, lento vs rapido.',
];
include __DIR__ . '/../../../tools/mouse_spin_tool.php';
