<?php
// Localized labels for resolution-test — auto-generated by generate-locale-wrappers.py
$rt_labels = [
    'aria' => 'Teste de resolucao de tela',
    'instruction' => 'Tudo atualiza ao vivo. Redimensione ou de zoom para ver viewport e DPR mudarem.',
    'screen_size' => 'Resolucao de tela',
    'native_res' => 'Resolucao fisica nativa',
    'viewport' => 'Viewport (esta aba)',
    'dpr' => 'Device pixel ratio',
    'color_depth' => 'Profundidade de cor',
    'color_gamut' => 'Gamut de cor',
    'pixel_depth' => 'Pixel depth',
    'orientation' => 'Orientacao',
    'aspect' => 'Razao de aspecto',
    'avail' => 'Tela disponivel',
    'reference' => 'Dica: DPR multiplica pixels CSS para fisicos. Retina / celular 2-3. Nativo = CSS x DPR.',
];
include __DIR__ . '/../../../tools/resolution_test_tool.php';
