<?php
// Localized labels for screen-size-calculator — auto-generated by generate-locale-wrappers.py
$ss_labels = [
    'aria' => 'Calculadora de tamanho de tela',
    'instruction' => 'Escolha a proporcao e informe diagonal, largura ou altura. As outras duas preenchem em polegadas e cm. Area visivel tambem calculada.',
    'aspect' => 'Razao de aspecto',
    'measured' => 'Eu sei a',
    'measure_diagonal' => 'diagonal',
    'measure_width' => 'largura',
    'measure_height' => 'altura',
    'value' => 'Valor',
    'unit' => 'Unidade',
    'diagonal' => 'Diagonal',
    'width' => 'Largura',
    'height' => 'Altura',
    'area' => 'Area visivel',
    'reference' => 'Dica: TVs sao anunciadas pela diagonal, mas o que importa na estante e a largura. 55 16:9 != 55 21:9.',
];
include __DIR__ . '/../../../tools/screen_size_calc_tool.php';
