<?php
// Localized labels for sound-test — auto-generated by generate-locale-wrappers.py
$st_labels = [
    'aria' => 'Teste de som - verificacao de canais e varredura de frequencia',
    'instruction' => 'Primeira vez? O navegador pedira permissao de audio no primeiro Play. Coloque o volume do sistema em ~30% antes de iniciar - os tons podem ser altos.',
    'channel' => 'Canal',
    'ch_left' => 'Somente esquerdo',
    'ch_right' => 'Somente direito',
    'ch_both' => 'Ambos',
    'ch_pingpong' => 'Ping-pong (alterna E e D)',
    'freq' => 'Frequencia',
    'freq_value' => 'Hz',
    'volume' => 'Volume',
    'volume_value' => '%',
    'play' => 'Tocar',
    'stop' => 'Parar',
    'sweep' => 'Varredura 100 Hz a 10 kHz',
    'now_playing' => 'Tocando agora',
    'idle' => 'Inativo',
    'reference' => 'Dica: se no modo Ambos so toca um lado, o problema e cabeamento (jack TRS mal encaixado, cabo ruim, BT mal pareado) - nao software.',
];
include __DIR__ . '/../../../tools/sound_test_tool.php';
