<?php
// Localized labels for viewing-distance-calculator — auto-generated by generate-locale-wrappers.py
$vd_labels = [
    'aria' => 'Calculadora de distancia de visao',
    'instruction' => 'Informe a diagonal da tela e a resolucao. A ferramenta retorna THX otimo (36 FoV), SMPTE cinema (30 FoV) e a distancia limite onde 4K ja nao se distingue de 1080p.',
    'diagonal' => 'Diagonal da tela',
    'resolution' => 'Resolucao nativa',
    'unit' => 'Unidade',
    'thx' => 'THX otimo (36 FoV)',
    'smpte' => 'SMPTE cinema (30 FoV)',
    'uhd4k' => 'Distancia max 4K UHD',
    'min_4k' => 'Alem disso, 4K = 1080p ao olho',
    'angle' => 'Angulo no THX',
    'reference' => 'Dica: THX = 36 (imersivo), SMPTE = 30 (cinema confortavel). Alem da distancia 4K max, comprar 4K nao ajuda nesse tamanho.',
];
include __DIR__ . '/../../../tools/viewing_distance_calc_tool.php';
