<?php
// Localized labels for apm-test — auto-generated by generate-locale-wrappers.py
$apm_labels = [
    'aria' => 'Тест APM - счётчик действий в минуту',
    'instruction' => 'Нажмите Старт, наведите фокус на пад и выполняйте обычные действия (клики, горячие клавиши, перетаскивания). Каждый клик или клавиша считается.',
    'start' => 'Старт',
    'stop' => 'Стоп',
    'reset' => 'Сброс',
    'current_apm' => 'Текущий APM',
    'peak_apm' => 'Пиковый APM',
    'avg_apm' => 'Среднее за сессию',
    'total_actions' => 'Всего действий',
    'elapsed' => 'Время',
    'clicks' => 'Клики',
    'keys' => 'Клавиши',
    'pad_hint' => 'Нажмите здесь, чтобы сфокусировать пад.',
    'reference' => 'Совет: RTS casual 40-80, Silver 100, Platinum 200, Master 300+, pro 300-450 устойчиво с пиками до 800.',
];
include __DIR__ . '/../../../tools/apm_test_tool.php';
