<?php
// Localized labels for burn-in-test — auto-generated by generate-locale-wrappers.py
$bi_labels = [
    'aria' => 'Тест выгорания OLED и остаточного изображения',
    'instruction' => 'Нажмите Полный экран. Используйте стрелки или кнопки для смены цветов. Сплошной белый 30-60 с выявит остаточное изображение. Esc — выход.',
    'mode' => 'Режим',
    'mode_cycle' => 'Цикл цветов (W, K, R, G, B, C, M, Y)',
    'mode_checker' => 'Мелкая шахматка',
    'mode_scroll' => 'Бегущий обновитель',
    'auto' => 'Авто-переход',
    'auto_off' => 'Выкл',
    'auto_5' => 'Каждые 5 с',
    'auto_15' => 'Каждые 15 с',
    'auto_60' => 'Каждые 60 с',
    'fullscreen' => 'Полный экран',
    'exit_fs' => 'Выход',
    'next' => 'Далее',
    'prev' => 'Назад',
    'current_color' => 'Текущий цвет',
    'reference' => 'Совет: оставьте обновитель на ночь для лёгкого выгорания OLED. Постоянное выгорание (после 8 ч белого) уже не починить.',
];
include __DIR__ . '/../../../tools/burn_in_tool.php';
