<?php
// Localized labels for color-range-test — auto-generated by generate-locale-wrappers.py
$cr_labels = [
    'aria' => 'Тест диапазона цвета - обнаруживает Limited vs Full RGB',
    'instruction' => 'Смотрите на каждую строку. FULL-дисплей показывает каждый патч отличным. LIMITED-дисплей сливает первые (в чисто чёрный) и последние (в чисто белый).',
    'near_black' => 'Рядом с чёрным (RGB 0-31)',
    'near_white' => 'Рядом с белым (RGB 224-255)',
    'ramp' => 'Непрерывный градиент (0 до 255)',
    'fullscreen' => 'Полный экран',
    'exit_fs' => 'Выход',
    'reference' => 'Совет: Windows часто отправляет HDMI в Limited по умолчанию. NVIDIA: Разрешение > Динамический диапазон = Full.',
];
include __DIR__ . '/../../../tools/color_range_tool.php';
