<?php
// Localized labels for edpi-calculator — auto-generated by generate-locale-wrappers.py
$ec_labels = [
    'aria' => 'Калькулятор eDPI - эффективный DPI для гейминга',
    'instruction' => 'Введите DPI мыши и чувствительность в игре. eDPI = DPI × чувствительность, для сравнения прицеливания между играми.',
    'dpi' => 'DPI мыши',
    'sens' => 'Чувствительность в игре',
    'edpi' => 'Эффективный DPI (eDPI)',
    'cm_360' => 'см/360 (оценка, yaw 0.022)',
    'reference' => 'Про-референс: 800 DPI × 0.5 = 400 eDPI',
];
include __DIR__ . '/../../../tools/edpi_calculator_tool.php';
