<?php
// Localized labels for screen-size-calculator — auto-generated by generate-locale-wrappers.py
$ss_labels = [
    'aria' => 'Калькулятор размера экрана',
    'instruction' => 'Выберите соотношение сторон и введите диагональ, ширину или высоту. Другие две заполняются в дюймах и см. Видимая площадь тоже считается.',
    'aspect' => 'Соотношение сторон',
    'measured' => 'Я знаю',
    'measure_diagonal' => 'диагональ',
    'measure_width' => 'ширина',
    'measure_height' => 'высота',
    'value' => 'Значение',
    'unit' => 'Единица',
    'diagonal' => 'Диагональ',
    'width' => 'Ширина',
    'height' => 'Высота',
    'area' => 'Видимая площадь',
    'reference' => 'Совет: ТВ продают по диагонали, но на тумбу встаёт ширина. 55 16:9 и 55 21:9 очень разные.',
];
include __DIR__ . '/../../../tools/screen_size_calc_tool.php';
