<?php
// Localized labels for viewing-distance-calculator — auto-generated by generate-locale-wrappers.py
$vd_labels = [
    'aria' => 'Калькулятор дистанции просмотра',
    'instruction' => 'Введите диагональ экрана и разрешение. Инструмент даёт THX оптимум (36° FoV), SMPTE кино (30° FoV) и максимальную дистанцию, на которой 4K ещё отличается от 1080p.',
    'diagonal' => 'Диагональ экрана',
    'resolution' => 'Нативное разрешение',
    'unit' => 'Единица',
    'thx' => 'THX оптимум (36° FoV)',
    'smpte' => 'SMPTE кино (30° FoV)',
    'uhd4k' => 'Макс дистанция 4K UHD',
    'min_4k' => 'Дальше 4K = 1080p на глаз',
    'angle' => 'Угол при THX',
    'reference' => 'Совет: THX = 36° (погружение), SMPTE = 30° (кино-комфорт). Дальше максимума 4K покупать 4K на этом размере бесполезно.',
];
include __DIR__ . '/../../../tools/viewing_distance_calc_tool.php';
