<?php
// Localized labels for aspect-ratio-calculator — auto-generated by generate-locale-wrappers.py
$ar_labels = [
    'aria' => 'حاسبة نسبة العرض - تحل العرض أو الارتفاع أو النسبة',
    'instruction' => 'عدّل اثنين من ثلاثة (عرض، ارتفاع، نسبة). تحل الأداة الثالث. تقبل النسبة \'16:9\' أو \'1.7778\'.',
    'preset' => 'نسبة مسبقة',
    'width' => 'العرض (بكسل)',
    'height' => 'الارتفاع (بكسل)',
    'ratio' => 'نسبة العرض',
    'simplified' => 'مبسّط',
    'decimal' => 'عشري',
    'orientation' => 'الاتجاه',
    'landscape' => 'أفقي',
    'portrait' => 'عمودي',
    'square' => 'مربع',
    'reference' => 'نصيحة: أدخل العرض والارتفاع لرؤية النسبة أو اختر إعداداً مسبقاً.',
];
include __DIR__ . '/../../../tools/aspect_calc_tool.php';
