<?php
// Localized labels for edpi-calculator — auto-generated by generate-locale-wrappers.py
$ec_labels = [
    'aria' => 'حاسبة eDPI - DPI الفعال في الألعاب',
    'instruction' => 'أدخل DPI الماوس وحساسية اللعبة. eDPI = DPI × الحساسية، لمقارنة التصويب بين الألعاب.',
    'dpi' => 'DPI الماوس',
    'sens' => 'حساسية اللعبة',
    'edpi' => 'DPI الفعال (eDPI)',
    'cm_360' => 'سم/360 (تقديري، yaw 0.022 افتراضي)',
    'reference' => 'مرجع احترافي: 800 DPI × 0.5 حساسية = 400 eDPI',
];
include __DIR__ . '/../../../tools/edpi_calculator_tool.php';
