<?php
// Localized labels for resolution-test — auto-generated by generate-locale-wrappers.py
$rt_labels = [
    'aria' => 'اختبار دقة الشاشة',
    'instruction' => 'كل القيم تتحدث لحظياً. غيّر حجم النافذة أو قم بالتكبير لرؤية تغير viewport وDPR.',
    'screen_size' => 'دقة الشاشة',
    'native_res' => 'الدقة الفيزيائية الأصلية',
    'viewport' => 'Viewport (هذه التبويبة)',
    'dpr' => 'نسبة البكسل للجهاز',
    'color_depth' => 'عمق الألوان',
    'color_gamut' => 'نطاق الألوان',
    'pixel_depth' => 'عمق البكسل',
    'orientation' => 'الاتجاه',
    'aspect' => 'نسبة العرض',
    'avail' => 'المساحة المتاحة',
    'reference' => 'نصيحة: DPR يضرب بكسلات CSS للوصول إلى الفيزيائية. Retina / الهواتف 2-3. الأصلية = CSS × DPR.',
];
include __DIR__ . '/../../../tools/resolution_test_tool.php';
