<?php
// Localized labels for screen-uniformity-test — auto-generated by generate-locale-wrappers.py
$su_labels = [
    'aria' => 'اختبار تجانس الشاشة',
    'instruction' => 'اختر لوناً وسطوعاً، ثم ملء الشاشة. اللوحات الجيدة تُظهر لوناً منتظماً من الحافة إلى الحافة. السطوع غير المنتظم أو الزوايا الملونة أو البقع الغائمة تكشف مشاكل التجانس.',
    'color' => 'اللون',
    'c_gray' => 'رمادي متوسط (يكشف السحب)',
    'c_black' => 'قرب الأسود (يكشف IPS glow وتسرب الإضاءة)',
    'c_white' => 'أبيض (يكشف هبوط السطوع)',
    'c_red' => 'أحمر',
    'c_green' => 'أخضر',
    'c_blue' => 'أزرق',
    'brightness' => 'السطوع',
    'fullscreen' => 'ملء الشاشة',
    'exit_fs' => 'خروج',
    'reference' => 'نصيحة: اختبر عند 20 و50 و80% من السطوع - المشاكل قد تظهر في نطاق واحد فقط. ابتعد 60-90 سم وأطفئ الأضواء لاختبار السحب.',
];
include __DIR__ . '/../../../tools/screen_uniformity_tool.php';
