<?php
// Localized labels for viewing-distance-calculator — auto-generated by generate-locale-wrappers.py
$vd_labels = [
    'aria' => 'حاسبة مسافة المشاهدة',
    'instruction' => 'أدخل قطر الشاشة والدقة. تُرجع الأداة THX الأمثل (36°)، SMPTE سينما (30°)، والمسافة القصوى التي يظل عندها 4K مميَّزاً عن 1080p.',
    'diagonal' => 'قطر الشاشة',
    'resolution' => 'الدقة الأصلية',
    'unit' => 'الوحدة',
    'thx' => 'THX الأمثل (36°)',
    'smpte' => 'SMPTE سينما (30°)',
    'uhd4k' => 'الحد الأقصى لـ4K UHD',
    'min_4k' => 'بعدها 4K = 1080p للعين',
    'angle' => 'الزاوية عند THX',
    'reference' => 'نصيحة: THX = 36° (غامر)، SMPTE = 30° (سينما مريحة). إذا جلست أبعد من الحد الأقصى لـ4K فلن تستفيد من دقة 4K بهذا الحجم.',
];
include __DIR__ . '/../../../tools/viewing_distance_calc_tool.php';
