<?php
/**
 * Korean localized landing page for apm-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ko.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'APM 테스트 - RTS·MOBA용 분당 액션';
$pageDescription = '무료 APM 테스트. 키와 클릭을 60초 롤링 윈도우로 카운트. RTS·MOBA용.';
?>
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('apm-test.php'); ?>">
  <link rel="alternate" hreflang="ko" href="<?php echo absoluteUrl('languages/korean/apm-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('apm-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ko.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">게이밍 진단</p>
          <h1 class="hero-title">APM 테스트</h1>
          <p class="hero-lede">StarCraft, DotA, LoL 등 마이크로가 중요한 게임에서 분당 액션을 측정. 60초 롤링 윈도우와 피크 APM, 세션 평균.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#apm-test">APM 테스트 시작</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">모든 도구</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="apm-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">게이밍 진단</p>
          <h2>APM 테스트</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/apm-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ko.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
