<?php
/**
 * korean localized landing page for auditory-reaction-time-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ko.php'; if (file_exists($__c)) include $__c;
$pageTitle = '청각 반응 시간 테스트 - 소리 반응 속도';
$pageDescription = 'Web Audio API로 소리 반응 시간을 측정합니다. 5라운드 평균/최고/최저, 조기 클릭 감지 포함.';
?>
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('auditory-reaction-time-test.php'); ?>">
  <link rel="alternate" hreflang="ko" href="<?php echo absoluteUrl('languages/korean/auditory-reaction-time-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('auditory-reaction-time-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('auditory_reaction_time', [['name'=>'Home','url'=>'/'],['name'=>'청각 반응 시간 테스트','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ko.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">오디오 진단</p>
          <h1 class="hero-title">청각 반응 시간 테스트</h1>
          <p class="hero-lede">소리에 얼마나 빠르게 반응하는지 밀리초로 측정. 1.5-4초 랜덤 지연 후 비프음이 울립니다. 5라운드 평균/최고/최저 기록, 조기 클릭 감지 포함.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#auditory-reaction-time-test">테스트 시작</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">모든 도구 보기</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/auditory-reaction-time-test/hero.jpg'); ?>" width="1200" height="800" alt="청각 반응 시간 테스트" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="auditory-reaction-time-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">주요 도구</p>
          <h2>청각 반응 시간 테스트</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/auditory_reaction_time_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/auditory-reaction-time-test.php'; ?>
    <?php $currentTool = 'audio'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/auditory-reaction-time-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ko.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
