<?php
/**
 * Korean localized landing page for fps-test
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ko.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'FPS 테스트 - 브라우저 프레임 레이트';
$pageDescription = '무료 FPS 테스트. 평균·최소·최대·1%-low 실시간 측정과 60/120/144/240 Hz 감지.';
?>
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('fps-test.php'); ?>">
  <link rel="alternate" hreflang="ko" href="<?php echo absoluteUrl('languages/korean/fps-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('fps-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ko.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">성능 진단</p>
          <h1 class="hero-title">FPS 테스트</h1>
          <p class="hero-lede">requestAnimationFrame으로 브라우저 프레임 레이트 실시간 측정. 현재 FPS, 평균, 최소, 최대, 1%-low 표시.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#fps-test">테스트 시작</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">모든 도구</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="fps-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">성능 진단</p>
          <h2>FPS 테스트</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/fps-test-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ko.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
