<?php
/**
 * korean localized landing page for gpu-stress-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ko.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'GPU 스트레스 테스트 - WebGL 셰이더 벤치마크';
$pageDescription = 'WebGL2 Mandelbrot 프래그먼트 셰이더로 모든 GPU에 부하를 겁니다. FPS, 최저 FPS, 소프트웨어 렌더링 감지.';
?>
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('gpu-stress-test.php'); ?>">
  <link rel="alternate" hreflang="ko" href="<?php echo absoluteUrl('languages/korean/gpu-stress-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('gpu-stress-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('gpu_stress_test', [['name'=>'Home','url'=>'/'],['name'=>'GPU 스트레스 테스트','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ko.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">하드웨어 벤치마크</p>
          <h1 class="hero-title">GPU 스트레스 테스트</h1>
          <p class="hero-lede">WebGL2에서 고반복 Mandelbrot 프래그먼트 셰이더를 렌더링하여 모든 GPU에 부하를 줍니다. 즉시 FPS, 1초 평균, 최저 FPS를 보고하고 소프트웨어 렌더링(SwiftShader) 여부를 감지합니다.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#gpu-stress-test">스트레스 시작</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">모든 도구 보기</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/gpu-stress-test/hero.jpg'); ?>" width="1200" height="800" alt="GPU 스트레스 테스트" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="gpu-stress-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">주요 도구</p>
          <h2>GPU 스트레스 테스트</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/gpu_stress_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/gpu-stress-test.php'; ?>
    <?php $currentTool = 'screen'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/gpu-stress-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ko.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
