<?php
/**
 * korean localized landing page for monitor-sharpness-test
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ko.php'; if (file_exists($__c)) include $__c;
$pageTitle = '모니터 선명도 테스트 - 온라인 텍스트 선명도';
$pageDescription = '무료 모니터 선명도 테스트. Lagom 스타일의 1픽셀 그리드, 다양한 크기의 텍스트 샘플, 색 번짐 블록, RGB 서브픽셀 자.';
?>
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('monitor-sharpness-test.php'); ?>">
  <link rel="alternate" hreflang="ko" href="<?php echo absoluteUrl('languages/korean/monitor-sharpness-test.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('monitor-sharpness-test.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('monitor_sharpness_test', [['name'=>'Home','url'=>'/'],['name'=>'무료 모니터 선명도 테스트 - 온라인 텍스트 선명도 검사','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ko.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">디스플레이 진단</p>
          <h1 class="hero-title">무료 모니터 선명도 테스트 - 온라인 텍스트 선명도 검사</h1>
          <p class="hero-lede">Lagom 스타일의 1px 픽셀 그리드, 세리프·산세리프·고정폭 텍스트 샘플, 색 번짐 블록, RGB 서브픽셀 자를 그려 모니터의 선명도를 평가합니다.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#monitor-sharpness-test">테스트 시작</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">모든 도구 보기</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/monitor-sharpness-test/hero.jpg'); ?>" width="1200" height="800" alt="무료 모니터 선명도 테스트 - 온라인 텍스트 선명도 검사" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="monitor-sharpness-test">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">주요 도구</p>
          <h2>모니터 선명도 테스트</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/monitor_sharpness_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/monitor-sharpness-test.php'; ?>
    <?php $currentTool = 'screen'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/monitor-sharpness-test.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ko.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
