<?php
/**
 * korean localized landing page for pitch-detector
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ko.php'; if (file_exists($__c)) include $__c;
$pageTitle = '온라인 피치 디텍터 - 내가 부르는 음은?';
$pageDescription = '브라우저에서 작동하는 무료 피치 디텍터. 마이크에 노래하거나 연주하면 주파수(Hz), 가장 가까운 음(C0-C8), 옥타브, 센트 편차를 실시간 표시.';
?>
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('pitch-detector.php'); ?>">
  <link rel="alternate" hreflang="ko" href="<?php echo absoluteUrl('languages/korean/pitch-detector.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('pitch-detector.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('pitch_detector', [['name'=>'Home','url'=>'/'],['name'=>'무료 온라인 피치 디텍터 - 내가 부르는 음은?','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ko.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">오디오 진단</p>
          <h1 class="hero-title">무료 온라인 피치 디텍터 - 내가 부르는 음은?</h1>
          <p class="hero-lede">노래하거나 흥얼거리거나 연주하세요. 주파수, 음 이름, 센트 편차를 즉시 표시합니다. 최근 10초간의 스크롤 그래프 제공.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#pitch-detector">디텍터 시작</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">모든 도구 보기</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/pitch-detector/hero.jpg'); ?>" width="1200" height="800" alt="무료 온라인 피치 디텍터 - 내가 부르는 음은?" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="pitch-detector">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">주요 도구</p>
          <h2>피치 디텍터</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/pitch_detector_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'pitch-detector'; $localizedRelatedCategory = 'audio'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ko.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
