<?php
/**
 * korean localized landing page for ram-latency-calculator
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ko.php'; if (file_exists($__c)) include $__c;
$pageTitle = 'RAM 지연 시간 계산기 - CAS를 나노초로';
$pageDescription = 'CAS 지연(CL)과 속도(MT/s)를 실제 나노초로 변환합니다. DDR4와 DDR5 키트 비교.';
?>
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('ram-latency-calculator.php'); ?>">
  <link rel="alternate" hreflang="ko" href="<?php echo absoluteUrl('languages/korean/ram-latency-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('ram-latency-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('ram_latency_calc', [['name'=>'Home','url'=>'/'],['name'=>'RAM 지연 시간 계산기','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ko.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">계산기</p>
          <h1 class="hero-title">RAM 지연 시간 계산기</h1>
          <p class="hero-lede">ns = (CL × 2000) / MT/s 공식으로 CL과 MT/s를 실제 나노초로 변환합니다. DDR4나 DDR5 키트 2개를 나란히 비교하거나 목표 ns에 필요한 CL을 역산할 수 있습니다.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#ram-latency-calculator">계산</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">모든 도구 보기</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/ram-latency-calculator/hero.jpg'); ?>" width="1200" height="800" alt="RAM 지연 시간 계산기" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="ram-latency-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">주요 도구</p>
          <h2>RAM 지연 시간 계산기</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/ram_latency_calc_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php include __DIR__ . '/../../help/seo-content/ram-latency-calculator.php'; ?>
    <?php $currentTool = 'mouse'; include __DIR__ . '/../../includes/related-tools.php'; ?>
    <?php include __DIR__ . '/../../help/ram-latency-calculator.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ko.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
