<?php
/**
 * Korean localized landing page for screen-size-calculator
 * Auto-generated by generate-locales.py. Edit translations in that file.
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ko.php'; if (file_exists($__c)) include $__c;
$pageTitle = '화면 크기 계산기 - 대각선, 가로, 세로';
$pageDescription = '무료 화면 크기 계산기. 인치와 cm 단위로 대각선, 가로, 세로 계산.';
?>
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('screen-size-calculator.php'); ?>">
  <link rel="alternate" hreflang="ko" href="<?php echo absoluteUrl('languages/korean/screen-size-calculator.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('screen-size-calculator.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ko.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">화면 계산기</p>
          <h1 class="hero-title">화면 크기 계산기</h1>
          <p class="hero-lede">화면 비율과 한 가지 치수를 입력하세요. 나머지 두 치수를 인치와 cm로 계산하고 가시 영역도 표시.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#screen-size-calculator">계산기 열기</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">모든 도구</a>
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="screen-size-calculator">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">화면 계산기</p>
          <h2>화면 크기 계산기</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/tools/screen-size-calculator-tool.php'; ?></section>
    </section>
  </main>
  <?php $__f = __DIR__ . '/footer-ko.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
