<?php
/**
 * korean localized landing page for webcam-mirror
 * Auto-generated by scripts/gen-localized-wrappers.py
 */
include __DIR__ . '/../../config.php';
$__c = __DIR__ . '/config-ko.php'; if (file_exists($__c)) include $__c;
$pageTitle = '온라인 웹캠 거울 - 카메라를 가상 거울로';
$pageDescription = '무료 웹캠 거울. 수평 반전, 밝기/대비 슬라이더, 그리드 오버레이, PNG 스냅샷 지원. 업로드 없음.';
?>
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $pageTitle; ?></title>
  <meta name="description" content="<?php echo $pageDescription; ?>">
  <link rel="alternate" hreflang="en" href="<?php echo absoluteUrl('webcam-mirror.php'); ?>">
  <link rel="alternate" hreflang="ko" href="<?php echo absoluteUrl('languages/korean/webcam-mirror.php'); ?>">
  <link rel="alternate" hreflang="x-default" href="<?php echo absoluteUrl('webcam-mirror.php'); ?>">
  <?php include __DIR__ . '/../../includes/head-common.php'; ?>
  <link rel="stylesheet" href="<?php echo url('assets/css/index-modern.css'); ?>">
  <?php include_once __DIR__ . '/../../includes/schema.php'; echo generateToolPageSchema('webcam_mirror', [['name'=>'Home','url'=>'/'],['name'=>'온라인 웹캠 거울 - 카메라를 가상 거울로 사용','url'=>'']]); ?>
</head>
<body class="landing-page">
  <?php $__h = __DIR__ . '/header-ko.php'; if (file_exists($__h)) include $__h; else include __DIR__ . '/../../header.php'; ?>
  <main id="main-content" class="landing-main">
    <section class="landing-hero">
      <div class="container landing-hero-grid">
        <div class="hero-copy">
          <p class="hero-kicker">기기 센서</p>
          <h1 class="hero-title">온라인 웹캠 거울 - 카메라를 가상 거울로 사용</h1>
          <p class="hero-lede">미러 모드, 밝기·대비, 3등분 그리드, 즉시 스냅샷 다운로드 기능을 갖춘 실시간 카메라 미리보기. 영상은 브라우저에서만 처리.</p>
          <div class="hero-actions">
            <a class="landing-btn landing-btn-primary" href="#webcam-mirror">거울 열기</a>
            <a class="landing-btn landing-btn-ghost" href="#tools">모든 도구 보기</a>
          </div>
        </div>
        <div class="hero-visual">
          <div class="hero-shot">
            <img src="<?php echo url('images/webcam-mirror/hero.jpg'); ?>" width="1200" height="800" alt="온라인 웹캠 거울 - 카메라를 가상 거울로 사용" loading="eager" decoding="async" fetchpriority="high">
          </div>
        </div>
      </div>
    </section>
    <section class="tool-stage" id="webcam-mirror">
      <div class="container tool-stage-header">
        <div>
          <p class="section-kicker">주요 도구</p>
          <h2>웹캠 거울</h2>
        </div>
      </div>
      <section class="tool-shell"><?php include __DIR__ . '/../../tools/webcam_mirror_tool.php'; ?></section>
    </section>
    <?php include __DIR__ . '/../../includes/components/tools-list.php'; ?>
    <?php $localizedToolSlug = 'webcam-mirror'; $localizedRelatedCategory = 'webcam'; include __DIR__ . '/../../includes/components/localized-tool-support.php'; ?>
  </main>
  <?php $__f = __DIR__ . '/footer-ko.php'; if (file_exists($__f)) include $__f; else include __DIR__ . '/../../footer.php'; ?>
</body>
</html>
