<?php
// Localized labels for apm-test — auto-generated by generate-locale-wrappers.py
$apm_labels = [
    'aria' => 'APM-Test - Aktionen-pro-Minute-Zaehler',
    'instruction' => 'Starten druecken, Fokus auf das Pad und normale Aktionen ausfuehren (Klicks, Hotkeys, Drags). Jeder Klick oder Tastendruck zaehlt.',
    'start' => 'Start',
    'stop' => 'Stopp',
    'reset' => 'Zuruecksetzen',
    'current_apm' => 'Aktuelle APM',
    'peak_apm' => 'APM-Peak',
    'avg_apm' => 'Session-Durchschnitt',
    'total_actions' => 'Gesamte Aktionen',
    'elapsed' => 'Zeit',
    'clicks' => 'Klicks',
    'keys' => 'Tasten',
    'pad_hint' => 'Hier klicken fuer Pad-Fokus und Aktionen.',
    'reference' => 'Tipp: RTS casual 40-80, Silver 100, Platin 200, Master 300+, Pro 300-450 mit Peaks bis 800.',
];
include __DIR__ . '/../../../tools/apm_test_tool.php';
