<?php
// Localized labels for aspect-ratio-calculator — auto-generated by generate-locale-wrappers.py
$ar_labels = [
    'aria' => 'Seitenverhaeltnis-Rechner - Breite, Hoehe oder Ratio',
    'instruction' => 'Aendere zwei von drei (Breite, Hoehe, Ratio). Das Tool loest das dritte. Ratio akzeptiert \'16:9\' oder \'1.7778\'.',
    'preset' => 'Voreinstellung',
    'width' => 'Breite (px)',
    'height' => 'Hoehe (px)',
    'ratio' => 'Seitenverhaeltnis',
    'simplified' => 'Vereinfacht',
    'decimal' => 'Dezimal',
    'orientation' => 'Ausrichtung',
    'landscape' => 'Querformat',
    'portrait' => 'Hochformat',
    'square' => 'Quadratisch',
    'reference' => 'Tipp: Breite + Hoehe fuer das Ratio, oder Preset + eine Dimension.',
];
include __DIR__ . '/../../../tools/aspect_calc_tool.php';
