<?php
// Localized labels for mouse-spin-test — auto-generated by generate-locale-wrappers.py
$ms_labels = [
    'aria' => 'Maus-Dreh-Test - zaehlt 360-Rotationen',
    'instruction' => 'Start druecken, Cursor aufs Pad, linke Taste halten und um den Mittelpunkt drehen. Jede volle 360-Drehung ist ein Spin.',
    'duration' => 'Dauer',
    'dur_15' => '15 Sekunden',
    'dur_30' => '30 Sekunden',
    'dur_60' => '60 Sekunden',
    'start' => 'Start',
    'stop' => 'Stopp',
    'reset' => 'Zuruecksetzen',
    'pad_hint' => 'Linke Taste halten und um den Mittelpunkt drehen.',
    'time_left' => 'Zeit',
    'spins' => 'Spins',
    'peak_sps' => 'Spins/s Peak',
    'degrees' => 'Gesamtrotation',
    'direction' => 'Richtung',
    'dir_cw' => 'Im Uhrzeigersinn',
    'dir_ccw' => 'Gegen den UZS',
    'dir_idle' => '-',
    'reference' => 'Tipp: hohe DPI erlaubt mehr Spins mit weniger Handbewegung. Beide Richtungen und langsam vs Flick probieren.',
];
include __DIR__ . '/../../../tools/mouse_spin_tool.php';
