<?php
// Localized labels for screen-uniformity-test — auto-generated by generate-locale-wrappers.py
$su_labels = [
    'aria' => 'Bildschirm-Uniformitaetstest',
    'instruction' => 'Farbe und Helligkeit waehlen, dann Vollbild. Gute Panels zeigen perfekt gleichmaessige Farbe. Unregelmaessige Helligkeit, getoente Ecken oder wolkige Flecken offenbaren Probleme.',
    'color' => 'Farbe',
    'c_gray' => 'Mittelgrau (erkennt Clouding)',
    'c_black' => 'Nahe Schwarz (erkennt IPS Glow + Bleed)',
    'c_white' => 'Weiss (erkennt Helligkeitsabfall)',
    'c_red' => 'Rot',
    'c_green' => 'Gruen',
    'c_blue' => 'Blau',
    'brightness' => 'Helligkeit',
    'fullscreen' => 'Vollbild',
    'exit_fs' => 'Verlassen',
    'reference' => 'Tipp: bei 20, 50 und 80% Helligkeit testen - Probleme erscheinen oft nur in einer Helligkeitsstufe. 60-90 cm Abstand, Licht aus fuer Clouding.',
];
include __DIR__ . '/../../../tools/screen_uniformity_tool.php';
