<?php
// Localized labels for screen-size-calculator — auto-generated by generate-locale-wrappers.py
$ss_labels = [
    'aria' => 'Bildschirmgroessen-Rechner',
    'instruction' => 'Seitenverhaeltnis waehlen, dann Diagonale, Breite oder Hoehe eingeben. Die anderen beiden fuellen sich in Zoll und cm. Sichtflaeche wird auch angezeigt.',
    'aspect' => 'Seitenverhaeltnis',
    'measured' => 'Ich kenne die',
    'measure_diagonal' => 'Diagonale',
    'measure_width' => 'Breite',
    'measure_height' => 'Hoehe',
    'value' => 'Wert',
    'unit' => 'Einheit',
    'diagonal' => 'Diagonale',
    'width' => 'Breite',
    'height' => 'Hoehe',
    'area' => 'Sichtflaeche',
    'reference' => 'Tipp: TVs werden nach Diagonale verkauft, aber was aufs Moebel passt ist die Breite. 55 16:9 != 55 21:9.',
];
include __DIR__ . '/../../../tools/screen_size_calc_tool.php';
