<?php
// Localized labels for viewing-distance-calculator — auto-generated by generate-locale-wrappers.py
$vd_labels = [
    'aria' => 'Sehabstand-Rechner',
    'instruction' => 'Diagonale und Aufloesung eingeben. Das Tool gibt THX-Optimum (36 FoV), SMPTE-Kino (30 FoV) und die maximale Distanz, auf der 4K noch von 1080p unterscheidbar ist.',
    'diagonal' => 'Bildschirmdiagonale',
    'resolution' => 'Native Aufloesung',
    'unit' => 'Einheit',
    'thx' => 'THX optimal (36 FoV)',
    'smpte' => 'SMPTE Kino (30 FoV)',
    'uhd4k' => 'Max 4K UHD Distanz',
    'min_4k' => 'Dahinter: 4K = 1080p fuer das Auge',
    'angle' => 'Winkel bei THX',
    'reference' => 'Tipp: THX = 36 (immersiv), SMPTE = 30 (Kino-Komfort). Weiter als die 4K-Grenze lohnt sich 4K bei dieser Groesse nicht.',
];
include __DIR__ . '/../../../tools/viewing_distance_calc_tool.php';
