<?php
// Localized labels for apm-test — auto-generated by generate-locale-wrappers.py
$apm_labels = [
    'aria' => 'APM 테스트 - 분당 액션 카운터',
    'instruction' => '시작을 누르고 패드에 포커스를 준 뒤 평소처럼 클릭·단축키·드래그를 실행하세요. 각 클릭이나 비수정키는 1액션.',
    'start' => '시작',
    'stop' => '중지',
    'reset' => '초기화',
    'current_apm' => '현재 APM',
    'peak_apm' => '최고 APM',
    'avg_apm' => '세션 평균',
    'total_actions' => '총 액션',
    'elapsed' => '경과 시간',
    'clicks' => '클릭',
    'keys' => '키 입력',
    'pad_hint' => '여기를 클릭해 패드에 포커스.',
    'reference' => '팁: RTS 캐주얼 40-80, 실버 100, 플래티넘 200, 마스터 300+, 프로 300-450 지속에 피크 800+.',
];
include __DIR__ . '/../../../tools/apm_test_tool.php';
