<?php
// Localized labels for burn-in-test — auto-generated by generate-locale-wrappers.py
$bi_labels = [
    'aria' => 'OLED 번인·이미지 잔상 테스트',
    'instruction' => '전체화면을 클릭하세요. 화살표 또는 버튼으로 색상을 전환하세요. 흰색 30-60초는 잔상을 드러냅니다. Esc로 종료.',
    'mode' => '모드',
    'mode_cycle' => '색상 사이클 (W, K, R, G, B, C, M, Y)',
    'mode_checker' => '미세 체커보드',
    'mode_scroll' => '스크롤 리프레셔',
    'auto' => '자동 전환',
    'auto_off' => '꺼짐',
    'auto_5' => '5초마다',
    'auto_15' => '15초마다',
    'auto_60' => '60초마다',
    'fullscreen' => '전체화면',
    'exit_fs' => '종료',
    'next' => '다음',
    'prev' => '이전',
    'current_color' => '현재 색상',
    'reference' => '팁: 리프레셔를 밤새 돌리면 경미한 OLED 잔상 회복에 도움. 8시간 흰색 후 남는 영구 번인은 복구되지 않습니다.',
];
include __DIR__ . '/../../../tools/burn_in_tool.php';
