<?php
// Localized labels for color-range-test — auto-generated by generate-locale-wrappers.py
$cr_labels = [
    'aria' => '색상 범위 테스트 - 제한 RGB vs 풀 RGB 감지',
    'instruction' => '각 행을 보세요. 풀 디스플레이는 각 패치를 구분해 보여줍니다. 제한 디스플레이는 앞부분(순수 검정)과 뒷부분(순수 흰색)이 합쳐집니다.',
    'near_black' => '검정 근처 (RGB 0-31)',
    'near_white' => '흰색 근처 (RGB 224-255)',
    'ramp' => '연속 그라디언트 (0~255)',
    'fullscreen' => '전체화면',
    'exit_fs' => '종료',
    'reference' => '팁: Windows는 HDMI를 기본값으로 제한 범위로 보내는 경우가 많습니다. NVIDIA: 해상도 > 출력 동적 범위 = Full.',
];
include __DIR__ . '/../../../tools/color_range_tool.php';
