<?php
// Localized labels for edpi-calculator — auto-generated by generate-locale-wrappers.py
$ec_labels = [
    'aria' => 'eDPI 계산기 - 게임용 유효 DPI',
    'instruction' => '마우스 DPI와 게임 내 감도를 입력하세요. eDPI = DPI × 감도로 게임 간 에임을 비교합니다.',
    'dpi' => '마우스 DPI',
    'sens' => '게임 내 감도',
    'edpi' => '유효 DPI (eDPI)',
    'cm_360' => 'cm/360 (추정, yaw 0.022 기본)',
    'reference' => '프로 기준: 800 DPI × 0.5 감도 = 400 eDPI',
];
include __DIR__ . '/../../../tools/edpi_calculator_tool.php';
