<?php
// Localized labels for screen-uniformity-test — auto-generated by generate-locale-wrappers.py
$su_labels = [
    'aria' => '화면 균일도 테스트',
    'instruction' => '색과 밝기를 고르고 전체화면을 누르세요. 좋은 패널은 끝에서 끝까지 균일합니다. 밝기 불균형, 색조가 있는 코너, 구름 무늬는 균일도 문제입니다.',
    'color' => '색상',
    'c_gray' => '중간 회색 (클라우딩 감지)',
    'c_black' => '검정 근처 (IPS 글로우 + 백라이트 번짐)',
    'c_white' => '흰색 (밝기 저하 감지)',
    'c_red' => '빨강',
    'c_green' => '초록',
    'c_blue' => '파랑',
    'brightness' => '밝기',
    'fullscreen' => '전체화면',
    'exit_fs' => '종료',
    'reference' => '팁: 20, 50, 80% 밝기에서 각각 테스트 - 문제는 특정 밝기 구간에서만 나타날 수 있습니다. 60-90 cm 물러서고 조명을 끄면 클라우딩이 잘 보입니다.',
];
include __DIR__ . '/../../../tools/screen_uniformity_tool.php';
