<?php
// Localized labels for screen-size-calculator — auto-generated by generate-locale-wrappers.py
$ss_labels = [
    'aria' => '화면 크기 계산기',
    'instruction' => '화면 비율을 고른 뒤 대각선·가로·세로 중 하나를 입력하세요. 나머지 두 개가 인치와 cm로 자동 계산되며 가시 면적도 표시됩니다.',
    'aspect' => '화면 비율',
    'measured' => '아는 값은',
    'measure_diagonal' => '대각선',
    'measure_width' => '가로',
    'measure_height' => '세로',
    'value' => '값',
    'unit' => '단위',
    'diagonal' => '대각선',
    'width' => '가로',
    'height' => '세로',
    'area' => '가시 면적',
    'reference' => '팁: TV는 대각선으로 광고되지만 가구에 올리는 건 가로 길이입니다. 55 16:9와 55 21:9는 매우 다릅니다.',
];
include __DIR__ . '/../../../tools/screen_size_calc_tool.php';
