<?php
// Localized labels for sound-test — auto-generated by generate-locale-wrappers.py
$st_labels = [
    'aria' => '사운드 테스트 - 채널 확인 및 주파수 스윕',
    'instruction' => '처음인가요? 첫 재생 시 브라우저가 오디오 권한을 요청합니다. 시작 전에 시스템 볼륨을 30% 정도로 낮추세요 - 순음은 크게 들릴 수 있습니다.',
    'channel' => '채널',
    'ch_left' => '왼쪽만',
    'ch_right' => '오른쪽만',
    'ch_both' => '양쪽',
    'ch_pingpong' => '핑퐁 (L/R 교대)',
    'freq' => '주파수',
    'freq_value' => 'Hz',
    'volume' => '볼륨',
    'volume_value' => '%',
    'play' => '재생',
    'stop' => '중지',
    'sweep' => '100 Hz ~ 10 kHz 스윕',
    'now_playing' => '재생 중',
    'idle' => '대기',
    'reference' => '팁: 양쪽 모드에서 한쪽만 들리면 배선 문제(TRS 완전히 안 꽂힘, 케이블 불량, BT 페어링)입니다 - 소프트웨어 문제가 아님.',
];
include __DIR__ . '/../../../tools/sound_test_tool.php';
