<?php
// Localized labels for viewing-distance-calculator — auto-generated by generate-locale-wrappers.py
$vd_labels = [
    'aria' => '시청 거리 계산기',
    'instruction' => '화면 대각선과 해상도를 입력하세요. THX 최적(36° FoV), SMPTE 영화관(30° FoV), 4K와 1080p의 구분이 사라지는 최대 거리를 보여줍니다.',
    'diagonal' => '화면 대각선',
    'resolution' => '네이티브 해상도',
    'unit' => '단위',
    'thx' => 'THX 최적 (36° FoV)',
    'smpte' => 'SMPTE 영화관 (30° FoV)',
    'uhd4k' => '4K UHD 최대 거리',
    'min_4k' => '이보다 멀면 4K = 1080p로 보임',
    'angle' => 'THX에서의 각도',
    'reference' => '팁: THX = 36° (몰입), SMPTE = 30° (영화관 편안). 4K 최대 거리보다 멀리 앉으면 그 크기에서 4K는 쓸모 없습니다.',
];
include __DIR__ . '/../../../tools/viewing_distance_calc_tool.php';
